== Forward by the Editor

William Shewen (1631-1695) was an early member of
the Religious Society of Friends (Quakers) in London,
England.
Though he does not appear to have been a traveling minister in the society,
he was nevertheless considered "`a very serviceable
man on truth`'s account in several ways,
and an elder in the church, being of a sound judgment and understanding in the truth.
He had very clear openings in relation to the work of truth,
and also of Satan`'s wiles to hurt and hinder the
progress of it (having had long experience of both),
and therefore could advise and direct the Christian traveler how to keep in the one,
and be preserved out of the snares of the other`" (taken from John Whiting`'s Memoirs).

My goal in preparing this edition of Shewen`'s writings was to make the English
somewhat more readable without changing his meaning or over-modernizing his language.
This was a difficult task, and it was approached with great care,
and in a measure of the fear of the Lord,
believing that the Spirit of God was the true Author behind much of this work.

There are a number of footnotes scattered throughout these writings.
Some are mine, and are labeled Editor`'s Note.
Some appear to be Shewen`'s original footnotes,
and are placed in quotations next to his initials, W. S.

[.signed-section-signature]
Jason R. Henderson

[.signed-section-context-close]
December, 2015
