== Meditations and Experiences

[.chapter-subtitle--blurb]
Made public as a testimony to the right way to God,
revealed and made known in this the Day of his glorious appearing to his people,
that they may be encouraged to walk therein to the end thereof.

[.centered]
__"`Speak unto the children of Israel, that they go forward.`"__ (Exodus 14:15)

[.centered]
__"`He that endures to the end, shall be saved.`"__ (Matthew 24:13)

[.centered]
=== I+++.+++ The Power that Crucifies Sin

It is a precious thing to know what the cross of Christ is,
and how to take it up, and make use of it; for indeed,
it is no less than the power that crucifies sin, and saves from it.
Of this power Christendom is generally ignorant,
having set up something else in its stead, and so sin remains alive, uncrucified,
and salvation is lacking.
For it is not all the gold, silver, and wooden crosses, nor voluntary humility,
in the whole world that are able to crucify one sin, as to the nature of it,
nor to make one disciple, nor enable to watch with Christ one hour,
nor follow him one step in the regeneration.

[.centered]
=== II. The Eye of the Mind Opened

It is a blessed state to know the eye of the mind not only opening, but opened,
by which an ability and wisdom are witnessed to read in the book
of life wherein all the treasures of wisdom and knowledge are hidden.
He or she that knows this light shining, and this eye opened in them,
walks and stumbles not.
This eye and light within is that which Christendom too much despises and rejects,
and therefore they walk in darkness and stumble, and know not where they go.
While we ourselves did so, we were darkness, and walked in it,
and our feet stumbled upon the dark mountains.
In the beginning,
that which shut and stopped this eye and darkened this light within was sin and transgression,
whereby mankind lost the sight and enjoyment of their Creator.
And this I testify,
that no people upon the face of the earth come to
witness this eye of the mind opened again,
except as they come to experience that power in themselves which crucifies sin,
and saves and redeems out of transgression, and are also obedient and subject unto it.

[.centered]
=== III. The Substance of All

The remembrance of the first day`'s work is very precious,
even the separation of the light within from the darkness within,
whereby we came to know each, its name and nature.
By this also our minds were turned from the darkness within, to the light within;
from the power of Satan within, to the power of God within;
from the teachers and books without, to the grace, the anointing,
the true teacher within.
The remembrance of this is very precious.
And now what remains, but that we walk in this light,
that we may be children of it indeed, and that we be always obedient to this power,
and learn of this anointing, till we are fully learned.
This is the substance of all.
It is the end of all words and writings; yes,
it is the end of all the dispensations of God since the beginning.

[.centered]
=== IV. The Beastly Nature Slain

The precious light which shines in the heart is the everlasting Day of God,
in which he walks, and in which he works.
Blessed are those that walk with him, and work with him;
these can tell of his mighty acts, and speak of his wondrous works.
Those who walk in this light, and are become children of this day,
are witnesses of the true everlasting worship which is in the Spirit and in the truth.
Such are come to the substance and end of all the legal administrations and temple worship,
which consisted much in daily killing and daily offering of bullocks, rams, and lambs, etc.
Now those that are come to the worship in Spirit witness a daily dying and a daily offering,
till death is known.
Such know that it is easier to kill a bullock or a ram outwardly,
than to kill or mortify the beastly nature within.
Indeed,
it is a greater work to witness the will wholly resigned up into the will of the Lord,
and the thoughts and imaginations brought down into the obedience of the cross,
than to perform the outward part of worship commanded in the law.
I testify to all,
that those who know not the beastly nature slain and offered up in themselves,
and their thoughts and will subjected, are not come to the end of the law,
nor out from under it, nor to the one everlasting offering--Christ Jesus.

[.centered]
=== V+++.+++ The Law Which is Spiritual

It is very precious (not only when we meet together,
but at all times) to feel our minds exercised by, and meditating in, the law of the Lord,
which is spiritual.
Those that are exercised in this law of the Spirit of Life, and walk in obedience to it,
no evil or temptation shall prevail against them;
but they will witness salvation for walls and bulwarks.
Some were witnesses of old that the law of the Lord was pure and perfect.
Many are witnesses of the same this day, and know it so by the operation of it,
and know themselves subjects to that law which is spiritual within,
which judges every vain thought, and every idle word,
and brings down every vain imagination.
It is a blessed state to be meditating in this law day and night.
For I testify that this law of the Spirit of Life within was man`'s rule
whereby he walked innocently and uprightly before transgression entered,
and before outward characters were invented,
or before any outward law was written or engraved on tablets of stone.
To this again are many now called, and many are coming, and are come.
Blessed forever are those that walk therein, and are ruled thereby.

[.centered]
=== VI. Knowing Christ Not After the Flesh

The true knowledge of Jesus Christ is very
precious--to know him as he was before Abraham was,
and to know the knowledge of him after the flesh passes away.
Such know him to be the Tree of Life, which grows in the midst of the garden of God,
and they sit under his shadow with great delight, and his fruit is sweet to their taste.
They that eat thereof, know that food of which the world is ignorant,
and which is beyond words.
Fruit and eating are more than words.
Such are come to witness the gospel promises fulfilled,
and they need no man to teach them.
No man need say to his neighbor,
"`Know the Lord,`" for the knowledge of him abounds in their hearts.

That which makes the meetings of the righteous to
differ from all other meetings in the world is to feel Jesus,
the Savior, in the midst of them,
and to feel their hearts and minds in unity and fellowship with him.
This feeling and knowing transcends all words and professions.
For, for a time Christ`'s very disciples did not so know him,
while he was with them in that prepared body.
Therefore a remnant can call that day blessed wherein their
minds were turned from darkness within to the light within,
which reveals and makes Christ manifest again,
as he was with the Father before the world began, and as he was before Abraham was.

[.centered]
=== VII. The Upright in Heart

It is now as truly witnessed as it was of old that,
"`the eye of the Lord runs to and fro through the earth,`"^
footnote:[2 Chronicles 16:9]
beholding the evil and the good--even that eye which searches the heart, tries the mind,
and shows to man his thoughts.
Our happiness consists in this:
that we have a testimony within ourselves that our hearts
are upright and sincere in the sight of this eye.
This was it which God had respect unto in all ages.
For when his chosen people, the Jews, degenerated from uprightness of heart,
notwithstanding they kept to the outward performances
and observations (as keeping appointed feasts,
new moons and Sabbath days, solemn assemblies, killing and offering sacrifices,
etc.) yet all these things were not accepted, but were an abomination unto him,
while their hearts were gone astray from him,
and were not upright and sincere in the sight of this eye of the Lord.

It is a precious thing to witness that our
hearts are upright in the sight of the Lord,
before his eye that runs to and fro throughout the earth,
that the sin which overtook the Jews of old may never overtake us, namely,
to keep the outward form and lose the power.
Our solemn assembling, our form of sound words,
our outward demeanor into which the life of truth led us, etc., indeed,
all is vain and unprofitable if we do not feel the
same life accompanying us and preserving us in it,
so that we are a living people, walking uprightly before the Lord.
It is the honest and upright heart that is the good
ground where the seed of the kingdom grows,
prospers, and brings forth acceptable fruit.

[.centered]
=== VIII. The Good Things of the Kingdom

It is a very precious thing to witness a true waiting upon the Lord.
Many great and glorious promises are made to those that truly wait upon him.
They that wait upon the Lord shall lack no good thing.
To witness and enjoy this is the substance of all.
While we waited upon invented means, men and books,
upon our own thoughts and imaginations, our own wisdom and understanding,
we lacked the good things,
for these were not sufficient to lead us to the knowledge or the enjoyment of them.
Hereby may all Christendom (so called) be tried and judged, even by this one thing:
they pretend a worshiping and waiting upon the Lord, but they lack the good things,
and the evil things still abound among them.
In this they are found to be false witnesses,
who say they wait upon the Lord but that he has not fulfilled his promises to them.
But a remnant at this day are true and faithful witnesses that the Lord is faithful,
just, and true to his promises,
and that he has fitted and furnished them with the heavenly treasures,
the good things of his kingdom, as they truly wait upon him.
This waiting does not begin when our solemn meetings begin,
neither does it end with them, but remains always.

[.centered]
=== IX. The Operation of Truth

The truth in itself is very precious,
and the revelation and knowledge of it in our hearts is also very precious.
It is in this truth that God is worshiped with that worship
which is more acceptable than all the worships in the world,
whose worshipers profess the truth in words, but know it not,
neither are they made free by it,
and so are found to be false worshipers and false witnesses.
For the revelation and knowledge of the truth brings to freedom from sin.
It gives power over vain thoughts, over passions,
over the will and inordinate affections,
and also removes the ground from which all evil springs.
The revelation and knowledge of this truth brings into that righteousness
which exceeds the righteousness of the Scribes and Pharisees;
it makes clean the inside.
All other knowledge and religion in the world makes clean only the outside at most;
but this makes clean the inside, and then the outside will be clean also.

Oh, what a lamentation may be taken up for the greater part of mankind,
who are not only strangers to the revelation and
powerful operation of the truth in the inward parts,
but also, through the wiles of the enemy of their souls`' everlasting peace,
are begotten into a belief that it is impossible to witness a clean inside,
and to be delivered from all evil on this side the grave!
They are easily persuaded that the enemy of their souls is always near them,
ready on the right hand and on the left to draw them
aside into the way wherein they ought not to walk,
but they have no knowledge or faith in the heavenly truth, virtue, and present power,
which is able to save out of all temptations, and to deliver out of the snares of Satan,
and so are taken captive at his pleasure.
We ourselves were in this state, but now the knowledge of the truth has come,
and we are witnesses of its powerful operation.
Let us persevere and walk in the same, that we may witness the end of its work,
which is to finish and make an end of sin, and bring in everlasting righteousness.
This is the substance of all, and the end of the truth revealing itself.

Now,
in the present sense and enjoyment of the revelation and knowledge
of the powerful operation of the truth within our own hearts,
we cannot help but call to mind the days past in
which the Lord waited to be gracious unto us,
and followed us with his mercies and with his judgments,
often knocking at the door of our hearts, and often appearing unto us,
though we knew him not.
Indeed his long-suffering was great,
wherein he waited to show himself kind and gracious unto us, standing at the door,
till his locks were wet with the drops of the night; but we let him not in,
neither received his kindness, because we neither knew him, nor his love.
But now he has revealed himself unto us.
He has opened that eye that can see him, and opened our hearts to receive him,
and is come to make his abode with us.

Oh Friends, how are we engaged to walk answerable to his great love,
of which we are made partakers!
Indeed we love him, because he first loved us.
We wait upon him, because he first waited upon us.
May we not say, as some of old said, "`What manner of love is this,
that we should be called the sons of God,`"^
footnote:[1 John 3:1]
and be inheritors of such precious promises,
and possessors of the knowledge of that one everlasting truth which makes free!
But Friends, when the knowledge of this truth is enjoyed,
there remains a possibility of losing it again.
The Holy Spirit which seals and establishes us in it, if it be grieved,
will not do its work; and a vain thought given place to will grieve it;
an idle word will grieve it.
Therefore it concerns us all to wait and watch in
that which preserves and keeps out of all evil forever,
namely, the light.

[.centered]
=== X+++.+++ The Plain Pathway

It is a blessed and happy state to have the testimony within ourselves that
our minds are exercised in that wherein the everlasting universal worship stands,
which is not limited to time or place.
This worship is not like the worships which are among the sects in the world,
who pretend only to worship God in certain places, and at certain times.
These think God is pleased with their pretended serving him one day in seven,
or one hour in seven, though at other times they serve themselves (and the evil one),
and speak their own words, think their own thoughts, and do their own works.
Oh, it is lamentable to behold, when I look over the state of Christendom,
and see the apostasy it has degenerated into,
retaining something of the form but denying the power!

Here is our blessedness and true happiness,
that we have our minds exercised in the heavenly light that brings to, and preserves in,
the true everlasting worship which is inward, in the Spirit and in the Truth,
of which all temple and Jerusalem worship (performed outwardly
at certain times and set places) were but types and figures.
This worship in the Spirit and in the Truth is the antitype;^
footnote:[Editor`'s Note--An antitype is the substance or fulfillment
of something that has been represented by a symbol or shadow.]
it is the substance of typical, temporary worships.
Oh my friends, let none of us be found out of this everlasting, universal worship,
which does not begin when we meet together to wait upon the Lord
a few hours to be refreshed together in the sense of his presence,
neither does it end when we part!

And Friends, this rests upon my Spirit to testify,
that none can enjoy true blessedness and spiritual consolation
to their souls farther than they have a testimony in themselves
that they walk in the precious everlasting light that now shines.
To this light, in which God dwells, our minds were at first turned,
and in it the worship in Spirit and truth is learned and performed,
both in this age as in ages past.
The way is, and has been throughout all generations, ONE, and it is a plain pathway.
"`The wayfaring man, though a fool, cannot err in it.`"^
footnote:[Isaiah 35:8 KJV]

In this light, many are now witnesses that God loved them, even while sinners,
and that in the days of their darkness and ignorance, he waited upon them,
to show himself gracious; though then they had no faith in him, no esteem for him,
neither could they see any comeliness in him,
"`his visage being more marred than any man`'s.`"^
footnote:[Isaiah 52:14]
Thus he appeared to them till the light shined out of the darkness,
and gave the knowledge of his glory, which as they walked in,
they became living witnesses of his power in salvation, redemption,
and translation from darkness and the power of Satan,
to the marvelous light and power of God.
Indeed they were translated out of the corrupt nature and degradation,
into the pure divine nature and regeneration;
and so became plants and trees of righteousness, bearing fruit unto God,
and giving him the glory and praise of all his works,
who alone is worthy throughout all generations, forever.

[.centered]
=== XI. Our First Love

It is a blessed state always to live in the sense
and feeling of that love which first visited us,
wherein our minds were turned to the light which shined in the darkness.
For we were then darkness;
but the light made manifest and revealed unto us the gift of God given to us,
which is compared to a little leaven, to a grain of seed, to a pearl hid in the field.
It is precious to know the leaven to work, the seed to grow, the field to be purchased,
and the pearl found, bought, and possessed.
This is more than talk and profession.
Now many can say, as was witnessed of old--"`We are come unto him as unto a living stone,
elect and precious,`"^
footnote:[1 Peter 2:4]
and we are kept by the power of him unto salvation,
and are in him in whom there is no condemnation.

Thus to read and witness the Scriptures is beyond all the
talk and notions that are in the world which lies in wickedness,
where the guilt and condemnation is.
As we continually live in the sense and feeling of
that precious love which at first sought us out,
and pulled some of us as brands out of the fire,
and others as swine wallowing in the mire, I say, as we remain sensible of this love,
we shall feel our hearts more and more engaged to walk worthy of it.
We shall not only profess grace, but live under it.
We shall not only profess light, but walk in it, that we may be perfect children of it.
For if we live not the life of what we profess,
sorer judgments will pursue us than many others who are called as we are,
but have not tasted of the heavenly power as we have.
Therefore it concerns us to be watchful, and to retain our first love.
For indeed it is possible, after the house is swept and garnished,
and the unclean spirits cast forth, that they may return and enter again.
Therefore it is very precious,
not only to know that blessed power that casts forth the unclean spirit,
and sweeps and garnishes the house with heavenly treasures,
but also to dwell and abide in the same,
and by it to be preserved from being defiled again.
This is the substance of the Christian religion.
This is the end of all ministering, speaking, and writing.
This is more than hearing ten thousand sermons.
Let us always remain in the feeling of, and obedience to, this power,
and we shall never fall.

[.centered]
=== XII. Preserved in His Power

It is more than words can express to feel
and enjoy that wherein the Kingdom of heaven stands.
It is written in the Holy Scriptures that the kingdom of
heaven stands not in food and drink and outward washings,
but in the power and joy of the Holy Spirit.
To enjoy this is the substance of all;
but none come to receive the joy of the Holy Spirit except
those who are kept by the power in which the kingdom stands,
which power preserves from evil and keeps from falling into temptation.
Many may come to the knowledge of this power,
and may possess it and have some faith in it (which
is beyond all notional sects in Christendom),
yet if they live not obedient to it, and witness being kept by it to the end,
they come not to be children of this kingdom, nor to sit down in it,
nor enjoy its comfort and pleasures.
The bare profession and knowledge of the power is of little worth,
but rather a being preserved by it.
For if any enter into evil and temptation, such grieve the Holy Spirit,
and so cannot have the joy of it, wherein the kingdom stands.
This is that which chiefly distinguishes us from the diverse
sects in Christendom--a being preserved in the power,
and not a talking of it only.

It is written in the Holy Scriptures of truth that Christ Jesus, the second Adam,
when he was tempted by the devil with sore and grievous temptations, ate nothing,
but instead, by the power of his Father that dwelt in him,
withstood the devil and all his temptations.
And when the devil departed from him, angels ministered unto him.
This same power which preserves in temptations,
and keeps from eating or receiving the bait of the enemy or tempter,
we are all to witness in the time of trial, and in the hour of temptation.
It was the first Adam that ate when he was tempted.
Now this eating implied a taking or letting in something,
a giving place to the devil`'s bait, whereby the temptation entered.
He did not stand in the power wherein the heavenly kingdom stands,
which is able to preserve, as did the second Adam.
So departing from this power, he lost the joy of the Holy Spirit,
in which stands the kingdom.
And this all the children of the first Adam do,
who have not faith in that power that saves out of temptation.

This is the substance of the Christian Religion,
which we are called to both profess and possess, namely,
the power and joy of the Holy Spirit, in which the kingdom stands.
This power strikes at the root of all the wickedness and evil in the world,
and is the axe that is laid to the root of the evil tree which has grown up in the apostasy.
This is that by which Christendom must be reformed.
There is no sound reformation but by this, in the particular and in the general.

Friends are witnesses, and many could seal it with their lives,
that there is no other way or means appointed of
God to come and sit down in the kingdom of heaven,
or to attain everlasting salvation, but by believing in the power of God,
in the light of Christ within, to which our minds have been directed.
Indeed,
among the many sects in Christendom there are diverse
other means and ways invented and set up,
but we know them all to be vanity.
We have tried and proved them, and know there is nothing of worth in them.
We are now come to the true and living way, the ancient path,
in which the righteous in all ages walked.
Now this remains, that we always feel our hearts engaged to walk in this way,
and to keep sensible of that power which saves from evil,
that we may adorn our profession.
For if any that profess this everlasting way enter into temptation, or commit evil,
they do not adorn their profession, but are a scandal to it,
and lay a stumbling-block in the way of others,
who are where we were when wandering in desolate places
and traveling in the deserts`' howling wilderness.
The day of such will be turned into darkness,
and the curse will fall upon the one who lays a stumbling-block in the way of the blind,
and leads him out of his way.

Therefore it concerns all to be watchful, and persevere in that which is good;
to be as lights of the world, and as the salt of the earth indeed,
that we may never cease shining or lose our savor.
Whatsoever was written before was written for our learning,
and it is profitable to meditate and consider how many in former
ages had great experience of the power and presence of the Lord,
saw many of his wondrous works,
and traveled through the Red Sea and Wilderness to the borders of the promised land,
and yet through murmuring and disobedience entered not therein,
nor enjoyed the end of the Lord in bringing them out of Egypt`'s land.
And we may in this age also fall short, as they did, if we walk not close with the Lord,
and learn by what is written to take warning,
lest by disobedience and unbelief we fall short of
receiving the great recompense of reward.

[.centered]
=== XIII. The Bread of the Kingdom

The bread of the kingdom is the joy of the Holy Spirit felt and known within,
which satisfies and refreshes the soul.
This is the bread which comes down from heaven.
The show-bread, in the outward temple, was a type and figure of this spiritual bread,
which is indeed the antitype and substance.
The table in the outward temple of the Lord was furnished with outward bread,
and as we witness our bodies to be the temple of the Lord, we shall enjoy this bread,
of which the other was but the type and shadow.
This is the bread that fills and satisfies the hungry,
when husks and all outward things cannot.

[.centered]
=== XIV. The Foundation of God

Many are living witnesses in this day, as of old,
that the foundation of God stands sure, and that this foundation, as now made manifest,
was the foundation of the righteous in all ages.
Indeed, the light, grace, and Spirit of God within,
which mixes not with vain thoughts and evil imaginations,
but discovers them and judges them, is this foundation.
This is the stone the builders in their natural wisdom reject and despise,
and they commend other stones, and invent other foundations,
according to the imaginations of their own hearts.
Now it is a blessed thing, and the duty of every particular,
to witness themselves living stones, built upon this foundation,
and to have their hearts and minds united to it and framed with it.

[.centered]
=== XV. The Teacher Within

The same grace, the same anointing,
which was the saints`' teacher in the primitive times,
is revealed and witnessed in this our day and time.
It is a blessed thing always to learn of him,
for many that have come to the revelation of this teacher,
not waiting low in that which did reveal him (so that self might be made of no reputation,
and the will and selfish spirit brought down) have been deceived,
and have learned of the false teacher, the antichrist, instead of the true,
yet under the name of the true.
Indeed, this has happened in some amongst ourselves, since we were a people.
For know this: that no people ever worshiped the whore, the mother of harlots, the beast,
false prophet and antichrist, under those names and denominations, but being deceived,
gave them good names and believed her to be the true woman, the Lamb`'s wife,
the true prophet, and the true Christ.
This has been the state of all the apostates in Christendom.
For as the mystery of godliness is great, so the mystery of iniquity is great also,
and there are none that are able to discern between the one and the other
except those that come truly to learn of the grace of God,
the anointing within.

Therefore, it is precious always to learn of the grace and anointing,
and to walk in the light to which our minds were at first directed,
for this reveals the deep things of God, and finds out the hidden things of Esau.
The very remembrance of the time wherein our minds were turned from the ways, inventions,
and teachings of men without, to the light, grace, and anointing within,
is very precious;
for hereby we are made partakers of a measure of the same wisdom
and revelation in which John wrote his book of the revelation.
The same Spirit by which he was led to give names to things according to their nature,
and not according to appearance, is now again witnessed.
The great whore, the mother of harlots, the beast and false prophet,
the golden cup that is held forth to the nations, the antichrist in the temple,
and the great red dragon that John saw in heaven,
by the same Spirit these are now revealed and judged;
and as we keep our hearts and ears open to this teacher,
we can never be deceived by them again.
All the nominal professors and sects in Christendom who learn not of this teacher,
are so far deceived that they believe the whore to be the Lamb`'s wife,
and her golden cup, the cup of blessing.
Indeed, these are greedily drinking of it,
not discerning the false prophet and antichrist from the true,
because he gets into the temple of God and clothes himself like unto an angel of light,
and like unto the true Christ.
These also take the great red dragon that appears in heaven to be the Lamb of God.

Therefore it is a blessed thing always to keep our minds
stayed and our feet walking in the heavenly light that now shines,
which reveals the true teacher that teaches and discovers all things,
and gives to see to the ground and foundation of things.
It is a blessed thing to discern spirits,
and to keep out of that wherein the mystery of iniquity prevails.
All the teachings of men and books in the world are but dross and
dung in comparison with this divine teacher--the light,
Spirit, and grace of God within.
This was man`'s teacher and guide before books were written,
before an outward law was written.
And this I testify in the Word of the Lord: that the teachings of all men,
books and writings,
which tend to divert the mind of mankind from this divine teacher within,
are vain and unprofitable, and proceed from that wisdom which is earthly, sensual,
and devilish.
All that lend an ear to it are captivated in the mystery of iniquity.
They are ever learning,
and never able to come to the knowledge of the truth which makes free,
so long as they abide under such teachers.
Many are living witnesses that as they gave up to be taught and led by the true teacher,
the anointing within, they soon became wiser than all their former teachers.

[.centered]
=== XVI. The Ancient Power

The same everlasting power which preserved
the righteous in all ages past out of evil,
and from falling into temptations, is now revealed and witnessed in this our day and age.
This is the same power and arm of salvation that preserved Joseph in Egypt,
Job in all his trials and temptations, Daniel and the three children,
and all the primitive prophets and Christians out of all the fiery trials, assaults,
and buffetings of Satan they met with.
Therefore it is a blessed thing to be truly acquainted with this power,
and always to live in the sense of it.
For indeed it is possible that people may come to the knowledge of this power,
and make a profession of it,
and witness salvation and redemption by it in a great measure,
yet if they do not wait low in their minds till it has fully
wrought the work of salvation and redemption in them,
or wholly brought every thought and imagination into the obedience of Christ,
subdued their own wills and selfish spirit,
and known self made of no reputation and nailed to the cross--I say, without this,
they may fall into the snare of the devil again,
be captivated and again led into temptation.
For it is after such as these that the tempter and destroyer
goes about like a roaring lion seeking to devour,
even the ones out of whom he has been cast and dispossessed.
For it is written that he rules in the hearts of the children of disobedience.
He need not go after these, being already got within them; there he is on his throne.
But it is after the righteous he goes, out of whom he has been cast,
who are redeemed from under his power and translated out of his kingdom.
It is against such as these he appears, not only like a roaring lion,
but as a subtle serpent, and an angel of light.

Therefore it is a blessed thing always to live in the sense, knowledge,
and feeling of this ancient power,
which alone saves and delivers in the midst of all trials and besetments of the evil one.
As the eye of the mind and understanding is fixed upon it, no temptation can prevail.
It is a blessed thing to know your faith increased in it,
for faith in this power of God is compared to a shield,
which is able to quench all the fiery darts of the devil, and to give victory over him.

Now that which was our misery and loss in the time of our ignorance and darkness,
is the misery and loss of mankind in their unregenerate state.
We had no faith in the Spirit of God, which convinced the world of sin.
We did not believe that the same hand of power that smote us for
sin and transgression was able and sufficient to heal us.
Neither did we regard the strivings of God`'s Spirit within,
nor give heed to him that stood at the door of our hearts and knocked,
who long waited to show himself gracious unto us.
He was as a light shining in darkness, but we regarded it not,
and so did not know its virtue and powerful operation.
In this unbelieving and disobedient state, we were children of wrath as well as others,
but having obtained mercy to be faithful,
we have now left all the world which is captivated in the unregenerate
state by reason of their unbelief and hardness of heart.

And herein is the love,
exceeding kindness and mercy of God manifest--in that he loved us while we were enemies,
and waited to show himself gracious while we were sinners,
to be reconciled unto us when we were in rebellion against him,
and enlightened us when we were darkness.
Indeed he often called when we were running from him,
and was near and ready to teach us when we were ignorant
and did not desire the knowledge of his ways.
In this was the exceeding love of God manifest to us then,
and is the same to all the world now.
His love is universal to all, as is testified in the Holy Scriptures:
God so loved the world, that he gave his only begotten Son as a light into the world,
that whosoever believes in him should not perish, but have everlasting life.

It is very precious to walk in this light
which does reveal the love and kindness of God,
and brings to the knowledge and experience of the means of salvation which he has appointed,
and to the feeling of that power which saves from falling into temptation,
even the same power which preserved Jesus when he was tempted in the wilderness.
Now, if any that are come to the knowledge and profession of
this power are not preserved by it from falling into temptation,
and delivered from evil, such are not obedient or faithful to it,
and so do not adorn their profession.
Such do not glorify the power, but are as "`spots in our love feasts,`"^
footnote:[Jude 1:12]
a scandal to the gospel of peace, and enemies to the cross of Christ,
which is the power of God to Salvation.
Now those that live in, and are obedient to, this power, are the wisest, happiest,
and safest people in the world.
They are blessed above all the families of the earth,
blessed with a hundred-fold in this world, and in the world to come, life everlasting.
Such are the salt of the earth which seasons all things,
as a city on a hill which cannot be hid, and as the light of the world indeed.

[.centered]
=== XVII. Those Who Love Your Law

Many are living witnesses that the law of the Spirit of life,
unto which their minds have been directed, is pure and perfect.
They witness it to be so by its operation in them,
by which every appearance of evil is condemned.
It is the happiness of every particular to have the witness
or testimony within themselves that they love this law,
and that they meditate in it day and night.
"`Oh,`" said one of old, "`how I love your law!`"^
footnote:[Psalm 119:97]
Only those who love it are the true witnesses of its purity and perfection.
For it is possible that a person or people not only profess and talk of this law,
but come to some knowledge of it also, and yet not love it, nor meditate in it,
nor feel the power and peace of it.

Those who love the law of God are by it converted and made wise unto salvation,
and though their enemies be very many, and very near also,
yet they cannot prevail against such as love this law.
Indeed, these are the happiest people of all the families of the earth.
No evil prevails against them, and as it has been witnessed of old,
"`Great peace have those that love your law.`"^
footnote:[Psalm 119:165]
So too now, there are living witnesses of the same great peace in this age,
who love the law, which is light.
"`Your law is light,`"^
footnote:[Proverbs 6:23]
said one.
He that loves the light, brings his deeds unto it, to be tried and judged by it;
and after this the great peace is witnessed.

Peace is the reward of those that love the law of God--peace in the inward parts,
even the peace of God, which the world cannot give nor take away.
This one sentence may try all the sects in Christendom,
and all others who profess themselves lovers of the law of God,
yet have not peace in their dwellings.
These have not "`the answer of a good conscience,`"^
footnote:[1 Peter 3:21]
which keeps void of offense towards God and man.
They have not that peace which passes the understanding of man in the fall.
They know not their hearts and minds kept by it, but are found in the evil-doing,
where the tribulation and anguish is, and in the fear which brings torment.
So wherever the doing of evil is, there the law is not loved,
let your talk and profession be what it will.
What is written is infallibly true: "`He that does evil hates the light,`"^
footnote:[John 3:20]
and he that hates the light is wicked.
Truly, to him there is no peace,
the law not being a light to his feet nor a lantern to his path.
He walks in darkness and stumbles, and knows not at what;
and in the end lies down in sorrow.

Therefore, it is very good for every particular not only to know the law of God,
but also to live in the sense and love of this law at all times,
both when they are about their common occasions in the world,
as well as in their solemn assemblings before the Lord.
The love of this pure law of the Spirit of life (which judges
every appearance of evil) makes one wise unto salvation,
even wiser than all former teachers.
And to hear, love, and obey this law (or Word in the heart) is the end of all words,
and the end of all outward dispensations and ministrations,
even though these proceeded from the power of God itself.
For had not mankind degenerated from the love and
obedience of this inward law or command of God,
transgression would have never entered,
neither would sin have had a place in the heart of man,
neither would an outward law have been added or given forth.
For the outward law was added because of transgressions,
and has power over the transgressor so long as he lives disobedient and as a
stranger to the law written in the tablet of the heart by the finger of God.
Indeed,
the inward law existed before any outward law was
written either in a book or on tablets of stone,
and before the cause of it was brought forth into the world.

[.centered]
=== XVIII. The Heavenly Treasure

The day-spring from on high,
and the everlasting light has and does shine out
of darkness in the hearts of many in this age,
and they are, by its heavenly shining,
come to the knowledge of the field where the treasure is hid,
and to the sight of that whose worth and beauty transcends
all the treasures and pleasures this world can afford.
None are to rest in the bare knowledge of this field, but to sell all and purchase it.
All the sects in Christendom who believe not in the light within,
and despise the day of its appearance within themselves,
are so far from enjoying this heavenly treasure that they are wholly
ignorant of the place or field wherein it is hid.

This is sealed in the hearts of a remnant: that there is no other way,
no other means, no other key to be found to open the heavenly mysteries,
nor to unloose their seals, nor to lead into the enjoyment of the heavenly treasure,
but by the holy divine light.
This light has appeared and shined gloriously in their hearts,
unto the discovery and destruction of the man of sin and the mystery of iniquity,
which once wrought and ruled therein.
In this light these have believed and walked,
and seen the wondrous works of the Lord in the deep.
But the people and nations that despise and hate it, walk and dwell in darkness,
and in the region and shadow of death, where the poverty, woe, and misery is.
Here there is stumbling, groping, falling, and wandering in desolate places,
where man labors for vanity and lies down in sorrow.
Therefore, the hearts of the remnant are greatly engaged unto the Lord,
to walk worthy of the riches of his grace, light, and heavenly treasure,
of which he has made them partakers.

[.centered]
=== XIX. The Day of Salvation

The light of the glorious gospel now shines.
The day of salvation is come,
even the salvation of God which he has prepared before the face of all people.
This is the day of great salvation, which many righteous men and prophets saw afar off,
and prophesied of, that is now revealed unto us.
It is a blessed thing, not only to know the appearance of the day of salvation,
but to know the joy of it, the joy of God`'s salvation,
and to know it as walls and bulwarks to save and defend,
not only from the besieger without, but also from the enemy within.

This is the glorious light of the Gospel
that shines in this day of salvation now revealed,
and as we walk and abide in it, we shall be as strong as an army with banners,
and witness victory over our enemies within, which are our greatest enemies.
To be saved from thinking our own thoughts, speaking our own words,
and doing our own works (Isa.
58:13), this is the great salvation that brings to the true Sabbath of rest,
to the true keeping the holy day unto the Lord.
One that enjoyed this salvation, asked this question--"`How can we escape,
if we neglect so great a salvation?`"^
footnote:[Hebrews 2:3]
It is a question that includes an impossibility,
for there is no escaping wrath to come for those that neglect
this great salvation which has now appeared unto them,
for there is no other way or means appointed of God besides this gospel light,
or great day of salvation, which has appeared to us.

This is my testimony: that none can receive the joy of God`'s salvation,
enter into the Sabbath of rest, or keep the holy day unto the Lord,
further than they know a ceasing and a being saved from thinking their own thoughts,
following their own wills, and obeying their own wisdom.
For the selfish thoughts that arise within are the root
of evil and the foundation of the kingdom of darkness;
and the light of this day of salvation is as the axe laid to the root of the evil tree.
So it is a blessed thing for people to meet and wait together,
and to walk in this heavenly light and day of salvation,
which discovers and judges every vain thought and foolish imagination, subdues them,
and brings them down into the obedience of Christ.
In this, as they walk and abide, they truly differ from all other families of the earth;
for in this heavenly gospel light, which judges every appearance of evil,
stands the true fellowship and true unity.
Indeed,
this is the foundation of that Church against which the gates of hell shall never prevail.
And as they walk and dwell therein, the power of death and hell shall never break them,
but they shall remain as Mount Zion which can never be removed.
In this stands their happiness and safety; out of this, they are as weak as other people.

[.centered]
=== XX. Sitting Down in the Kingdom

It is a blessed thing to wait for the appearance
of him who is the consolation of Israel,
and for the coming of his kingdom,
but it is more blessed to be witnesses of his appearance, and to know his kingdom come.
And it is most blessed of all, to know a sitting down in the kingdom with him,
in the glory of his Father, and our Father, his God, and our God.

[.centered]
=== XXI. The Appearance of Jesus

It is a blessed thing to truly know how to wait for the appearance of Jesus,
and to know him when he does appear.
I say, this is very blessed; but it is more blessed, or a greater degree of blessedness,
to be witnesses of his appearance, and to join with him when he does appear,
and in so doing to experience the end of his appearance accomplished,
abiding with him till it be finished,
truly understanding the end for which he does appear,
and the state and condition at his appearance.
Indeed,
this is the main thing chiefly to be understood and minded throughout all dispensations.
And under them all, his appearance is to be carefully minded and regarded,
though it be in his first or lowest appearance, which is to convince of sin,
self-righteousness, and judgment, in order to destroy sin, to finish transgression,
and to bring in everlasting righteousness.
For except people abide with him and love his appearance in the ministration of condemnation
(which brings tribulation and anguish upon the soul that has sinned),
they can never come to enjoy and inherit the ministration of life and salvation,
nor ever come to enjoy the glory of his appearance "`the second time,
without sin unto salvation.`"^
footnote:[Hebrews 9:28]

This is the loss and misery of mankind,
and was our loss and misery in the day of our ignorance,
that we knew not how to wait for the appearance of Christ, or the coming of the just one.
Neither do they, nor did we, know him when he did appear; for he often appeared unto us,
and stood at the door of our hearts and knocked,
and waited to show himself gracious unto us; but we not knowing it was him,
did not regard him, nor open unto him.
Yet he was indeed the desire of our hearts, and the one whom we longed to enjoy.
Yes, he is the desire of all nations, the light and salvation of the Gentiles,
the consolation and glory of Israel.
But in this was our loss and misery: that we knew not how to wait for his appearance,
neither did we know him when he did appear.

So I say again,
it is a blessed thing for a people to know how to
wait for the appearance of Jesus the Savior,
and to know him when he does appear.
But behold, there is a greater degree of blessedness, namely,
to be witnesses of his appearance, and to know the coming of the just One,
or the rising of the Sun of Righteousness with healing under his wings,
and to be able to say with the primitive Christians,
"`We know that the Son of God is come,
and has given us an understanding whereby we know him that is true,
and are in him that is true, even in his Son Jesus Christ;
this is the true God and eternal Life.`"^
footnote:[1 John 5:20]
Truly, this is a high and heavenly knowledge, and a blessed state.
This is the mark and prize of the high calling of
God in Christ Jesus unto which we have been called.
Indeed, this is the state that all are to wait for, inherit, and possess,
and not to sit down short of it.
If this is not witnessed and enjoyed, all profession is vain, all knowledge is vain,
all religion and talk of Christianity is vain and of no worth.
For it is he that believes that Christ is come in the flesh,
and that demonstrates the livingness of his faith by the works thereof, that is of God,
and God dwells in him, and he in God.
This is more than a bare profession or verbal confession,
according to the testimony of John, in his first epistle, chapter 4.

[.centered]
=== XXII. The Little Stone

It was a spiritual and heavenly vision which the prophet Daniel had,
when he saw the interpretation of the king`'s dream,
where a stone was cut out of the mountain without hands, smote the feet of the image,
and broke in pieces the iron, the brass, the clay, the silver, the gold,
and became a great mountain that filled the whole earth.
A remnant in this age are come to the same everlasting light and spiritual eye whereby
they see the power of God (signified by that stone) prevail against all imagery,
not only without, but also within, and know the ground of it shaken and removed.
The dark thoughts and imaginations of men are the
grounds of the imagery upon the face of the earth,
and the power that breaks them down,
and brings every thought into the obedience of Christ, is the antitype of that stone,
and its work revealed to Daniel and dreamed of by the king.

In this day of light and knowledge some are come
to witness this little stone become a great mountain,
and to fill the earth, and to be the chief foundation and corner stone,
elect and precious.
Indeed, it is the rock and hiding place of the righteous in this and all ages.
These abide in it,
whereby they are preserved from making likenesses and images
for themselves either of things in heaven or things on earth,
or from the many mixtures prefigured by the iron, brass, clay, silver, and gold,
and defiling and corrupting themselves therewith.
There is not another means of preservation,
nor of coming to receive the white stone (which John in
his vision and revelation saw) wherein is the new name written,
which none knows save he that has it.
This is the name which is better than the name of sons or daughters.
He that reads let him understand, and give God the glory forever.

[.centered]
=== XXIII. The Way

This I testify, that the way of life and everlasting happiness,
the way that brings to the sitting down in the kingdom of God with Abraham, Isaac,
and Jacob, which was the way of the righteous in all ages,
is now again revealed and made known.
This way is the true everlasting light that now shines, not only in darkness,
but out of it.
This light is the thing to which our minds were at first turned,
which judges every appearance of evil,
every vain thought and evil motion that arises within.
And as there is a walking in this way, a sitting down in the kingdom will be experienced.
For we have been and are called to inherit substance, to possess life,
and to sit down with Christ in heavenly places.
So it is a precious thing for all that know this
way to persevere in it till they possess these things,
and in this way to abide, which way is the light of Christ within,
and there is not another.
The walking in this way distinguishes them from all
the nominal professors upon the face of the earth,
even this light that judges every appearance of evil.

It is a precious state to feel the mind stayed upon the Lord, walking in his way,
and to know the girdle and bridle of truth, and to be girded and bridled with it.
Indeed it is precious to know every high thought
and imagination brought down and subjected unto Christ,
the light and the way.
This is possible to be known now, even as in time past.
It is in the thoughts, will,
and imaginations that the enemy of man`'s happiness gets and builds his strongholds,
and until they are broken down, subjected, and destroyed by the power of God within,
no peace, quietness, and soul satisfaction can be enjoyed.
Without this there is no sitting down in the kingdom of God, nor can the soul attain to,
or partake of, the rivers of pleasure that are at his right hand.

[.centered]
=== XXIV. Life and Peace

It is as truly witnessed now, as in days of old,
that to be spiritually minded is life and peace.
Indeed, to mind the Spirit, to have our minds,
thoughts and wills exercised by the Spirit of truth, is life and peace;
and to be carnally-minded is death, sorrow, and trouble.
These things are not only read, but truly known,
and every particular may feel both within.

[.centered]
=== XXV. Jesus in the Midst

It is as we meet and wait together in the Spirit,
and as we live and walk in the Spirit,
that the worship of God in Spirit and truth is performed,
of which worship all the bare professors upon the face of the earth are ignorant.
Such as wait and worship in the Spirit know Jesus in the midst of them to be their Savior,
teacher and leader, and as they follow and obey him (though but as one of a family,
and two of a tribe) they will be as the light of the world, as the salt of the earth,
and as patterns and examples of righteousness to all that behold them.

[.centered]
=== XXVI. The Arm of the Lord Revealed

It is a precious thing for every particular
to know the right arm of the Lord which brings salvation,
and to witness a sitting down at his right hand, where the sheep lie down,
and where the rivers of pleasure run softly, and to drink of the same,
which refresh the whole city of God.
To feel this arm of the Lord, and to know it revealed,
and to come to a sitting down at his right hand, is the end, sum,
and substance of the Christian religion.
Such as these know salvation for walls and bulwarks,
and are as Mount Zion which cannot be moved.

[.centered]
=== XXVII. Rivers of Pleasure

It is a very blessed state, always to live, walk, meet together,
and wait in that which gives free access to the throne of grace,
and which leads into the presence of Him that sits thereon,
in whose presence (as some of old could witness) were rivers of pleasures,
and at whose right hand was joy forevermore.
Oh, all that taste of one drop of this river,
and partake of the least measure of this joy,
know them to over-balance and outweigh all the treasures, joys,
and pleasure that this world and the glory of it can afford!

[.centered]
=== XXVIII. The Watchtower of the Righteous

The light, to which our minds have been turned,
was the watchtower of the righteous in all ages,
and is the same to the righteous in this age,
and to all people upon the face of the earth.
All pretended watchmen in Christendom who watch not in this tower, watch in vain,
and see nothing that profits.
This is the word of truth to all Christendom, and to all people:
this light is the one everlasting way that leads unto him,
and that fits and prepares to enter the kingdom of heaven,
gives free access to God and the throne of his grace,
and presents unto him without spot or wrinkle.
Many are witnesses of the beginning of this blessed work,
and have received that faith whereby they believe for the accomplishment of it.
And as they live and abide in this,
the blessed experience of the finishing of the work shall be added to their faith.

[.centered]
=== XXIX. The Power and Sufficiency of the Spirit of Truth

It is a good state for every particular to wait in silence upon the Lord.
These only come to witness obedience to those divine precepts
left upon record in the holy Scriptures--"`Be still,
and know that I am God,`"^
footnote:[Psalm 46:10]
and, "`Let all flesh be silent before the Lord.`"^
footnote:[Zechariah 2:13]
Thus to wait and to worship in the heavenly Spirit that brings to stillness,
to a standing still and beholding the salvation of God,
to the silence of all flesh within,
to the stopping of all voices and motions to evil within,
and to the obeying of the voice and power of God within,
this is the worship of God in the Spirit and in the truth, in the inward parts,
which God loves, even to worship, obey,
and follow the appearance and manifestation of the Spirit of God within.
Indeed, the world and its proud professors are strangers to this worship.
And in this we differ from them all:
that we are found waiting and worshiping in that which silences all flesh
and brings to the standing still and beholding the salvation of God.

The Spirit of truth, which convinces the world of sin,
is that wherein the universal worship of God stands and is performed.
This I testify of it: that there is power and sufficiency in it,
not only to convince of sin, reprove, and condemn for sin, but also to convert, change,
cleanse, and redeem the whole world of mankind from sin, if they would believe in it,
love it, receive it, and obey it.
This is the condemnation of the world, that light is come into it,
and they love darkness and will not bring their deeds to the light, nor love, believe,
or walk in it.
So it is that the sayings of Christ are verified upon them,
"`Except you believe that I am he, you shall die in your sins,`"^
footnote:[John 8:24]
and, "`Where I go, you cannot come.`"^
footnote:[John 8:21]

Many are witnesses of the power and sufficiency of this Spirit of truth,
and of its redeeming power from sin, and of the strength of it.
These are not convinced of sin by it as the world is,
but being redeemed from committing sin,
they know this Spirit to be their comforter and leader into all truth.
It is very precious to be found in the true disciples`' state,
waiting for the comfort and leading of the Spirit of truth,
and witnessing the same within themselves.

A remnant in this day,
who have received this Spirit and followed the leadings of it,
are able to say as some of old did, "`We are not come to Mount Sinai,
where the voice of words is heard, where the thunderings, lightnings,
and earthquakes are, but to Mount Zion, the city of the living God,
the heavenly Jerusalem, and to an innumerable company of angels,
to the general assembly and church of the firstborn, which are written in heaven,
and to God the judge of all, to the spirits of just men made perfect; to Jesus,
the mediator of the new covenant, and to the blood of sprinkling,
that speaks better things than that of Abel.`"^
footnote:[Hebrews 12:24]
This is a high and heavenly state, which the primitive Christians were come unto.
Indeed, even while in their earthly tabernacles they enjoyed the heavenly treasure.
Such as these have the witness in themselves,
that they are inhabitants and fellow citizens of this heavenly Jerusalem,
wherein no unclean thing can enter.
Even while they dwell in these houses of clay, they walk in this city,
and have their citizenship in heaven with God, Christ,
and holy or just men`'s spirits made perfect.
This the spirit of this world, though clothed with the name of Christianity, cannot bear.

[.centered]
=== XXX. The Second Appearance of Christ

It is a very blessed state, to be found true waiters for, and witnesses of,
the second coming of Christ, which is "`without sin unto salvation.`"^
footnote:[Hebrews 9:28]
For true happiness does not consist in having seen one of the days of the Son of Man,
or in being witnesses of his first appearance, wherein he convinces and reproves for sin,
but in waiting for the witnessing of his second coming to cleanse, save,
and redeem from sin.
Herein is the joy of God`'s salvation felt and enjoyed.

Christ`'s appearance is first to convince of sin,
and this is a ministration of condemnation, which is glorious in its time.
But there is a ministration which exceeds it in glory, which all are to wait for,
witness, and not sit down short of.
This is the mark of the high calling,
the high and heavenly state which they are called to,
even to know the second coming of Christ without sin unto salvation,
and a being presented to the Father without spot or wrinkle.
To possess and enjoy this is the end, sum,
and substance of all the dispensations of God towards mankind ever since the fall.
This is the end of all good words and writings,
and the end of Christ`'s first and second appearance.
All men have sinned and come short of the glory of God,
and must therefore know the ministration of judgment and condemnation
fulfilled in and upon them before they can know the glory that is in it,
and before they come to know the second ministration, which exceeds it in glory.

It is a precious thing to be inward with the Lord,
and to feel our hearts drawn near unto him, waiting for the appearance of Christ,
that when he does appear,

"`we may appear with him in glory.`"^
footnote:[Colossians 3:4]
This is the high and heavenly state that some were in when they could say,
"`Truly our fellowship is with the Father and with the Son.`"^
footnote:[1 John 1:3]
To witness this, is the feast of fat things prophesied of,
and the broad rivers and streams which make glad the city of God,
beyond what all the dainties of the earth can afford.
This is the soul`'s delight, rest, and happiness, which some did enjoy in former ages,
as a remnant do in this age, praises to God forever.

To mind the Spirit, or to be spiritually minded, not only in our solemn meetings,
but at all times, is our duty, and is very precious.
Then will the testimony of one in primitive times be found true, when he said,
"`To be spiritually minded is life and peace.`"^
footnote:[Romans 8:6]
Here death and trouble are taken away, the ministration of condemnation is ended,
having done its work.
The Word which was as a hammer, fire, and sword has broken down, burnt up, destroyed,
and purged away the filth of the daughter of Jerusalem, and is now become as milk, honey,
and balm.
Indeed, it is as a glorious light that shines more and more unto the perfect day,
and as a shield, fortress, and tower of defense,
where there is everlasting peace and safety,
salvation being as walls and bulwarks against which the enemy cannot prevail,
and nothing can enter that would defile.
In this state were some in the primitive times, when they could say,
"`We can do nothing against the truth, but for it;`"^
footnote:[2 Corinthians 13:8]
and it is possible to say and do the same now.

[.centered]
=== XXXI. The True Shepherd

It is a blessed thing for a man to know within himself,
and be able to say from a living experience, as one of old did,
"`The Lord is my Shepherd, I shall not want.`"^
footnote:[Psalm 23:1]
Such are witnesses of the truth of those sayings of Christ Jesus,
"`My sheep hear my voice, and I know them, and they follow me,
and I give unto them eternal life; and they shall never perish,
neither shall any man pluck them out of my Father`'s hand.`"^
footnote:[John 10:27-28]
It is as this voice is heard, obeyed, and followed,
that there is a leading out of that state where the wants are,
and a coming into the green pastures where the true and safe feeding is,
and where is the lying down in the valley where none can make afraid,
and where the bread is sure and the water fails not.
And this I testify:
all that do not hear and obey the heavenly voice
of the true Shepherd are goats and swine,
and not sheep, let them profess what they will.
These feed upon husks, and are wandering in the dry places,
and upon the barren mountains where the wants are,
and are strangers to the green pastures of life and salvation.

[.centered]
=== XXXII. Worship in Spirit and Truth

It is a very blessed thing for people to know how to worship God aright,
and to be found in this worship, not only at set times and appointed places,
but at all times and in all places.
This is the spiritual worship, or the worship in Spirit and in truth;
and these are the spiritual worshipers which God seeks and accepts.

This worship excels all other worships upon the face of the earth,
with their set times and appointed places,
which stand in saying so many prayers in a day,
and reading and singing so many lessons a day, and hearing so many sermons a day,
and other outward observations.
Such worship stands in time, place, letter, and form; but they that worship God aright,
worship in the Spirit and in the truth, which is pure and universal.

As people are found in this true worship,
they differ from and excel all others upon the face of the earth.
These worshipers know what it is to bow at the name of Jesus,
and what it is to know every thought brought into the obedience of Christ.
These know what his rule, government, and great authority is,
and how all power in heaven and earth is given unto him,
and how all are to worship him as they worship the Father, whether things in heaven,
or things on earth, or things under the earth.
These can confess with their tongues that Jesus Christ
is Lord to the glory of God the Father,
truly and experientially being witnesses of his heavenly power and rule in their hearts,
minds, and understandings, giving victory over all vain thoughts, self-will,
carnal desires, and wanderings of the mind.
These are the worshipers that know the old man put off with his deeds,
and the new man put on.
They know the old things cast away, and all things become new,
and what it is to enjoy the Sabbath rest,
where an end is put to thinking their own thoughts, speaking their own words,
and doing their own works.
They know what it is to bear no burden upon the Sabbath day;
and what it is to enjoy the comfort of the Scriptures,
and to enjoy the good things of which they testify.
Such are partakers of that which the righteous in all ages did enjoy,
and are in unity with just men`'s spirits, being come to God, the judge of all,
who is blessed forever.

Our peace, joy, consolation,
and continual happiness stand in being exercised in this worship,
witnessing the power of God, the name of Jesus, over all in ourselves,
all bowing under it, and yielding obedience to it,
as in the innocency before transgression,
when the earth was subdued in the dominion of God, and the heavenly rule was over all.
Indeed, the true worship in the Spirit and in the truth brings again into this,
and makes free from the contrary, as truly as is testified in the Scriptures:
"`If you know the truth, the truth shall make you free`"^
footnote:[John 8:32]--free from the evil that is in the world, from the evils within,
and from the enemies within, which are the greatest enemies.
Except this freedom be known, all other knowledge is vain,
all religion and profession is vain, all talk of God, Christ, and Christianity is vain.

[.centered]
=== XXXIII. Delight in the Law of the Lord

Blessed are those who have their minds and hearts always exercised by
that which leads into the fellowship of "`just men`'s spirits made perfect.`"^
footnote:[Hebrews 12:23]
These also have unity with the words and testimonies
left upon record in the Scriptures of truth,
as is written by one in the Psalms,
"`Blessed is the man that walks not in the counsel of the ungodly,
nor stands in the way of sinners, nor sits in the seat of the scornful,
but his delight is in the Law of the Lord, and therein does he meditate day and night.`"^
footnote:[Psalm 1:1-2]
The same blessed state is to be witnessed now,
which is more than to read and sing all the Psalms;
and he only is the blessed man that does these things.
If Christendom had learned this lesson (which they have no doubt read and sung),
they would not have become as a vast, howling wilderness,
and as a desert which brings forth no fruit to God.
But having lent their ear to the wicked one, and walked in the way of sinners so long,
they have come to believe that it is impossible to walk
in any other way while on this side of the grave.

In this condition we ourselves were,
while the veil of the covering was over our hearts.
We dwelt in this thick darkness, where the ear is lent to the wicked,
and the way of the sinner and seat of the scornful is known,
and we knew not the way out of it.
That which dispersed this thick darkness and took away the veil from off our heart,
and stopped the ear that hearkened to the wicked one,
and blinded that eye which led us to walk in the way of sinners,
and brought down that exalted spirit that sat in the seat of the scornful; I say,
that which has done all this for us was, and is no other than,
the power of God working in his precious light, to which our minds were at first turned,
and in which we have believed.
And as we walk and abide in this,
we witness such sayings as these in Scripture fulfilled,
"`They that see shall be made blind, and they that are blind shall see,`"^
footnote:[John 9:39]
and "`The blind shall be led by a way they know not, and the lame shall leap as a deer;`"^
footnote:[Isaiah 42:16 and 35:6]
and "`The mighty shall be brought from their seat, and those of low degree exalted.`"^
footnote:[Psalm 62:9]
As one walks in and abides with that which wrought these things,
a delight in the law of the Lord is known, and a meditating in it day and night.

Truly,
there is nothing else able to preserve us from lending an ear to the wicked one again,
and from walking in the way of sinners again,
and to keep down the spirit of exaltation from rising again,
but the delighting and meditating in this law.
This is "`the law of the Spirit of Life,`"^
footnote:[Romans 8:2]
which has made us free,
and is able to preserve us in the freedom unto which we have attained.
All that are strangers to this law, and to meditating in it, will give ear to the wicked,
walk in the way of sinners, and sit in the seat of the scornful,
let their profession be what it will.
By this one Scripture,
all the sects in Christendom (who profess the Scriptures to be their rule) may try themselves,
whether they are in the state of the blessed man, or in the state of the cursed man.
They need not hire a scholar or learned Rabbi to give them the meaning of the Scriptures,
for they were spoken by plain men,
and are understood only by those who are come to the Spirit.
Those that obey the wicked one lend their ear to him,
and those that commit sin walk in the way of sinners.

[.centered]
=== XXXIV. The Chamber of His Presence

It is one of the fundamental doctrines of
religion to believe that God is omnipresent and almighty,
that is, that he is present at all times and in all places.
This is generally professed and believed among the sects in Christendom,
though in many it is no more than a bare profession
or a traditional and historical faith,
for they are not true witnesses of it.

Herein is the difference between those who do,
and those who do not witness the presence of the Lord and the almightiness of his power:
only the former know the ground and reason why Moses
(that eminent servant of the Lord) said,
"`If your presence does not go with us, do not bring us up from here.`"^
footnote:[Exodus 33:15]
This was the delight of the soul of the righteous in all ages and generations past,
and is so now, even to feel the comfortable presence of the Lord,
and to know the light of his countenance lifted up upon them.
This makes their hearts more glad than the increase of corn, wine, and oil,
and is better than them all.
This was the strength and encouragement of the righteous in all ages,
and what made them willing to suffer for his name.
This carried them through the water and through the fire.
This made them sing and rejoice in prison and in the stocks,
and willing to joyfully suffer the spoiling of their goods.
And friends, except this living presence be felt and enjoyed, known and lived in,
we are as weak as any other people.
And indeed, if any lose or depart from it, such will become as wicked as others as well.

Therefore it is a very precious thing for every
particular to always prize the riches of that grace,
and the glory of that light, to which their minds were at first turned.
For this grace and light has led a remnant into the chamber of his presence,
into the banqueting house, where the banner over them is love,
and is leading still others into the same.
Indeed, this will guide and direct all out of the way of evil and into the way of peace.

Oh, the freeness of this love and grace,
and the glory of this light which has led a remnant (who
have loved it and followed it) into the chamber of his presence,
into the banqueting house,
to the top of that holy mountain where the feast
of fat things and the well-refined wine is enjoyed,
and to the right hand of God, where are the rivers of pleasure.
This is free grace and love indeed.
This love is stronger than death, and better than life.
Oh, the consideration of this love is able to break the heart,
to melt the soul before the Lord,
and to dissolve it into a holy resignation and a pure resolution to live
for the praise and magnifying of it among the sons and daughters of men,
who thereby may be won and persuaded to accept of its offers, and follow its leadings,
that they may know the pleasantness of its paths,
and witness its virtue and operation in their own souls.

[.centered]
=== XXXV. Self Made of No Reputation

It is a blessed thing, and a high and heavenly state,
for every particular to have a witness within that self is made of no reputation.
There is not a people upon the face of the earth that are in the way to
this state besides those whose minds are turned to the light of God within,
and are exercised thereby.
For this light alone discovers and makes self manifest in all its appearances, thoughts,
ways, and imaginations, and leads those that walk in it to the true self-denial,
without which there is no salvation.

For truly the destruction, loss, and misery of all mankind came in at this door,
when man gave heed, credit, and reputation to his own selfish desire, thoughts,
reasonings, and imaginations, and desired to know of himself and be wise of himself.
Then the serpent, who spoke from his own resources (John 8:44), prevailed over him.
Then man entered into the temptation of the devil,
and lost his dwelling place in paradise.
Thus the enemy of man`'s happiness, under a pretense of advancing man,
and bettering his state, and making him of some account and reputation,
drew him into a state of loss and misery.
Self-reputation was the first bait of the enemy, and will be his last.
Therefore watch diligently against it, for herein stands his power,
and by this bait he overcame the first Adam.
And therefore it is a blessed thing to live in the power of the second Adam,
which makes self of no reputation.
For as sin and the devil entered and prevailed by reason of self-reputation,
so shall he be cast forth and overcome by the power of God
in all those in whom he makes self of no reputation.

This is a principal lesson of Christianity which all must necessarily learn
in some measure before they can be such disciples of Jesus as he himself teaches:
"`If any man will be my disciple, he must deny himself, take up his cross daily,
and follow me.`"^
footnote:[Luke 9:23]
Denying of self and taking up the cross are inseparable, and must precede discipleship.
Yet even this state is short of being a friend of God and co-heir with Christ,
bone of his bone and flesh of his flesh.
It is short of sitting down with him at the right hand of God in the kingdom of heaven,
and knowing the Son to surrender the kingdom up to the Father,
so that God becomes all in all.
It is short of knowing it to be meat and drink to do the will of God,
and knowing his fruit to be sweet to their taste,
and sitting under his shadow with great delight,
glorified with that glory which Christ had with the Father before the world began.
In this state, self is truly made of no reputation.
Indeed, the first birth is slain, the serpent`'s head is not only bruised,
but broken and subdued, the second birth rules,
and the elder serves the younger (who delights naturally to do the will of God).
And this is no longer a cross to him, neither is the cross to be taken up by him,
for this is the sheep that knows Christ`'s voice and follows him with delight,
and will not follow a stranger.

[.centered]
=== XXXVI. The Name of the Lord

It is a blessed thing for people to know the name of the Lord.
They that know it can trust in it as a strong tower unto them,
and as a wall of defense within which the righteous dwell safely,
and unto which they fly when danger does attend.
It is very precious for people to meet together and wait in this name.
Such as these find Jesus, the Savior, in their midst,
and know a mounting up as with the wings of an eagle.
These know their bread sure, and their water fails not.
They meet and wait for the better, and not for the worse; they wait not in vain.
Indeed their strength is renewed, they mount upward,
and they know the name of the Lord to be as precious
and as powerful now as it was in ages past.
They know it to be a strong tower, a safe hiding place,
and a precious ointment poured forth, and so they love it, because of its sweet savor,
and because they have been made clean, and are preserved by it as virgins.

These can say, "`Your name is as precious ointment poured forth,
therefore do the virgins love you.`"^
footnote:[Song of Solomon 1:3]
It was virgin souls in ages past that loved the name of the Lord.
It is the virgins now that love the name of the Lord.
Those that are joined to any other lovers cannot love the name of the Lord,
though they may pretend much love to it.
Their hearts have gone a whoring after other lovers,
and though they profess love to the name of the Lord,
and take it often into their mouths, and draw near to him with their lips,
yet their hearts are gone astray, and they do not depart from iniquity.
So though they confess and profess the name of God in words, yet they deny him in works.
Such confessors and professors cause the name of God to be blasphemed among the heathen.

This is the name of the Lord by which he
has made himself known unto us--the light.
The pure everlasting light that now shines in our hearts, this is the name of the Lord.
For God is light, and in him is no darkness at all.
This is the name of the Lord to us.
As we meet in this name, and wait in this name,
and live together and walk together in this name, we have fellowship with God,
and with one another, and we dwell together as in the rocky fort,
where no evil or enemy can prevail against us.
In this name, the light, there is no occasion of stumbling.
And as we love this name and walk in it, we are so far from falling that we stumble not.
It is outside of this name where the stumbling and falling and evil-doing is found.
For he that does evil hates the light, and does not bring his deeds, thoughts,
and words to it, and so walks, talks, and works in the darkness,
not knowing what he says, where he goes, or what he does.

All the professors of Christianity, and all sects upon the face of the earth,
may be tried, measured and judged by this one thing,
regardless of their talk of loving the name of the Lord--if they do or commit evil,
they hate the light.
This is a universal, infallible truth; let their profession be what it will.
If people are found in evil-doing, they hate the light, are enemies to God,
loving their evil deeds.
This name of the Lord, the light,
which makes all things manifest and judges every appearance of evil,
is that which the sect leaders in Christendom despise and set aside,
and so they know not the salvation that is in it.
But to them that believe in it, this name is precious,
and they possess and do witness the sweetness and salvation that is in it.
And this is the salvation that these have waited for, and do partake of,
even to be saved from sin, from the doing, speaking, and thinking of evil,
even while they dwell in these houses of clay, in these earthen vessels.
These have and do enjoy the heavenly treasures.

It is a strong delusion indeed,
and a gross doctrine of devils that has overspread
the world of mankind in the great night of apostasy,
wherein and whereby people are taught and persuaded that
it is impossible to cease from sin during the term of life,
and that, though they continue and remain in sin,
yet they shall enjoy the salvation of God after they are dead.
Truly this may very fitly be called the doctrine of devils and a strong delusion,
a state wherein people are given up to believe a lie, seeing that "`as the tree falls,
so it lies,`"^
footnote:[Ecclesiastes 11:3]
and there is no repentance in the grave.

This is the happiness of a remnant in this day,
that they know the name of the Lord exalted and set
above every name in heaven and in earth within them,
and know everything in themselves bowing to it and worshiping before it.
Here the King of righteousness is upon his throne.
Here the righteous bear rule, and the land rejoices,
and peace is found within their borders.

This is my testimony, that none can enjoy true peace,
but as they witness this name of the Lord exalted in their
hearts above everything--above gold and silver,
house and land, wife and children, and self-reputation, yes,
above all heavenly names as well as earthly,
having every thought and imagination brought down and subjected to it.
There is no other name given under heaven whereby men can be saved
from their enemies within (which are their greatest enemies) but
only as they witness this name of the Lord exalted in them,
even his name who said, "`I am the light of the world.`"^
footnote:[John 9:5]
This light shows unto man his enemies, and not only so,
but destroys them with the breath of his mouth, and the brightness of his coming.
Power is in his name--the light--which makes all things
manifest to destroy and expel all that is contrary to it,
and redeem mankind from under the power of it.

A remnant are living witnesses in this our day,
and in love and good-will are ready to tell their neighbors, countrymen,
and acquaintances,
what the name of the Lord (through their loving of it) has done for their souls,
so that these may be persuaded to embrace it,
and come to experience the like great salvation.
Great is the knowledge that is broken forth in our hearts and understandings,
and glorious is the light of that day that now shines.
What then remains,
except that all that have received this knowledge do walk answerable to it?
And that all, in whom this light shines, abide in it and love it,
so a vain thought cannot arise, nor an idle word be spoken, nor an evil deed be done,
but these are judged and condemned by the light.
This light that judges every appearance of evil is a day of judgment,
wherein men give an account for every idle word they speak.

[.centered]
=== XXXVII. Drawing Near unto God

It is a certain truth which was testified by the apostle when he said,
"`Great is the mystery of godliness.`"^
footnote:[1 Timothy 3:16]
And this is one of the great mysteries--that though
God is very near unto the sons and daughters of men,
many of them are very far from him.
God is in the world, but the world knows him not.
God, who is light, shines in darkness, but the darkness does not comprehend him.
He is in men, and "`they live, move and have their being`"^
footnote:[Acts 17:28]
in him, and yet they are without him, without God in the world, strangers to him,
though he is not far from every one.

In this stands the happiness of a remnant,
that they know God not only near them and in them,
but also they know themselves near unto him--he dwelling in them, and they in him.
These are they that enjoy the effect of that blessed prayer of Christ Jesus,
that "`they may be one, as you Father and I are one; I in them, and you in me.`"^
footnote:[John 17:21]
This is the blessed unity and heavenly fellowship which
the primitive Christians were witnesses of when they said,
"`Truly our fellowship is with the Father and with his Son.`"^
footnote:[1 John 1:3]
This is a state worth waiting to feel and enjoy.
It is more than words can express, and is the end of all words and declarations.
None are to sit down short of this state.
This is the end of the race, and the mark of the high calling of God in Christ Jesus.
Here is the seeing eye to eye, and the talking with God as a man talks with his friend.
Here is the seeing as you are seen, and the knowing as you are known.
Here is the walking with God as Enoch did, and here is the talking with him as Abraham,
Moses, and the prophets did.
Here is known the coming of the Lord to the last supper,
where the delicacies are prepared, and the well-refined wine.
Here is the fruit of the vine drunk anew in the kingdom of God.
Here is the marriage union, where the water is turned into wine,
where the bride and the bridegroom rejoice together,
where the tears are wiped off all faces, and where there is no crying or pain,
death or sorrow.
Here death is swallowed up in victory, darkness is swallowed up in light,
fear is swallowed up in love, in which there is no torment.
Here is the truth of that saying witnessed, that "`love casts out fear.`"^
footnote:[1 John 4:18]
This is the love which is greater than faith, greater than hope,
is the end of faith and hope, and remains when they are gone.
This was the first, and will be the last.
Blessed are all that dwell and abide in it, for no evil can enter their dwellings.

[.centered]
=== XXXVIII. The Low Valley

It is the blessing of all blessings to know
the low valley where the green pastures are,
where the safe feeding is, where none can make afraid,
and to know the feeding in this low valley where the fatness of the Lord`'s house is,
where the greenness and safety is, and where the ravenous beast cannot come.
The feeding here is more than words; it is the end of all words and declarations.
It is the goal of the Lord in sending his messengers of the everlasting gospel among us.
And it is their crown and rejoicing to find us feeding in this low valley,
where the idle shepherds and their flocks cannot partake with us,
for they know not the way that leads thereto.

The very remembrance of the time wherein the call of the Lord reached us,
and called us out of the holes of the rocks, and off the high hills and barren mountains,
into the valley of Jehoshaphat, where he pleads with all flesh with fire and sword,
and where the judgment is known by which Zion is redeemed, I say,
the remembrance of this day is very precious to a remnant,
and the ministration thereof was glorious in its time.
But this is more glorious:
to dwell in this low valley where the green pastures of life and salvation are fed upon,
where the growing is unto the stature and fullness of Christ,
where there is no fear (for the cause of it is taken away),
where the pleasant rivers run, and where tranquility of mind, peace,
and full satisfaction is enjoyed.
This is the blessing of blessings,
and is the portion of a remnant in this the day of
the Lord`'s love and exceeding riches and kindness.
Those that truly enjoy the least measure of this do esteem it above all the world,
because they well know that all things in the world are
not sufficient to purchase the least drop thereof.

[.centered]
=== XXXIX. Possessing the Good Things

It is a very blessed thing for every particular
to feel and know the Spirit of God within themselves,
bearing witness with their spirits that they are true waiters upon and worshipers of him.
According to the testimony of the patriarchs, prophets, and apostles,
many glorious things are enjoyed by, and do accompany those who wait upon the Lord.
One formerly could say, "`They that wait upon the Lord, shall lack no good thing.`"^
footnote:[Psalm 34:10]
This one sentence is sufficient to try all who claim to wait upon the Lord in Christendom,
who profess a waiting upon him in ordinances, and yet are found lacking the good things.
Poverty, blindness and nakedness, leanness of soul and barrenness of heart,
are their daily companions.
So instead of lacking no good thing,
they lack all good things relating to their inward man.

Another could say, "`They that wait upon the Lord,
their strength shall be renewed, they shall mount upward as upon eagles`' wings,
walk without weariness, run without fainting.`"^
footnote:[Isaiah 40:31]
No bare formal professor in Christendom can be a living witness of these things,
and so may infallibly conclude that they are deceived and
mistaken in the cause when the effect does not follow.
For this is the testimony of truth to all the sects in Christendom,
and to diverse worshipers elsewhere in the world:
let them profess what they will (though it be truth itself),
but if they do not enjoy these good things,
nor feel their strength renewed so as to run without weariness and walk without fainting,
and if they do not grow from grace to grace, from knowledge to knowledge,
nor increase with the increase of God in the inward man,
then they deceive their own souls with a vain, dead, fruitless profession,
which profits nothing, but will vanish like smoke in the day of the Lord.

[.centered]
=== XL. Great Salvation

It is a precious thing to be a witness of the presence
of Jesus in the midst as a peaceable Savior.
Those that know him this way do live, abide, and walk in him,
and are of the number of those who need no repentance.
Indeed, it is a high and heavenly state to come to this degree of knowledge.
None come further, except those who have first known him as a judge and reprover,
as a refiner with consuming fire, and as an overcomer of all the enemies within them.
These know the great dragon bound, the mouth of the bottomless pit stopped,
and so stand upon the sea of glass mingled with fire,
being witnesses of victory over the beast and his image,
and over the mark and number of his name.
These are they that come to sing the song of Moses and the Lamb,
not only upon the banks of salvation,
but in the midst of Jerusalem which comes down from God out of Heaven,
and before the throne of the Lamb, who is the light thereof,
and has redeemed them from the earth, and saved them with a great salvation.

[.centered]
=== XLI. The Precious Pearl

That which was lost is now found.
A remnant in this age has dug deep and found the
precious pearl that was hid in the field,
and many rejoice in the sight and knowledge of it.
But let all understand this:
it is not sufficient to find the heavenly treasure or precious pearl,
but to purchase it and possess it, even by selling all and parting with all for it.
Nothing in our hearts, nothing in our esteem must stand in competition with it;
all must be laid down for it.

It is a true saying spoken by Jesus, "`If any man love anything more than me,
he is not worthy of me.`"^
footnote:[Matthew 10:37]
He alone must reign and rule, and have the government in our hearts.
We must know him to be the foundation, corner, and top-stone, elect and precious.
It is not sufficient to know him as a little "`stone
cut out of the mountain without hands,`"^
footnote:[Daniel 2:34]
smiting at the feet of all imagery,
but we must also know him grown and increased to an exceeding great mountain,
to fill the earth, and to become all in all.
We must know everything to bow at his name--every high thought, every imagination,
and every vile affection.
Every selfish will and desire must be denied, brought down,
and subdued into obedience to the name, to the power of God.

All who have gained, not only the knowledge of the field where the pearl is hid,
but have also dug deep therein and found it,
are to wait for and experience this blessed state.
These must not sit down short of it, having only the sight, knowledge,
and profession of the precious pearl, but instead are to purchase, inherit, possess,
and enjoy it.
Then they will be able to say, "`My beloved is mine, and I am his.`"^
footnote:[Song of Solomon 2:16, 6:3]
Here is the feeding among the lilies, where there is neither toiling nor spinning.

[.centered]
=== XLII. Where the Deceiver Cannot Come

That which makes a people blessed above all the families of the earth,
is that they are sensible (both in their solemn assemblies and
at all times) of that power which makes self of no reputation,
even self in its innocency.
For Christ had such a self, which was humble and made obedient to the death of the cross,
and this was the way to a high and heavenly exaltation.
As people come to walk in this way (as did the Captain of our salvation),
the serpent that beguiled in paradise by drawing mankind into self-exaltation and self-reputation,
cannot ever prevail against them.
For the worship into which this power has led us
begins not when our solemn assemblies begin,
neither does it end when we part, but is found in that which is without beginning or end,
even in the Spirit and in the truth, into which the deceiver cannot come.

It is a precious state, a high and heavenly condition,
to witness self made of no reputation,
and to have unity with that power that has made it so.
No temptation can prevail against those that remain and abide in it.
So the whole duty of those that are come to the knowledge of this power,
and come to have faith in it, is always to cleave unto it with their whole hearts,
and to fix their minds upon it,
so that in the midst of all temptations and trials
they may witness deliverance and salvation by it.
Indeed, such as these shall never miss it.

For when Christ was tempted, it is said that after the temptation was over,
angels ministered unto him.
The same is now witnessed in measure by a remnant, praises to the Lord!
These experience the blessedness that attends the enduring of temptation,
and do magnify the power of God over the power of the evil one,
and walk to the praise and glory of it.
Herein they differ from others: not by talk and profession only,
but by living in the sense and obedience of that
power which makes self of no reputation.

Self became of some repute when temptation first entered mankind.
By giving credit to the Devil`'s saying, "`You shall be as God,`"^
footnote:[Genesis 3:5]
etc. a selfish hope was begotten for selfish gain.
And being so deceived, a vain desire of self-reputation sprang and increased,
so that disobedience to the command and power of God and a selfish
hope and confidence were immediate companions in the beginning.
And all the children of the light, who are now come to a dwelling place in paradise,
are to watch against this, lest, as the serpent beguiled Eve, he beguile them also.

[.centered]
=== XLIII. The Sun of Righteousness

The night is far spent, darkness is past, and the true light now shines.
The day of God is dawned, and the day-star is risen in the hearts of thousands.
This state and knowledge is very glorious in its time,
and is more than all the bare professors in Christendom know and understand.
Yet that which we are to wait for, and press after, is a further thing,
or a knowledge of the same thing in a greater degree of glory,
even to know the Sun of Righteousness arise with healing under his wings.
Indeed this is more precious,
and is a greater degree of knowledge--even to experience
the healing virtue of the Sun of Righteousness.

This ministration follows after that of discovering, reproving, convincing,
smiting, correcting, and wounding; indeed this binds up and heals,
comforts and consoles the soul, refreshes and gladdens the heart,
and ministers the joy of God`'s salvation.
To live in the sense and feeling of this healing virtue,
this saving and preserving power (not only in our solemn
assemblies but at other times as well) is very precious.
This cures all diseases and infirmities, and takes away, disperses,
and removes the cause of hurts and wounds, even the cause of smiting, convincing,
and reproving, and preserves from falling into the same again.
So long as we live and abide in it, we can never err, nor ever need reproof, smiting,
or wounding.

It is the world that lies in that state where
the Spirit of God convinces for evil,
reproves, smites, and wounds for transgression,
but to us salvation is now nearer than when we first believed,
and the great day of salvation is come.
Indeed, the restorer of the breach and the healer of nations is come.
Blessed are all that do experience his healing virtue,
and the blessed effect of his appearing with heavenly healing under his wings.
These can say their soul-sickness is cured, and their wounds are not only bound up,
but healed, and they are cleansed and made sound, both in soul, body, and spirit.
These are fitted and prepared to have their citizenship with God in heaven,
and sit there in the enjoyment of the light of his countenance,
which is better than the increase of all other things.
It is the taste of the rivers of pleasure that are at his right hand,
and of the wine in his kingdom,
that engages those that drink thereof to wait to partake more and more of the same.
It is because of the savor of his good ointment that the virgins love him.
If there was no good savor,
if there was not something felt and witnessed of greater worth
and value than the treasures and pleasures this world can afford,
the souls of the righteous would not long after it and become sick of love,
nor be encouraged to wait to enjoy the increase and abounding of it.

In this stands our happiness,
to daily experience and partake of the virtue of this healing, saving,
and preserving power, to feel our hearts and minds joined to it, united to it,
and become one with it.
Herein is our everlasting blessedness,
and what truly distinguishes from all the bare professors
in Christendom--even to walk and abide in this blessed light,
in the Sun of righteousness that is risen and now shines,
and to witness its healing virtue.

[.centered]
=== XLIV. The Tenderizing Power of the Lord

It is a precious state to be of a tender spirit, of a soft heart,
prepared to wait upon the Lord.
Such are in a capacity to know when good comes.
They are not like the parched grassland, nor the barren desert,
but rather like the tender herb, sensible of the dews from heaven,
and the gentle rain that falls, and the fruitful showers that descend upon them.
They can feel the droppings down of divine love,
and they sprout forth and sing for joy in the sense thereof.
But those whose hearts are stony, and whose spirits are hard,
cannot taste and see how good the Lord is.
These are not prepared to wait upon the Lord,
nor to draw near unto him and partake of his divine refreshments,
neither have they the sacrifice wherein his soul delights,
which is a broken heart and contrite spirit.

Oh,
it is a blessed thing for people to meet together and wait in the
sense and feeling of the tenderizing power of the Lord,
even that power that sought us out and gathered us in the beginning!
Indeed it is blessed to have our hearts exercised
in this tenderizing power which is now with us,
and attends us for our good and preservation.
This is that which makes us and our solemn assemblies
differ from all the bare professors of Christianity.
They that so meet and so wait, sit as at the table of the Lord,
feeding upon that which is meat indeed, and drinking of the wine that he has prepared,
feeding upon life itself, and upon substance itself.
This is better than to sit at the table of princes; indeed,
all the banquets and delicacies of the earth are not to be compared to it.

As every mind and heart keeps in the sense of the tenderizing power of the Lord,
they are living witnesses of the preciousness of it.
Here none can forget the lovingkindness of the Lord,
nor let his benefits slip out of their minds,
but are in a capacity to praise and magnify him for all his mercies,
his heavenly blessings,
and the wonderful kindnesses and deliverances that he has wrought for them,
even as great as for any people in any age of the world.
These can say he has not only brought them out of Egypt,
through the Red Sea and wilderness, but also into the good land,
and has divided their inheritance unto them.
They can say their lot is fallen in a good place,
and feeling the flowing of the milk and honey,
they eat and drink and praise the Lord in the sense of all his mercies, blessings,
and salvation that accompany and surround them.

This is the mystery of our fellowship, and the bond of our unity,
as our minds and hearts are exercised in the tenderizing power of the Lord,
especially in our solemn meetings and waiting together upon him,
as everyone keeps close unto this, and are united unto it.
Oh, this is a precious state!
Herein stands our blessed unity and fellowship.
Herein we are strong, even as Mount Zion,
and as a three-fold cord that cannot easily be broken.
As we keep and abide in this, the gates of Hell cannot prevail against us,
and no evil can hurt us.
In this stands our joy and preservation in our meetings, and also in our partings,
and in all times and places--even to feel our hearts
and minds in unity with the Spirit of the Lord,
not now being convinced, reproved, and condemned by it,
but rather justified and commended.
This is sweet and precious indeed, as all that are in it know full well.

[.centered]
=== XLV. The Mind Stayed Upon the Lord

It is he that stays at home that divides the spoil of his enemies.
It is he that stays at home that obtains the blessing.
The wanderer and hunter does not, for he toils and wearies himself,
and sells his birthright.
It is the retired mind, the stayed mind,
the mind whose loins are girded with the girdle of truth and stayed upon the Lord,
that receives the blessing and knows a being kept in perfect peace,
according as it was witnessed of old, "`You will keep him in perfect peace,
whose mind is stayed upon you.`"^
footnote:[Isaiah 26:3]
To enjoy this is the mark of the high calling of God in Christ Jesus,
unto which we have been and are called, even to enjoy perfect peace, to be complete,
lacking nothing.
To enjoy this is the end, sum, and substance of the Christian religion.

It is those that are witnesses of a retiredness and a staidness
of their minds upon the Lord that inherit substance.
It is those that have known the candle of the Lord lit within them,
and have swept their own house and found the piece of silver, that therefore rejoice.
This heavenly light that now shines,
discovers the vanity and emptiness of all things below the sun.
And by the same light, our minds have been redeemed from these things,
and are become living witnesses that neither all the treasures, pleasures, opinions,
and religions that are in the world, nor the bare profession of truth itself,
are able or sufficient to stay or satisfy our souls.
We have found and proved them all to be the very vanity and vexation of spirit.
For the soul of man is in itself more excellent, more noble,
and of greater value than all these things, and superior to them all.
The lesser cannot satisfy or fill the greater, nor can that which is inferior, ignoble,
and less excellent, stay or satisfy that which is superior or more worthy, noble,
and excellent in nature, capacity, and being.
As the soul of mankind is above all created terrestrial beings,
therefore all things under the sun, instead of being food and satisfaction unto it,
prove vanity, emptiness and vexation of spirit.

So blessed is the remembrance of that day and time wherein
our minds were turned to the true everlasting light that now shines,
which has discovered the vanity and nothingness of all things below the sun,
and has redeemed the children of light out from under them all,
up unto him who is in them, through them, and above them all, God blessed forever.
Indeed this light brings into the one true everlasting universal worship,
which stands in the Spirit and in the truth.
Here God, who is light and who dwells in the light, is bowed unto, worshiped, and obeyed.

[.centered]
=== XLVI. Darkness is Past

They have attained to a heavenly state,
who can experientially witness and seal to the truth of that ancient
testimony in the Holy Scriptures--"`Darkness is past,
and the true light now shines.`"^
footnote:[1 John 2:8]
It is a blessed thing to witness the truth of this,
or be able to truly say that darkness is past.
Those that have known what it is to dwell in darkness
and to work and travel in the land thereof,
and have been surrounded and encompassed with the thick
mists and fogs in the dark region of the shadow of death,
such can remember that their steps were taken in solitary places,
and their habitation was with dragons, owls, and bats as their companions,
and there they were stumbling and groping like blind men for the wall.
It is those who have been in this state,
and have now come to know redemption and deliverance from it,
who can say in truth that darkness is past,
and that the true light now shines in and unto them.
Such can call it a blessed state indeed,
and they know that it is more to witness and experience the truth of these three
words--darkness is past--than to hear and read thousands of good words.

There is much in these three words.
The ones that know darkness to be past and gone are come to the everlasting day of God,
to the rising of the glorious Sun of righteousness,
which has caused the very shadows of death to flee away.
In these,
the womb which has bred and generated all the evil
and wickedness that comes forth in the world of mankind,
has been made barren, removed, and vanished away.
They are come to the springing of that day, and to the arising of that sun,
that disperses all the mists and fogs, clouds and errors,
that did surround them and make them to walk in the shadow of death.
Their hearts are made to rejoice in the feeling and enjoyment of this day,
and their eyes become satisfied with seeing the glory of the true light that now shines,
and they find their hearts engaged to walk in the same.
Yes, they not only profess and talk of it, but do walk in it,
and become not only children of it, but young men, fathers, and elders in it.
Walking in the light implies no less than being led and guided by it,
and bringing every thought, word, and deed to it,
to be tried--not only in our solemn meetings and assemblies, but at other times, that is,
in our affairs, dealings, and converse among men, even in our common occasions.
As all are found herein, they are in the true worship of God,
whether together or asunder.

[.centered]
=== XLVII. The Sabbath Rest

These are true and faithful sayings testified
of old--that "`There remains a rest`"^
footnote:[Hebrews 3:9]
which the believer enters into,
and he that is entered into this rest has "`ceased from his own works,
as God did from his.`"^
footnote:[Hebrews 4:10]
This is the substance and antitype of the Jews`' Sabbath,
and this rest is inward and spiritual, even a stay and rest for the soul,
wherein that blessed state (spoken of in old time) is witnessed, namely,
"`You will keep him in perfect peace, whose mind is stayed upon you.`"^
footnote:[Isaiah 26:3]
This is a blessed state indeed, to be kept in perfect peace.
Those that know an entrance into this rest, and abide in it,
know a ceasing from their own works, from following their own thoughts,
and from doing their own will.
Such as these keep the holy day to the Lord,
and know that the day of the Lord (long spoken and prophesied of) is come,
and that the glorious light thereof now shines.

This is the day of the great Sabbath,
in which Christ stands up as a teacher of his people,
and they hear and understand his voice, and follow him,
and shut their ear against the many voices that are in the world.
This is the teacher we have been directed to from the beginning.
We have not been called to a noise or sound of words, nor to a bare profession,
but to inherit substance, to enjoy rest,
even that rest which has been prepared of old for the people of God.
Indeed this rest does remain, and is very glorious,
as those that have entered into it can witness.
And this is my experience and testimony:
that none can enter into this rest except as they know a ceasing from their own works,
their own willing, running and thinking,
and have every thought brought into the obedience of Christ.
Only as far as this is effected,
can any entrance be witnessed into this rest that is prepared,
and that does remain--let the peoples`' talk and profession be what it will.

[.centered]
=== XLVIII. The Old Man Bound

This is a great truth: that where a bridle to the tongue is not known,
and a chain to the will, affections, lusts, and passions witnessed,
the religion of such is vain; for though they may talk of rest and peace,
yet they enjoy none.
John saw an angel come down from heaven,
having the key of the bottomless-pit and a great chain in his hand,
who laid hold upon the dragon, that old serpent, which is the devil and Satan,
and bound him.
Every particular is to see and know this effected in the revelation of God,
before they can witness an entrance into,
and a sitting down in that rest which is glorious,
and into which the light of this glorious day leads the children thereof.
So it is precious to wait upon the Lord, who dwells in the light,
and who leads the children of light into the enjoyment of rest.

[.centered]
=== XLIX. Drawing Near Unto the Lord

Certainly it was the joy and delight of the righteous
in all ages to draw near unto the Lord with their hearts,
and to be inward with him in their minds.
And truly it is the joy and delight of the righteous in this age, who,
by drawing near unto the Lord,
experience the truth of that testimony--those that draw near unto the Lord,
the Lord will draw near unto them.
These are witnesses of his heavenly presence, and partake of the joy of his salvation,
having their citizenship in heaven where God dwells, and walk with him as Enoch, Abraham,
Moses, and the prophets did.
This is witnessed by a remnant in this age, as it was in ages past.
For the day of life and salvation is come,
and the blessed way that leads thereto is known,
and is evidently made manifest to thousands in this our native country,
the island of the gentiles, upon whom the glory of the Lord has risen.

It is a blessed thing to know the way of life and salvation,
but it is more blessed, and a greater degree of happiness,
for every particular (to whom it has appeared) to know themselves
fitted and prepared by walking in the light of life,
in order to possess and inherit salvation.
And this is worthy to be waited for, and is the blessed end of all holy writing, reading,
preaching and believing--even to possess the thing about which words have been read,
written, and preached.
Those who are taught of the Lord, and established in righteousness, not only know it,
and profess it, but are established in it.
This is the mark of the high calling,
which all that are in the way that leads thereto are to press after,
that they may come to the enjoyment thereof.

It is the tasting and seeing how good the Lord is
that raises and quickens desires to enjoy him,
and more and more engages the heart to draw near unto him, and to wait upon him.
It is the tasting of the streams of the river of life and pleasure
that is at the right hand of God that alone renews strength;
and only these are witnesses of the truth of that saying,
"`They that wait upon the Lord shall renew their strength,
and mount upward as upon the wings of an eagle, run without weariness,
and walk without fainting.`"^
footnote:[Isaiah 40:31]
These run in the way of God`'s commandments with delight,
which has become more natural and pleasant to do than ever it was to do the contrary.

This is the blessed state and privilege of many,
to draw so near unto the Lord that they not only taste and see the goodness of the Lord,
but are also filled and satisfied with the renewings of strength, divine refreshments,
and heavenly consolation in their souls,
whereby they are also made more and more in love with him,
and engaged continually to wait upon him.
And in this stands the happiness and preservation of all,
even as the eye of their minds is kept looking unto the Lord and waiting upon him,
even as "`the eye of the maid is upon the hand of her mistress,`"^
footnote:[Psalm 123:2]
and much more.
Where this tasting, seeing, drawing, and waiting is lacking, there weakness, weariness,
and fainting abound,
and the enemy of the soul prevails--let the talk
and profession of religion be what it will.

[.centered]
=== L+++.+++ The Testimony of the Spirit

It is a blessing, yes, the blessing of all blessings,
for every particular to know and feel within themselves that the Spirit of God
bears witness with their spirits that they are the sons and daughters of God,
and that they are begotten by him to a living hope,
whereby they purify themselves even as he is pure, and that they are Christians indeed,
Israelites indeed, in whom is no guile.
This I say is the blessing of all blessings--for everyone
to have the Spirit of God witness these things unto them;
indeed, this is precious to wait for and enjoy.
For he that has called us is holy, harmless, and without guile,
so as we follow and obey him we shall be like him, even as the primitive Christians were,
who said, "`We know that when he does appear, we shall be like him.`"^
footnote:[1 John 3:2]
This testimony of the Spirit of God is more than a thousand witnesses.
It was the only comforter of the righteous in all ages past, and is the same now.

It is good to mind the Spirit and its testimony,
so as to become spiritually minded.
Only then is life and peace known, and death and trouble vanish away,
and the truth of that saying is witnessed, "`To be spiritually minded is life and peace,
but to be carnally-minded is death.`"^
footnote:[Romans 8:6]
Of a truth, the Spirit of grace and truth is come,
and many are living witnesses of its appearance and power,
not only to reprove and convince,
but also to comfort and console those that have and do wait for its appearance,
and are in love therewith, and have their ear open to its teaching,
and their minds and hearts exercised in it.

In this stands the everlasting joy, peace, comfort,
and consolation of the righteous--even as they continually learn of the Spirit of grace,
and are witnesses of its leading and guiding out of all evil into all good.
As they keep in the sense and exercise of this Spirit of grace,
they excel all the bare professors in Christendom.
This alone makes them differ from all others--even that
they grow in spirit from one degree of grace unto another,
from knowledge to knowledge, from faith to faith, from strength to strength,
from children to young men, from young men to elders and fathers,
even to the stature and fullness of Christ, having his mind,
and doing always that which pleases God.
Such are sons of God without rebuke, and are able to say as some did of old,
"`We can do nothing against the truth.`"^
footnote:[1 Corinthians 13:8]
This is a high and heavenly state indeed, which all are to wait for and press after,
which is possible to be attained unto even in this age, as in ages past.
Such can say, "`Greater is he that is in us, than he that is in the world,`"^
footnote:[1 John 4:4]
and are daily witnesses of his strength preserving them out of the evil of the world,
though they live and labor in it, and daily converse with the children thereof.
This is that which keeps us a living, virtuous people--even as we abide in him,
and increase and grow in him, who at first appeared unto us,
and unto whom our minds were at first directed.
Herein we shall be preachers of righteousness, lights of the world,
and the salt of the earth indeed.

[.centered]
=== LI. The Name "`Light`"

It is a precious thing to wait, walk, and dwell in the light,
even in that which makes all things manifest.
Those that wait and walk in it, are led by it to the rising of the Sun,
even the everlasting Sun of righteousness, whose glory, light,
and virtue does as truly disperse and drive away the vain thoughts, dark imaginations,
fogs, clouds, and mists of ignorance and darkness within, as the outward sun does expel,
extinguish, and cause the fogs, mists and darkness to vanish away outwardly.
Of this many are witnesses.

The very remembrance of the first discovery
of truth under the name "`light`" in this our age,
is very precious.
The truth is but one, though it has many names,
and this name--light--is very excellent to a remnant.
Many righteous men and prophets in former ages foretold
the glory of this day or light that now shines,
and prophesied of its breaking forth unto a people that sat in darkness,
who were covered with the shadow of the night, and dwelt in the region of death.
We see the fulfilling of these things,
for indeed we sat in darkness and wandered in desolate places,
and were encompassed with the region and shadow of death.

Oh, how sweet was the light when it first sprang unto us,
and caused us to see over the tops of the high mountains of darkness,
and discovered unto us the secret chambers of imagery, and the hidden things of darkness,
and guided our feet out of the mire and clay,
and set them at liberty to walk in that path which
leads out of the way of death and darkness!
This is that manifestation of light by which all these things are effected,
to which our minds were at first turned, which light judges every appearance of evil,
and leads all that walk in it out of the same.
This is the pathway that not only leads into innocency, but preserves in it.
For there is a possibility in this age (as of old) that people may lose a good state,
and be tempted out of innocency and out of the virgin`'s state,
even after they have attained unto it.
This is why Paul exhorted those to whom he wrote,
that they beware lest the serpent beguile them as he did Eve.
How was that?
By drawing or alluring them out of innocency, out of a harmlessness and sinless state,
into sin or a breach of God`'s commandments, to the loss of Paradise.
This he has done, and may do again.
Indeed people may lose a good state, yes, their place in Paradise,
if they are not watchful.
Therefore it is good to wait and watch in the light,
which not only leads again into the garden of God, and brings to the Tree of Life,
and gives a right to eat thereof, but also preserves in the same,
discovering and giving dominion over the tempter,
and keeping from falling into the temptation.

It is no wonder to us why the old enemy of
mankind rages against the truth under this name--light.
It is no wonder that he gives it so many opprobrious and despicable names,
so that people might not regard it, nor believe in it;
for he knows that it undermines his kingdom of darkness,
and discovers him and all his works, and destroys them also.
We are witnesses of the power and virtue of faith in the light,
that it is able to break all the chains of darkness,
and deliver out of the fetters of death and Hell.
And we also know that there is not any other way or means under
heaven appointed of God that is able to effect this work.
All other ways, means, and inventions of men,
are not able to break one link of the chains of darkness.
It is faith in Christ, the light, which reproves the world of sin.
Though this light shines in the world, even in the darkness, in wicked men,
yet they not having faith in it, nor believing in it as that in which God dwells,
never know its saving power and virtue.
Yet such as these shall not escape its reproving and condemning power.

[.centered]
=== LII. To Know His Name

It is a blessed thing for people to know the name of the Lord,
even as some in ages past knew it (and have left
their knowledge and experience upon record),
who could say and witness that the name of the Lord was as a buckler, as a shield,
as a tower, yes, as a strong tower into which the righteous fled and were safe.
It is very precious for people so to know the name of the Lord,
and to meet together in it.
Such are in a capacity to enjoy, possess,
and inherit all the blessings that ever were promised,
and to avoid and escape all the curses that were ever threatened.

The glorious light of the gospel that now shines is the name of the Lord
whereby he has made himself manifest to us in this our day and age.
As we wait together, and walk in this name,
we are witnesses and experiencers of the fulfilling of that promise,
"`Where two or three are met together in my name, there am I in the midst.`"^
footnote:[Matthew 18:20]
Such as these know their teacher, their Savior, in their midst,
and their eye is towards him, and their ear open to his voice,
who is a teacher that teaches to profit indeed.
Many that have learned of him can say they soon became wiser than all their former teachers.
Thus to hear and learn of him is the blessed end of all preaching, hearing,
and believing, and of all the ordinances, ministrations, dispensations,
and appointments of God,
ever since the fall of man--even to hear and obey the voice of the Son of God,
who is light, and dwells in the light,
wherein the righteous in all ages had fellowship with God, and with one another.

To know this name is more than talk and bare profession;
to know it as a safe hiding place,
a sure rock and tower of defense when the enemy assaults,
when floods of temptations attend, when arrows fly by night, and cease not in the day,
even when storms descend and winds blow.
This was and is the blessed end of the knowledge of the name of the Lord in all
ages--to save and preserve them that have it from all dangers that attend them,
at all times and in all places, and from the enemy of their souls,
that his fiery darts may not hurt them, nor his floods drown them,
nor the storms and winds overthrow them,
nor the enemies of their own house prevail against them.
This was the reason why those who knew it compared it to a strong tower, etc.
They often meditated in it, and thought upon the name of the Lord,
and thereby found strength to abstain from every appearance of evil,
and to resist the devil in all his attempts.
This is a happy state indeed, which only those who know the name of the Lord,
and can trust in it, do enjoy.

By this may all the bare professors of all the various
names in Christendom (so called) be proved and tried,
who talk and profess much of the name of the Lord, but do not depart from iniquity,
nor cease from evil,
nor know his name as a strong tower to save and preserve
them from the strength and power of the enemy of their souls.
These, I say, notwithstanding their great profession of the name of the Lord,
do not depart from iniquity.
And though they take his name into their mouths, they hate to be reformed by him,
which is a great abomination to the Lord, and stinks in his nostrils.
For this I testify in the name of the Lord:
that all people upon the face of the earth (let their name and
sort of religion be what it will) who profess the name of the Lord,
but are found in evil doing, their profession is vain, and their religion is a lie.
In sin they live, and in sin they will die,
except they come to know that repentance which is never to be repented of.
Until this, they can never come to know the name of the Lord as a strong tower, buckler,
or shield, but instead are led captive and ensnared by the enemy of their souls,
even at his pleasure.

[.centered]
=== LIII. The Power of Faith

In this stands our blessedness and everlasting happiness,
as our eye is kept always looking to Jesus, the author and finisher of our faith,
and not only to know him as the author the beginner of faith,
but as the finisher and ender also, and to know the end of faith,
which is the salvation of our souls.
Such as these know "`salvation nearer than when they first believed.`"^
footnote:[Romans 13:11]
It is a blessed thing to have and know that faith of which Jesus is the author,
the least measure of which is very precious and very powerful.
Though it be but as a grain of mustard seed, it removes mountains,
and does wonderful things.

Many are living witnesses in this age, as in ages past, of the power of faith,
even in the beginning of its work.
But it is a higher state to know the end of it, the finishing of faith,
even to know its work done, to know the heart purified by it,
and the victory over the world obtained, the wicked one subdued, overcome, brought down,
and destroyed.
This is a blessed state indeed, and that which all are to wait for, press after,
and witness.
The only way to attain this is to always look to Jesus,
to keep the eye of the mind toward him, and the ear open to him,
who alone teaches to profit, even in silence, when no word is spoken outwardly.
This is the blessed end of the ministry and the ministers
of truth whom the Lord has sent among us,
and of all preaching, writing, and printing,
even that everyone`'s eye might be turned to Jesus,
always looking to him who has begun the good work, and who alone is able to finish it.

[.centered]
=== LIV. Citizens of Zion

It is a blessed state, to be as a stranger and pilgrim on the earth,
and to be able to say in truth (as some of old did), "`We have here no continuing city,
but we seek one to come.`"^
footnote:[Hebrews 13:14]
I say, this is a blessed state; but it is more blessed to find the city sought for,
to know the heavenly city to be come,
even to know the heavenly Jerusalem come down from above, from God out of heaven,
and to be a citizen of it.
Such dwell in a quiet habitation, and are redeemed from the earth.
Indeed,
those who dwell in this heavenly city (where no unclean
thing can enter) dwell not upon the earth,
neither do they inhabit its dark corners where the woe and misery are, as it is written,
"`Woe to them that dwell upon the earth; woe to the inhabitants of the earth,
for the Devil is come down amongst you,`"^
footnote:[Revelation 12:12] etc.

Oh,
let none that talk of and profess themselves citizens of
the heavenly Jerusalem be found inhabiters of the earth!
And all who are not yet fellow citizens with the saints in light,
who dwell not within its gates, let them travel Zionward,
until they come to dwell therein, and become free citizens thereof!
Oh press forward unto this, that you may witness a sitting down in the kingdom!
This is the end of our pilgrimage, the end of seeking a city that will endure,
whose builder and Maker is God.
Indeed, he is worshiped in this city in Spirit and in the truth,
and has everlasting praise from all the inhabitants thereof.
The outward Jew, the outward Jerusalem, the outward temple,
with its outward furniture and worship and worshipers, were shadows,
figures and types of these things.
Jerusalem was the place of worship, and all were to return there to worship,
to make their offerings, and to offer their sacrifices.
And wherever the people prayed or worshiped,
they were to turn their faces towards the city of Jerusalem.
Now the antitype and substance of these things,
and of all the blessed promises relating thereto,
is to be made a witness of the coming down of the heavenly Jerusalem,
and to become a fellow citizen of the saints in light.
All who have not yet come to this, but are in the way that leads thereto,
are to wait for it.

[.centered]
=== LV. The Word of Faith

It is a true saying, recorded in the holy Scriptures, that "`the word is near,
in the mouth and in the heart; none need to ascend or descend to fetch it down,
or bring it up.`"^
footnote:[Deuteronomy 30:14; Romans 10:8]
This was the Word of Faith, preached and believed by the primitive Christians,
and is now again preached and believed by a remnant in this age.

Blessed are all those that know, experience, and abide in this Word of faith,
and hear and obey its voice and teachings, and learn of it,
not only when they meet together in one place, but at other times and places,
and even in their common occasions they lend their ear to it and receive its instruction.
Such will assuredly be made wise unto salvation.
Such will not be always learning and never learned, nor remain laden with sin,
nor be led about by diverse lusts,
but rather will witness the powerful salvation of God through faith in the Word,
which is quick, sharp, and powerful.
It is quick to teach and instruct in all that is good,
and to reprove and condemn all that is evil.
And it is sharp and powerful to cut down and destroy
that which did formerly load down with sin,
and lead into the things that are evil.

Hearing and obeying this Word of life,
this in-speaking Word of God that is near in the mouth and in the heart,
is the only ground of all true learning and knowledge.
All that despise its voice,
and shut their ears against its teachings and have not faith in it,
though they may be furnished with all the academic learning in the world,
and be diligent listeners to the voice of men and books,
yet these will remain strangers to, and ignorant of,
the pure sanctifying and satisfying wisdom, and the peaceable salvation of God.
Indeed, these will remain under the burden and power of sin,
and under the command of their lusts, wills, and passions.
The lack of faith in the Word and power of God within,
and the neglect of hearing its still, small voice,
is the ground and cause of all ignorance, errors, darkness, and confusion among men,
in all sects and sorts of religion upon the face of the whole earth.

[.centered]
=== LVI. Fruits of Faith

It is a precious thing to have faith,
and to be always looking unto Jesus the author and finisher of it,
and to be growing and increasing in it from one degree to another.
They are the blessed people who wait, walk, and live together in this faith,
of which Jesus is the author.
This is the same "`faith which was once delivered to the saints,`"^
footnote:[Jude 1:3]
being the gift of God and not of man.

The least measure of this faith is very powerful,
for though but as a grain of mustard-seed, it is able to remove mountains.
All who know the growth and increase of it, and do persevere therein,
come to know Jesus not only as the author, but also as the finisher of faith.
He is not only the beginner of faith, but the ender of it; for faith has an end,
even the salvation of the soul.
All that attain to that end can rejoice in the salvation of God,
which has come nearer unto them than when they first believed.

Let all the sects in Christendom who talk of having faith in God,
try and examine what their faith has done for them.
If it has not removed mountains of darkness and ignorance,
if it has not purified their hearts, if it has not given them victory over the world,
saved them out of the evil thereof, enabled them to please God, to live unto him,
and to find acceptance with him--I say,
if they know not these things wrought in them and for them,
they may infallibly conclude their faith is dead,
and is not that faith which is the gift of God, once delivered to, and received by,
the primitive saints, of which Jesus was the author.
Rather, theirs is a faith of their own making, and is like the faith of devils,
who "`believe and tremble`"^
footnote:[James 2:19]--this is the only fruit and effect
of the faith of devils and of wicked men.

[.centered]
=== LVII. Called to Inherit Substance

It is a blessed thing to know and witness
a meeting and waiting together in the name of Jesus.
Such as meet in this name, and know Jesus the peaceable Savior in the midst of them,
know the heavenly adorning of a meek and quiet spirit.
These know the Prince of peace and his peaceable government, the Lamb upon the throne,
the righteous bearing rule, the land rejoicing, and heavenly peace in their borders.

Those who truly wait and meet in this name enjoy all the blessings promised.
It is they who know their strength, faith, and confidence in God renewed,
and their wisdom and knowledge increased with the increase of God.
They know the light to shine more and more unto a perfect day, as was witnessed of old,
"`The just man`'s path is a shining light that shines more and more unto a perfect day.`"^
footnote:[Proverbs 4:18]
But before this day is known, Jerusalem must be searched as with candles (even Jerusalem,
the chosen beloved city, and every inhabitant of it).
For the blessed end of searching is to cleanse and purify it.
Indeed, judgment begins at the house of God,
to purge away and sweep out all that does defile, and to lay waste Babylon,
the city of confusion, the mystery of impurity.
These things are to be known and experienced in every
particular--even to know Jerusalem searched and cleansed,
to know Babylon laid to waste and destroyed,
and to know the increase of the kingdom of heaven within, and its power, light,
and glory shining more and more.

As we meet and abide in this name,
we feel the kingdom come and the will of God done, and whatsoever we ask in this name,
we receive, according to Christ`'s promise.
For we have not been called to a sound of words, to figures, types, and shadows,
or to depend upon the lips of others,
though they be enabled to make long declarations of the truth itself.
But we are called to inherit substance, to feel Jesus the truth in the midst,
the Tree of Life in the midst,
to eat of his fruit and sit under his shadow with great delight.
These things are a remnant come unto, and do enjoy.

This is the crown and rejoicing of the messengers and ministers of the
Lord when they come among us--to find us feeding on the bread of life,
enjoying and possessing substance, peace, life and everlasting salvation.
And it is their sorrow and trouble to find a people under the profession of truth,
always learning but never learned,
always hearing and yet ignorant of the voice of the word of life in themselves,
and of that living bread which comes down from heaven.

[.centered]
=== LVIII. Loving the Appearances of Christ

To those who believe, Christ is very precious.
He whom the nations despise, and the builders reject,
this one has become the chief cornerstone to all that believe.
These love him in all his appearances, manifestations, dispensations, and operations,
whether he appear as a judge, a convincer, a reprover,
a refiner with fire and a fuller with soap, or as a comforter, savior,
or prince of peace.
In all these he is precious to those that believe in him,
because they know and believe that the blessed end of every appearance
and operation of his Spirit in them is in order to make them happy.

It is very blessed to know him appear as a judge, a reprover,
a refiner and fuller, etc.
This is much more than a bare profession,
and is beyond all nominal Christians upon the face of the earth;
but it is much more blessed to know him as a finisher of the work,
to know judgment brought forth to victory, to know a being refined, a being purified,
a being sanctified and saved.
This is a state that every believer is to wait for and experience,
without which they cannot be Christians indeed, Israelites indeed in whom is no guile.

For this I testify,
that this is the end of the blessed appearance of the Son of God, the light, grace,
Spirit, power or love of God within (which is all one thing,
though under different names): to work and operate in every true believer in him,
and lover of him, so as to "`make an end of sin, finish transgression,
and bring in everlasting righteousness.`"^
footnote:[Daniel 9:24]
This is the blessed end of all his operations.
The nominal Christian that talks of Christ and his offices, such as king, priest,
and prophet, savior and redeemer, etc. but knows him not first as a refiner, a fuller,
a purger of the floor, and a burner of the chaff with unquenchable fire,
deceives his own soul with a vain talk and profession,
and so never witnesses sin made an end of, nor transgression finished,
nor everlasting righteousness brought in.
Except this be known, all profession is vain,
and people cheat themselves with the name Christian when the nature thereof is lacking.

It is very precious, and absolutely needful,
for every particular that professes the name of Christ,
and says that he is a believer in him,
to feel and know his heart and mind truly in love
with every appearance of him in his soul,
to follow and obey it, and to enjoy the end thereof, namely,
everlasting salvation brought in and sin made an end of,
that the Lord may appear the second time without sin unto salvation.
Indeed, this is worthy to be waited for.
As everyone loves the appearance of Christ,
and joins to it in their hearts against every appearance of evil,
they are in the way that leads to everlasting life, peace, and salvation.
This is the new and living way, and there is not another.
All that are out of this way, and strangers to it in their minds,
their hearts being alienated from it, never come to inherit substance,
nor to know everlasting righteousness brought in,
unrighteousness finished and cast forth, the house swept, purged, and cleansed,
and themselves made a habitation for God in the Spirit.
Instead they remain as a cage for unclean birds, and a place for dragons,
though they may talk of the fame of wisdom, sanctification, redemption, righteousness,
and salvation, yet they are found in the contrary--in captivity and bondage.
Indeed, though they talk of freedom and redemption, sanctification and righteousness,
yet they walk in unholiness and corruption.
Let all concerned consider these things.

[.centered]
=== LIX. Bowing to Jesus

It is a blessed thing for people to meet together in one place with one accord,
all minding one thing,
every mind exercised in the Spirit and in the truth where alone God is worshiped.
This is the worship that a remnant are brought unto,
which worship does not always begin when their solemn meetings begin,
neither does it end when they part.
It is as everyone is found in this,
that they and their worship differ from all the formal
worshipers upon the face of the whole earth,
whose worship stands in the traditions and inventions of men,
in set times and certain places, in saying certain prayers, reading diverse lessons,
preaching and singing, etc.
But when every mind is exercised in the truth,
everything that is contrary thereunto is made to bow and bend unto it.
Every thought, every imagination,
every desire and affection is made subject to the truth,
worshiping or bowing to the name of Jesus.
This is more than bowing the knee, or all bodily exercise whatsoever.
It is more than all the worship "`upon mountains or in Jerusalem`"^
footnote:[John 4:21]
in all the diverse modes in Christendom.
For while the mind is carnally exercised, the heart corrupt, the conscience defiled,
and the understanding darkened, all is but will-worship, self-work,
and voluntary humility, and has no acceptance with God.

[.centered]
=== LX. The Comforter

It is a true saying which Christ spoke to his disciples when he said,
"`If I go not away, the Comforter will not come.`"^
footnote:[John 16:7]
There is much in these words.
Many have read them but have not understood what they read,
for it is a blessed thing to know the going away of Christ after the flesh,
and to be able to say (as one of old did) that we "`know him thus no longer.`"^
footnote:[2 Corinthians 5:16]
These are they who know him come again in the Spirit as a Comforter,
as a Prince of peace, and are witnesses of his peaceable government in their souls,
and can say, '`He is come, and we look not for another.`'

[.centered]
=== LXI. Daily Bread

Of a truth, the times of refreshing have come from the presence of the Lord;
the showers from heaven are falling and the heavenly manna is raining down.
Indeed, many are livingly refreshed, and are become as a well-watered garden.
Those who were as a desert and wilderness are now blossoming as a rose;
and those that were barren now bear and bring forth fruit unto God.
This is the Lord`'s doing, and it is marvelous in the eyes of a remnant.

Blessed are the people that can meet together with one accord,
and sit before the Lord waiting upon him.
Such at times are favored to sit as at a banquet,
and have a table richly spread before them;
they eat and drink and their souls are satisfied.
Their everlasting happiness and blessedness stands in this:
in feeling their hearts and minds continually drawn
near unto the Lord and stayed upon him,
not only in their solemn meetings, but at other times.
In this they are daily preserved in a capacity to
partake of the mercies and blessings of the Lord.
This is a blessed and safe state indeed--to know a stay to the mind,
to know the heart fixed, joined, and settled upon the Lord.
Such as these cannot be easily moved, neither can the enemy prevail against them,
nor the stranger meddle with their joy.
Their bread is sure, and their water fails not.
They are witnesses of the truth of that prophet`'s words, who said,
"`You will keep them in perfect peace, whose minds are stayed upon you.`"^
footnote:[Isaiah 26:3]
What can any desire more than perfect peace, a peace that is entire, lacking nothing,
full of satisfaction and rejoicing in the inward man?
Oh, what would a remnant have given in times past to have known a stay to their minds,
to have known the heavenly treasure, which is sufficient to satisfy, refresh,
and comfort their souls!
This is the pearl of great price.
This is the eating of the Tree of Life indeed,
and is the only way and means to come to the possession of all the treasures
of wisdom and knowledge that lie hidden in Christ Jesus,
and to inherit all the blessings that attend the Christian religion we profess.
But those that are of a wandering mind, with their thoughts, wills,
and affections unsubdued and unmortified,
these are in that state wherein they know not when good comes,
and are like broken cisterns that can hold no water.

So this is the main thing wherein our safety and happiness stands, namely,
to know our minds and hearts drawn near unto the Lord and our eye fixed upon him,
so that after we have partaken of his blessings and been refreshed with his presence,
we may abide in a frame of mind ready to receive of him that which
satisfies our souls and ministers true contentment to our minds.
Nothing is able to do this but the daily bread.
What we eat today will not serve tomorrow.
Give us this day our daily bread-- bread every day fresh from the table of the Lord.
Hereby is the growing from grace to grace, from faith to faith,
from one degree of glory unto another witnessed,
even till we all come unto the stature and fullness of Christ.
The more that any do truly wait to enjoy this,
the more they will feel their strength renewed with heavenly encouragement,
so that they can run and not be weary, and walk and not faint.

[.centered]
=== LXII. The Still, Small Voice

That which makes a people blessed and happy,
is that they hear and obey the still, small voice, which says, "`This is the way,
walk in it.`"^
footnote:[Isaiah 30:21]
This is the voice of the true shepherd, and the sheep know it, follow it, and obey it,
and a stranger they will not hear or follow.
In this lies the safety, strength,
and blessedness of the righteous in all ages and generations past,
even in hearing and obeying the voice of the Lord.
By this they gained victory over their enemies,
and knew them all confounded and brought to nothing.
And this is the strength and blessedness of the righteous in this age and generation,
by which we too overcome our enemies.

As we hear and obey this voice,
we grow strong and prevail against all our enemies, even those of our own house,
which are our greatest enemies.
In obeying this heavenly voice we are called out of all
the crooked ways and bypaths of sin and transgression,
into the straight and living way of the Lord, and are preserved therein.
His voice leads out of the way of sin and transgression,
so that we are not captivated in the way of darkness
and error out of which we have been called,
and from which we have been redeemed and saved with a great salvation.
Praises be to the name of the Lord, who has caused his glorious day to dawn,
and his heavenly voice to be heard and known from all the voices that are in the world,
and from the voice of the serpent.
And blessed be the Lord, that though his voice is many times very low and small,
yet we hear and know it from the voice of our enemy and from the voice of the stranger,
because it calls out of all evil and error, into purity and holiness.
It calls out of all self-will, thoughts, and imaginations, into the heavenly stillness,
self-denial, deep humility, and lowliness of mind,
which is the low valley where the fresh pastures are,
and where the springs of life are known, satisfaction is enjoyed,
and peace and tranquility of mind are possessed.
This is the substance of all.
This is that to which we have been called in this the glorious day of God`'s appearance,
in this his visitation with his Dayspring from on high,
which shines gloriously to a remnant.
Praises to God forever.

[.centered]
=== LXIII. My Redeemer Lives

They are a blessed people who need not seek for their Teacher, their Savior,
and their Redeemer, but instead their eye beholds him, and their ear hears his voice,
witnessing and enjoying what one of old knew when he said,
"`I know that my Redeemer lives, and he shall stand last upon the earth.`"^
footnote:[Job 19:25]
This is a heavenly state (which a small remnant witness),
even to see their Redeemer stand last upon the earth.
He was the first upon it, and is known to be the last also, subduing all under him,
the earth being made his footstool--all earthly-mindedness, earthly desires,
earthly affections, trodden down and trampled upon by him.
Indeed, every vain thought and lofty imagination are subdued under him,
and all our enemies destroyed by him.
But no people or person upon the face of the earth
can witness these things effected in them,
except as they travel through the work of regeneration,
and come to know that their Redeemer lives, not only in himself, but also in them.
Then transgression is known to be finished, and everlasting righteousness brought in.
Then the Prince of peace and righteousness reigns, and sits upon the throne and rules,
even where the prince of the power of the air and unrighteousness did rule.
Then does the land rejoice and heavenly peace abounds in their dwellings,
which peace cannot be enjoyed by any (let them profess what they will,
though it be the truth itself) unless they experientially know their Teacher,
their Savior, and their Redeemer.

[.centered]
=== LXIV. The Lord`'s Highway

The very remembrance of the time when our minds were turned
to the true light that now shines (not only in the darkness,
but out of it) is very precious.
It is in this light that God dwells,
and we are living witnesses of his presence and appearance,
which ministers more consolation, refreshment, and gladness in our hearts,
than the increase of corn, wine, and oil.

The exceeding love and kindness of God in
fitting and preparing instruments in his own hand,
and by his own power, to turn and direct our minds to the light of Christ within,
to the power of God within, is never to be forgotten.
The waiting in this light, and the obedience to it,
makes us and our assemblies differ from those who are strangers thereto.
And as we wait in and obey this light, we never need to seek a teacher, or guide,
or instructor, though no word be spoken outwardly.

It is a precious thing to love this light, and to walk in it,
for this is the only way to be a child of it.
This is the highway that was prophesied should be built up, wherein "`the wayfaring man,
though a fool, should not go astray.`"^
footnote:[Isaiah 35:8]
There is no stumbling in this way, nor occasion of stumbling.
As we walk and abide therein, we are the most contented people, the wisest, strongest,
and happiest people upon the face of the earth.
But out of this way, we are as weak as any other.
And indeed, after we have come to the knowledge of this way, if we abide not therein,
we may also become as wicked as any other.

There is no other way to be looked for, no other gospel to be preached than this,
to which our minds were turned at the beginning, namely, the light, the grace,
and power of God, the pearl, the treasure, the kingdom within.
In this the key is known that opens not only the mysteries of godliness,
but the mystery of iniquity also, and brings our eye to be satisfied with seeing,
our ear with hearing, and our heart with understanding.
Oh, how we are engaged to walk in this way,
and to walk worthy of this love which is shed abroad in our hearts,
of which we are made partakers!
Oh that we may adorn our profession with all holiness of life and conversation,
to the praise of Him that has called us out of darkness into his marvelous light!
To him be the glory forever.

[.centered]
=== LXV. The Leaven of the Kingdom

It is a blessed thing to know the kingdom of God to be come,
even the same kingdom for which Christ long ago taught his disciples to pray,
and for which, in this age also, he has taught his disciples to pray.
It is a blessed thing to know this kingdom to be come,
but it is more blessed to know a sitting down in it,
and a partaking of that wherein it stands, namely, the peace and joy in the Holy Spirit,
which all the kingdoms of this world cannot give or take away.

Now the reason in time past why we, as well as others,
were ignorant of the coming of this kingdom,
and we lacked the enjoyment of that wherein it stands,
was because we disregarded its appearance, and overlooked the seed of it,
and slighted the operation of it, which is like the working of leaven in meal.
This was the cause: because we "`did not regard the day of small things.`"^
footnote:[Zechariah 4:10]
We had no faith in the holy power and spiritual appearance of God within,
though but as a little leaven, or a small seed, which always wrought against evil,
and against the author of it, and his kingdom of darkness.

Now all the sects and sect leaders in Christendom who overlook the seed
of the kingdom (which works like leaven in all that have faith in it) and despise
the appearance and operation of the light and Spirit of God within,
these never know the coming of the kingdom of God, nor the sitting down in it.
Such inherit vanity, reap sorrow, and lie down in misery,
let their talk and profession be never so high.
Indeed, this is the word of truth to them all.
But all that know the coming of this kingdom, and a sitting down in it,
and the enjoyment of that wherein it stands, which is peace and joy in the Holy Spirit,
these are living witnesses of their being gathered from the east, west, north and south,
and of sitting down with Abraham, Isaac, and Jacob, in the kingdom of God.
These can say, as could some of old to whom the author of the Hebrews did write,
"`But you are come unto Mount Zion, and unto the city of the living God;
the heavenly Jerusalem, and to an innumerable company of angels,
to the general assembly and church of the first-born, which are written in Heaven;
and to God the judge of all, and to the spirits of just men made perfect; and to Jesus,
the Mediator of the new covenant; and to the blood of sprinkling,
that speaks better things than the blood of Abel.`"^
footnote:[Hebrews 12:22-24]
Were not these things written in the holy Scriptures, it might be counted unlawful,
if not blasphemy, to speak or write after this manner.
But the kingdom and power of God is one and the same throughout all ages,
and it was the dwelling place of the righteous in all generations.

To this kingdom and power our minds were at first turned and directed,
whose first appearance was like a light shining in a dark place,
like a little seed springing out of a dry ground,
like a little leaven working in the meal,
according to the parables and teachings of Christ Jesus.
This was the lot and inheritance which the holy men
and holy women in ages past waited for and received.
Indeed they glorified and praised God for the enjoyment thereof, even in the midst of,
and over all afflictions and fiery trials.
This was their joy and crown, and the righteous in this age desire no other.

[.centered]
=== LXVI. The Bread Which Nourishes

We have been and are called to inherit substance,
and all that have obeyed this call, and abode with him that has called,
are witnesses of that bread which nourishes up unto eternal life.
These do experience the preciousness and pleasantness that
is found in eating of that bread which comes down from heaven.
The outward bread, upon the outward table, in the outward temple,
was a type and representation of this heavenly bread,
which nourishes those that feed thereupon unto eternal life.

To meet together, and sit together at this table, and eat of this bread,
is better than to sit on thrones with princes, and to eat of their delicacies.
All the treasures and pleasures of this world are not to be compared with it;
for there is nothing able to content the soul,
and to stop its hungering and thirsting after those things that perish with the using,
except the eating of this bread.
And truly, the more any eat of this bread, the more they hunger after it.
There is a pleasure and blessing in hungering and thirsting when
the treasury of living bread and water is ready at hand to supply.
For it is the taste of the crumbs which fall from the children`'s
table that begets this cry in the hearts of a remnant:
"`Evermore give us this bread!`"^
footnote:[John 6:34]

[.centered]
=== LXVII. The Eye Kept Upon the Lord

Blessed are all who have their eye unto the Lord,
and their ear open unto him at all times, in all places,
and in all states and conditions.
For of a truth, God is come to teach his people himself, as was long before foretold.
All that have learned of him, and are guided by his Spirit,
are thereby led within the veil into the holiest of holies,
and know the veil to be taken away--not only the veil of Moses,
and the veil of the outward temple, but also the veil of the flesh of Christ.
These are come to behold him, and to dwell with him,
who existed before the cause of any veil, before the cause of the law,
or the cause of the prophet`'s labor, or the cause of Christ`'s sufferings.
This state is precious to behold, and very delightful to enjoy.
This is the light of his countenance indeed, which is better than corn, wine, oil,
or all visible things.
This is the blessed end of waiting upon God "`as
the handmaid does upon the eye of her mistress.`"^
footnote:[Psalm 123:2]
Whether you are as a babe, as a child, as a young man, as an elder, or as a father,
your duty in all these states and growths is to have your eye unto the Lord,
that he may lead you from the one into the other, and preserve you therein by his grace.
Indeed this grace is able and sufficient to teach you all good,
save and defend you from all evil, lead you into glory,
and establish you in the kingdom thereof forever.

[.centered]
=== LXVIII. Temples of the Holy Spirit

It is a very blessed thing, and they are in a very blessed state and condition,
who can say in truth that their bodies are the temples of the Holy Spirit.
These are they whose eyes behold their teacher;
their eye is inward unto him who teaches in his temple,
and whose glory appears in his temple.
These are a blessed people who have this knowledge; and all that have it,
know how they came by it, and how they became so,
having formerly been the temples of the unclean spirit.
They know the temple that was defiled and polluted, now cleansed and purged,
and the unclean spirit and his works cast forth.
And now these are a watchful people against all that would defile the temple again,
and they are the true temple worshipers in this day and age.

It is in this temple that everyone speaks of the glory of the Lord,
the power of the Lord, and of his wondrous works wrought therein,
even in his "`temple not made with hands.`"^
footnote:[Hebrews 9:11]
This is the antitype and substance of the outward temple built by Solomon,
and the various worships and services therein--even when people are brought
into such a state as to know their bodies the temple of the living God;
that he walks in them, and dwells in them,
according to the ancient prophecies of holy men.
These are a habitation of God through the Spirit.
These are the worshipers in Spirit and in truth,
not only in appointed places and solemn assemblies, but at other times and places,
bowing to every appearance of God in his temple,
in the Spirit and in the truth in the inward parts, which God loves, accepts,
and delights in.

Now the outward temple, after it was finished and sanctified, became defiled,
polluted, and made a den of thieves;
it was therefore robbed and spoiled of all its treasure, and so in the end was destroyed.
This came to pass as a figure, and is written for our learning.
Therefore, let all be watchful and take heed,
lest after they know their bodies made the temples of God, sanctified or made holy,
they become polluted and defiled again.
Such God will destroy with woeful destruction.

It is very precious when people are come not only to know their
bodies the temples of the Holy Spirit (which knowledge is absolutely needful,
for without it there is no being a Christian),
but also are come to know a heavenly stillness, a heavenly silence in the temple,
with no buying and selling and exchanging,
no noise of the workman`'s iron tool in the temple.
For man`'s work defiles the temple, and pollutes the altar,
if a tool be but lifted up upon it.
The best abilities, inventions, and arts of man in the fall,
have nothing to do in rearing an altar, in building a temple, in setting up worship,
or offering sacrifices to God.
Man`'s righteousness and his wickedness are both an abomination to the Lord.

[.centered]
=== LXIX. The Power of the Gospel

The gospel is the power of God unto salvation.
This gospel was preached in Abraham`'s time, yes even in Enoch`'s and Adam`'s time,
and salvation was obtained in it and by it.
Those that obeyed this gospel (the power of God) in those ages,
were saved by it from evil, made just and holy men, friends of God, and walked with him.
So it was before the law, under the law, and throughout the prophets.
All that obeyed the Spirit and power of God obeyed the gospel,
and were redeemed and saved by it from sin and transgression.
All mankind, being fallen into sin and transgression,
had need for the gospel to be preached unto them,
and had need of redemption and salvation by it.
And as it is received and obeyed,
it is known by such to be the power of God unto salvation.

Paul`'s testimony was that he was "`a minister of
that gospel which was preached in every creature under heaven,`"^
footnote:[Colossians 1:23]
which indeed was the universal light, love and power of God,
appearing for the salvation of man.^
footnote:[Editor`'s Note--When speaking of the universal light or love of God,
the early Quakers were not at all advocating the idea of universal salvation or reconciliation.
The word universal is used with reference to their belief that
God offers salvation to all mankind (and not only to a small,
predestined number) through a measure of His light
or grace that witnesses in the heart against sin,
and invites all to find salvation in Christ.
It is this gracious, inward invitation that is universal.
When received, followed, and obeyed,
this light becomes the life and salvation of the soul.
If rejected, the same light becomes man`'s condemnation.
See John 3:19-21.]
All that are true ministers of this gospel are like their heavenly Father,
whose light shines for all, whose rain falls upon all, whose love extends to all.
They are not like the Jewish rabbis, doctors, priests, or ministers of the letter,
who preach not the power of God that brings salvation to all who receive and obey it.
Neither do these bring their disciples into true love, peace, unity, good-will,
and brotherly-kindness one to another, and to all mankind,
and put an end to the contrary.

Oh, the miserable state that poor mankind is brought into, and held captive in,
through the mystery of iniquity working in many of
the nominal professors in nominal Christendom!
For under the name and profession of the Prince of peace, love, goodwill, innocency,
patience, kindness, and all holy virtues,
there is really found and practiced all sorts of wars, fightings, cruelty, violence,
envying, hating and destroying one another.
These are not the fruits of the gospel of God, nor of the ministry thereof,
but rather of men, of the prince of confusion and of Babylon,
and of those who have drunk from the whore`'s cup,
whose wine of fornication has made drunk all the nations.
He that can understand, let him.

[.centered]
=== LXX. Heavenly Jerusalem

Blessed are all those who know themselves members of the true church,
which is built of living stones, elect and precious,
and are made a habitation for God in the Spirit and in the Truth.
Such as these meet together and wait upon the Lord in silence,
and worship in Spirit and Truth, without a book or dependence on a human minister.
Indeed, blessed are all who are of the true church, living stones,
a spiritual house and habitation for God,
who know him to dwell in them and walk in them as in his temple,
teaching and ruling in their hearts.
These are fellow-citizens with the saints in light, and know the heavenly city,
Jerusalem, come down from heaven, and themselves inhabitants thereof.
These have known a redemption from the earth,
and the tongue of the Egyptian sea is dried up.
Yes, these have discovered the seat of the whore,
and the mystery of all her harlotry (under all her various dresses, golden appearances,
and sumptuous array) and they cannot be deceived by them any longer.
These can sing, "`Hallelujah!
Salvation, glory, honor, and power unto the Lord their God.`"^
footnote:[Revelation 19:1]
These can say, "`True and righteous are his judgments, for he has judged the great whore,
which did corrupt the earth with her fornication,
and has avenged the blood of his servants at her hand.`"^
footnote:[Revelation 19:2]
These can say, "`Praise our God, all you his servants, and you that fear him,
both small and great, for the Lord God Omnipotent reigns; let us be glad and rejoice,
and give honor to him, for the marriage of the Lamb is come,
and his wife has made herself ready.`"^
footnote:[Revelation 19:5-7]
Indeed, these are arrayed in fine linen, clean and white,
which is the righteousness of the saints,
and is the wedding garment that all are to be clothed with
who are called to the marriage supper of the Lamb,
who are members of his body, which is his church.
