== A Treatise Concerning Thoughts and Imaginations

Evil thoughts and imaginations are great troublers of the world,
and the one who is given up to follow, obey,
or walk according to his own evil thoughts and imaginations is accompanied by,
and surrounded with, great misery.
It was a sore judgment pronounced against the disobedient,
rebellious Jews in the word of the Lord by Jeremiah, saying, "`Hear O earth,
behold I will bring evil upon this people, even the fruit of their thoughts.`"^
footnote:[Jeremiah 6:19]
And by the prophet Isaiah, the Lord says,
"`I have stretched out my hand all day to a rebellious people,
which walked in a way that was not good, after their own thoughts,
which are thoughts of iniquity, and the act of violence is in their hands.`"^
footnote:[Isaiah 65:2, 59:6]
Also it is written, "`Every thought and imagination of man`'s heart is only evil,
and that continually.`"^
footnote:[Genesis 6:5]
Very great is the misery, bondage, and slavery of mankind in this state.
Indeed, he is an enemy to God, and to himself, and to his neighbor and brother.
Wasting and destruction are in the path of those who have not God in all their thoughts.

Now reader, that which is principally on my mind,
is to set before you a certain infallible way how you may
come to be saved from following or obeying your own thoughts,
and to gain strength against, and get victory over, all your imaginations that are evil.
And also, how you may attain to good thoughts and heavenly meditations instead,
and come to know every good thought and desire brought into the obedience of Christ,
and every evil thought and imagination destroyed and consumed
with the breath of his mouth and the brightness of his appearing.
And when you are restored and brought into the same state man was in before transgression,
even into the garden of God, how you must then dress and keep the garden.
You must then watch over and govern your thoughts (in the wisdom and power of God),
lest the serpent beguile you as he did Eve.

The Source and Nature of Evil Thoughts

First,
you must understand that from the same ground from
which evil thoughts and imaginations arise,
spring all the briers, thorns, and thistles,
and other hurtful weeds in the world of mankind.
In Adam`'s heart, these began to spring, grow, and increase,
just as soon as he began to lose faith in God his maker,
and incline his ear to the voice of the serpent,
and give credit to his lies which begot a vain thought.
From this vain thought a false hope sprung up, that, by eating the forbidden fruit,
they should better their conditions and be as God,
according as the serpent told the woman, the weaker vessel.
In this false hope (grounded upon man`'s thoughts
and imaginations) entered the first transgression,
and when the temptation was entered into, and sin committed,
then thoughts and imaginations began to multiply
and fill the disobedient earthly heart of man.
Now man,
having turned his back upon the heavens and slighted the
voice and command of God (who was his teacher and lawgiver),
lent his ear to the wicked one, and gave up his mind and heart to obey him,
even with thoughts that it was all for the best.

Thus poor man, being deceived with vain thoughts and false hopes,
lost his habitation and dwelling-place in paradise,
though he sought to keep it even after he had transgressed.
For he was soon convinced he had done amiss in eating the forbidden fruit,
and fear possessed his heart, but when he heard the voice of God in the cool of the day,
he sought means to cover and hide himself from the sight of God.
But herein his thoughts were vain, and his endeavors were to no purpose.
The woman, man, and serpent all received the fruits of their own doings.
Nothing but life, goodness, and blessings were known before, but now death, evil,
and cursing (the fruit and effect of disobedience),
became the daily companions of mankind, who found and still finds by experience,
the saying to be true, "`When sin is finished it brings forth death.`"^
footnote:[James 1:15]
All of this, as I have said, entered first by giving place to a vain thought and desire,
in hopes of gain and to better their state.

So man lost his place in the garden which God planted
through neglecting his work which God appointed him to do,
which was "`to dress it and to keep it.`"^
footnote:[Genesis 2:15]
For indeed the garden needed dressing and keeping before the forbidden fruit was eaten,
innocency was lost, and sin was committed.

And this arises in my mind, to testify to all the wise in heart:
that after they are come to find that which was lost, to witness a restoration,
regeneration, and a returning into the innocency of Eden,
yet they have work there to do--for "`dressing`"
and "`keeping`" are two very significant words.
This was the business of man in the beginning, in the state of innocency.
If he had not neglected this work, and slighted the light, power, wisdom,
and glory of God with which he was replenished, he would never have fallen.
When the temptation got into a thought, if he had watched in the light and wisdom of God,
he would have seen and discovered the tendency of it,
and would have prevented its becoming a desire and an act.
But by first giving place to a selfish thought, it soon sprang to a hunger or desire,
and then into an act.
This is the source and progress of sin in this day as well,
which mankind in innocency has power and wisdom from God to prevent, if he abide in it,
and if he keep in his watchtower--the light and strength
of God--which is as near to man as the temptation can be,
and is sufficient to preserve him.
But where this work is neglected, men (yes even holy men) fall,
and they sin after the similitude of Adam`'s transgression,
and are beguiled as the serpent did Eve.
They are drawn out of innocency and a sinless state
even after they have attained unto it.

Therefore let none be high-minded,
but rather fear and take the Second Adam for an example, who when he was tempted,
did not desire after the things that were presented (though very
deceptive in appearance and accompanied with very large promises),
even as the first Adam did.
Indeed, it is written that while the temptation lasted Christ ate nothing,
let nothing in, and gave no place to selfish thoughts and enticements of the enemy,
and so when the temptation was over, angels ministered unto him.
Let this be an example unto all the children of light, and as they do likewise,
the powerful salvation of God shall surround them,
and truly "`neither heights nor depths, angels, principalities, nor powers,
things present, or things to come,
shall be able to separate them from the love of God in Christ Jesus.`"^
footnote:[Romans 8:39]
This is something of a side note.

Now evil thoughts and imaginations are of a multiplying nature,
and do mainly take root and increase in the generality of mankind who,
through evil works, are estranged from the life of God.
These are like a degenerate plant, having sprung up from the seed of the evil doer,
who dwell and labor in that ground which God has cursed,
and know not the "`seed of the woman`"^
footnote:[Genesis 3:15]
to bruise the serpent`'s head,
or to redeem and preserve them from following and obeying their own thoughts and imaginations,
which are evil, and that continually.
And indeed, in that state it cannot be otherwise,
whether their thoughts lead into self-sinning or self-righteousness,
both are an abomination to the Lord,
and are destructive to both the temporal and eternal well-being of mankind.

For since the beginning,
all the wickedness that has been brought forth and committed
in the world has begun or appeared first in thought,
and this thought, being cherished and joined to by the mind, will, and understanding,
increases and increases into words and actions.
That which is clean cannot proceed from that which is unclean.
The heart of mankind in the fall is universally corrupted and desperately wicked,
and so (as has been said), "`The thoughts and imaginations of man are evil,
and that continually.`"^
footnote:[Genesis 6:5]
Therefore, before it can be otherwise,
there is an absolute necessity that every particular
man and woman know and experience in themselves,
their hearts cleansed, purged, purified, and created new.
The ground must be made good before the seed or heavenly plant can grow, increase,
and flourish therein, and before good thoughts,
heavenly thoughts and meditations can arise, spring, and remain therein.

Now, when this state is known and enjoyed, then you are to abide with him,
dwell and walk with him, who has wrought these mighty things in you, and for you.
And in his wisdom and power,
you are to dress and keep the garden (the heart) with all diligence,
that that which would defile may not enter or creep in again, as it did in the beginning.
Indeed,
what the Spirit of God gave man to do in the beginning
(when he was a noble plant in Eden,
wholly a right seed), namely, to dress and keep the garden,
so the Spirit of God now in this age says, "`Watch and pray,
lest you enter into temptation!`"^
footnote:[Matthew 26:41; Mark 14:38]
"`Take heed, lest as the serpent beguiled Eve, through his subtlety,
so your minds should be corrupted from the simplicity that is in Christ.`"^
footnote:[2 Corinthians 11:3]

A Means Ordained to Cleanse the Heart

Now this I testify from certain knowledge:
that though the heart of mankind is so corrupted
that nothing that is good proceeds out of it,
nor can anything that is heavenly and of God,
spring up in it and live even a moment (being so foul and so dark,
like a foul dark piece of natural earth upon which the sun never shines,
nor the rain falls), yet even so,
God has ordained a means by which man in this miserable
state may come to know and experience his foul heart cleansed,
purged and sanctified, as the Christians in the primitive times did.
"`Such were some of you, but now are you washed, cleansed, and sanctified,`"^
footnote:[1 Corinthians 6:11]
etc.
The fallow ground may be plowed up,
and the bare seed and wilderness may become a fruitful field,
and streams may break forth in the desert,
and the desert may come to rejoice and to blossom as a rose.
Indeed, crooked things may be made straight, and rough places smooth.
Great, heavy, and dark high mountains may be brought down and removed,
yes melted at the presence of God, and the low valleys may be exalted.
Truly, the wilderness may become like Eden, and the desert like the garden of the Lord.

In this age,
the Lord has wrought all of these mighty works and wonders in and for a remnant,
who have come to the fulfilling of these prophecies, and are living witnesses of them.
And these, in his Holy Spirit and power,
do proclaim that the love and mercy of God towards lost man is universal,
and that his hand is stretched forth to help him out of the snare, pit,
and deep dark dungeon wherein he is fallen,
and out of which he cannot (by all his strength, wisdom, and invention) help himself.
Indeed the Lord has appeared to set him at liberty,
that he may run the ways of his commandments with delight,
and that he may come again to stand upright (even as God made man in the beginning),
and lay aside all his thoughts and inventions whereby he has corrupted himself.
Surely the Lord desires to bring him into such a state and condition
that he may be able to do all things that are good,
to think good thoughts, speak good words, and do good works,
and so avoid and abstain from the contrary.
To know and be able to do this is the one thing needful, and without it,
all men are miserable--let their knowledge, wisdom, opinion, invention,
and profession of religion, be what it will.

Therefore my mind is in goodwill to mankind,
having received knowledge and understanding of the means
that God has ordained for their good and salvation.
And being somewhat acquainted with the two great mysteries of godliness and iniquity,
and the way and working of each,
it is my desire to impart and signify something of the same in a few words,
in order to instruct and inform those to whom my testimony may come,
how they may attain to these things,
and how they may come to be rid of those troublesome companions, namely,
evil thoughts and imaginations which arise in the heart while corrupted,
and also how the heart may be purified and made a holy habitation for God,
as it was before sin entered, before innocency was lost,
before the serpent deceived the weaker vessel, when all was good, yes very good.

Whoever you are that has a mind or a desire to find that which is lost, observe,
believe, and receive what I write as truth--not truth received or learned by tradition,
but by the experiential and powerful work and operation
of the Spirit of truth in my own mind.
And indeed, what I have said, or shall say, is according to the holy Scriptures,
and is witnessed to by them, for I cannot write contrary to them,
being in unity with them, and with the just men`'s spirits that wrote them.
Therefore, the way I declare to is as follows: First, you must know O man,
whoever you are, and whatever your thoughts and imaginations are,
however far you have run into corruption, darkness,
and degeneration from the state of innocency, purity, and holiness,
yet there is a measure of divine light that attends you.
Though you are darkness, it shines in you, in order to show you your way out of it.
Though you are degenerated and run out from God into the earth,
yet this pure light and Spirit of God follows you, and calls you back,
and you may (even in this state) hear it as a voice behind you, saying, "`Return, return,
this is the way, come and walk in it.`"^
footnote:[Isaiah 30:21]

Truly, this is the kindness and love of God to you in his Son,
who is the light of the world,
and who "`enlightens everyone that comes into the world.`"^
footnote:[1 John 1:9]
If you hear and obey this voice of the light of the Son of God,
though you were dead in sin and buried as in a grave,
yet you shall arise and come forth and live before him;
the bars and gates of hell shall not be able to retain you.
But if you slight and despise the light of God that visits you,
and shut your ear against its voice, it will be as a thousand witnesses against you,
while you rebel against it and are found following your own thoughts and imaginations,
and doing the things that are evil.

For this light I speak of is the "`eye of the Lord,
that runs to and fro throughout the earth,`"^
footnote:[2 Chronicles 16:9]
beholding the evil and the good, and discerning the thoughts and intents of the heart.
It is the word that is near in the mouth and in the heart, which is quick and powerful,
sharper than any two-edged sword.
This is the candle of the Lord that searches Jerusalem,
and gives light to the ends of the earth, and to the corners of the world,
from whom the shadow of death cannot hide, nor the rocks and mountains cover or defend.
For it is written, "`He that forms the mountains, and creates the winds,
and declares or shows unto man what is his thought, that makes the morning darkness,
and treads upon the high places of the earth, the Lord, the God of Hosts is his name.`"^
footnote:[Amos 4:13]
This is the Spirit of truth that convinces the world of sin,
and sets men`'s sins in order before them, and reproves and smites in secret for evil,
and brings to judgment "`the hidden things of Esau.`"^
footnote:[Obadiah 1:6]
From this eye or light of the Lord, you cannot hide yourself,
any more than Adam or Cain could.
And though you should hate the light which shows you your thoughts,
and love the darkness so as to dwell in it,
yet the light or eye of God will pursue you and find you out.
Neither hell, darkness,
or the utmost parts of the earth can secure you from the just condemnation of God.
For while you hate the shining of his light,
and stop your ear against the voice and teaching of it,
and love the darkness and dwell in it, you choose the way of death,
and neglect the means of salvation that God has ordained.
"`For this is the condemnation of the world, that light is come into it,
and men love darkness because their deeds are evil.`"^
footnote:[John 3:19]

Love and Obey the Light

Now, at the first step towards restoration and everlasting happiness,
you are required to turn your mind from the darkness in which you dwell, to the light,
eye, or Spirit of God, and to resist the power of Satan that works in the darkness,
and embrace the power of God.
When you do but begin to do so,
you will find the scales to fall from your eyes by degrees,
and the veil to be taken off your heart,
and the fetters and chains of darkness to be loosed, and your prison doors opened.
So when your candle is lit, and your eye opened, you will discern your way out,
and see the angel of the Lord go before you, and guide you in the same.
And you will also perceive what is in your house,
and clearly understand what has lodged in the dark room of your heart.
And when you come to see these things as they are,^
footnote:[W. S.--"`The cause of error is a mistake in the understanding
concerning the nature of things that present themselves before mankind.
Thus it is that some call darkness light, and light darkness.`"]
you will receive wisdom to give them names according to their nature,
and to judge righteously concerning them.
And as you love this light,
you will be enabled by it to divide between thought and thought,
and will begin to act according to your conscience, and to hate every vain thought.
And when you cannot be easily rid of them, nor remove them from their old lodging place,
you will breathe and cry to the Lord in the Spirit, as one of old did,
who was burdened and oppressed with their company, saying, "`Search me and try me, O God,
and know my heart, try me and know my thoughts, and see if there be any wicked way in me,
and lead me in the way everlasting.`"^
footnote:[Psalm 139:23-24]
This is the cry which the Lord hears, and will answer in due and needful time.
And Jeremiah`'s cry to Jerusalem was, "`Wash your heart from wickedness,
that you may be saved; how long shall your vain thoughts lodge within you?`"^
footnote:[Jeremiah 4:14]
Now the only way to dislodge them and to be rid of their company,
is to show them no countenance, make no provision for them, give them no entertainment,
but by the light of God which discovers them to be your enemies, judge them,
and keep your mind exercised in the light and power of God that it is turned to.
And though they do and may arise, and pursue and surround you like bees,
yet keeping your eye fixed in the light and power of God
(which is as near to you as your thoughts are,
and shows them unto you).
So you will see them in due time scattered as chaff before a fierce wind,
and destroyed as stubble before a devouring fire.

Now as you come to be a believer in the light,
and to trust in the power of God (to which your mind
is turned) you will become a child of it indeed,
and soon will be able to say, "`Darkness is past, and the true light now shines,`"^
footnote:[1 John 2:8]
by which you can see and judge every thought and
motion that arises and stirs in your mind,
whether evil or innocent, hurtful or harmless, and have wisdom to order them accordingly.
This is that primitive wisdom mankind had in the beginning, but he abode not in it,
through looking at the temptation and beauty of the
thing presented to the eye of his mind.
The woman was deceived in her thoughts.
Indeed, she was beguiled in her judgment and understanding before she obeyed the tempter,
for "`it appeared good for food, pleasant and desirable, and able to make one wise`"^
footnote:[Genesis 3:6]
before she ate or gave to her husband.
Paul says, the woman being deceived,
was in transgression subjected to vanity, not willingly, but through hope,
for she hoped to find the serpent`'s words true, and to become more wise,
and more happy by taking the serpent`'s counsel; but instead thereof,
fell into the depth of misery:

This same danger attends the children of light, the sons and daughters of God,
for Adam was a son of God before transgression.
And it is only those who are in the restoration,
and are children of the light and of the day,
that are capable of falling as Adam and Eve did,
and sinning after the similitude of Adam`'s transgression, losing the innocency, purity,
holiness and uprightness as they did,
and being driven out of the garden of God as they were.
Such as were never in it, nor ever dwelt in the state of restoration, innocency,
purity and holiness, cannot be said to fall from it, or lose it.
Indeed, children of darkness and children of the devil,
who have gone astray and dwelt in darkness and in the region
and shadow of death (as men and women now do in the world),
never knew what the life of purity and holiness is,
nor what the simplicity of the gospel of Christ is,
and so cannot be beguiled as the serpent did Eve of that which they never knew or had.
These are beguiled by the serpent in another way--not
of what they once had and did enjoy,
but of what they might have and would enjoy.
And this he effects by keeping the eyes and minds of people looking abroad,
and by persuading them to follow anything, and walk in any way,
rather than to turn the eye of their minds inward to the Light, word, power,
and Spirit of God.
For truly it is this that shines, speaks, and works in man in order to lead, to teach,
to guide and direct him into the way of life, and salvation,
and to bring him into the glorious liberty of the sons of God,
into a perfect translation from darkness to light,
and from the kingdom and power of Satan, to the kingdom and power of the Son of God,
and to know Christ made unto him wisdom, sanctification and redemption.

This is the blessed end for which God sent his Son as a
light into the world--even to enlighten the Gentile and Jew,
professor and profane, that through him they might believe and receive eternal life,
and enter into that blessed rest that God has prepared,
into which the primitive Christians who believed did enter.
These did not speak their own words, nor think their own thoughts,
nor do their own works, but their heavenly Father spoke in them,
and their thoughts were thoughts of God,
and he wrought all their works in them and for them.
This is a blessed state indeed,
and none are entered into the rest which God has prepared except such
as come to witness and experience these things now in this age,
as the primitive Christians did in ages past.
For while any are found thinking their own thoughts, speaking their own words,
and doing their own works (even though under a profession of Christ and Christianity),
they cannot enter into the rest which God has prepared.
These may create for themselves false rests,
or kindle a fire and walk by the light of their own sparks,
but in the end will lie down in sorrow.

True rest and peace are obtained through a true self denial--a denial of self-sinning,
self-righteousness, self-thinking, and working, contriving and inventing,
self-wisdom and understanding.
All these things must be denied, annihilated, brought to nothing, and confounded.
The feeding upon these things occasioned and still occasions the curse,
together with all the labor, trouble, sorrow,
and torment that has attended mankind since the fall.
These must all come to death before a sitting down in the kingdom of God can be witnessed,
or before any can cease from their own works, as God did from his.^
footnote:[W. S.--"`The feeding on the forbidden fruit, which was good in itself,
though not for food, occasioned (and still occasions at this day),
all the miseries that attend mankind.`"]

Keep Watch in the Light

Now you who are a child of light,
understand this one thing for your comfort and encouragement
in your warfare against evil thoughts:
that notwithstanding a multitude of thoughts do arise in you,
and troops thereof attend you, which are sinful in themselves,
yet if you join not with them in your mind, will, and understanding,
they are not your thoughts, neither shall the evil thereof be imputed unto you.
If you love the light, and keep your mind joined to the Spirit of God,
or the appearance of Christ in you that discovers all temptations
unto you in the very thought and first appearance of them,
then you are helping the Lord against the mighty.
For being joined unto him, you are becoming one with him in your mind and spirit,
though in your members there is a law or power that wars against you.
And as you abide with the Lord, waiting upon him,
even as "`the eye of a maid waits upon the hand of her mistress,`"^
footnote:[Psalm 123:2]
he will save and deliver you, and subdue all your enemies, even those of your own house,
which are the greatest enemies.

Though temptations may and will attend you, yet it is no sin to be tempted,
even with inward temptations.
And you are not to account yourself (nor will you be accounted) a sinner,
because sin and vain thoughts may present themselves in you, in your warfare state.
Instead, you may say as Paul did, "`It is no more I, but sin that dwells in me,`"^
footnote:[Romans 7:20]
and that "`in me, that is in my flesh, dwells no good thing.`"^
footnote:[Romans 7:18]
Indeed, you are now in the way to know how this flesh withers as the grass,
and the glory of it becomes as the faded flower of the field,
and how the sin that dwells therein is destroyed,
and how the creature of God`'s making is preserved,
and the earthen vessel that holds the heavenly treasure is sanctified, saved,
and delivered from the yoke of bondage under which the whole creation of God groans.
And you shall certainly arrive at this, as you keep your eye upon your Savior,
your light, your way, your Captain,
whom you will see go before you conquering and to conquer,
till all his and your enemies are subdued, brought under, and destroyed,
and you are made as a king and a priest to God.^
footnote:[W. S.--"`Lest you should stumble at these sayings,
consider that John was the greatest prophet born of a woman,
yet the least in the kingdom was greater than he.`"]
And you will be made to say (as the primitive Christians could say), "`As he is,
so are we in this present world.`"^
footnote:[1 John 4:17]
We are pure as he is pure, holy as he is holy, righteous as he is righteous,
harmless and innocent as he was, in all things resigned up unto the will of God.
"`Not my will,`" said the second Adam, "`but yours,`"^
footnote:[Luke 22:42]
though his will was as innocent and harmless as the first Adam`'s was before the fall,
and did even excel it.
When you come to this, you will understand and receive what I say;
until then it will be as a mystery and a hard saying to you.

And while in your way, take heed of the thinking, willing, and running,
that do not obtain the prize.
"`Stand still and see the salvation of God.`"^
footnote:[Exodus 14:13]
Above all, mind the arm of his power in you, which is able to suppress your thoughts,
mortify your will, stop your running,
and give you perfect strength to resist the devil and make him flee,
and to furnish you for every good word and work.
Indeed, he will give you dominion over your own spirit,
whose natural condition is to be swift in thoughts, eager in desires,
and restless in the accomplishment thereof.

Now it is written,^
footnote:[W. S.--"`Consider the simile, and in the light try to apply it to yourself,
and you will find the truth of it.`"]
"`He that has rule over his own spirit, is stronger than he that takes a city`"^
footnote:[Proverbs 16:32]
and, "`He that has no rule over his own spirit, is like a city broken down,
and without walls,`"^
footnote:[Proverbs 25:28]
and "`When the righteous bears rule, the land rejoices; but when the wicked,
the land mourns.`"^
footnote:[Proverbs 29:2]
These things are infallibly true.
While the usurper keeps the throne,
the Prince of peace and his peaceable government is not known.
Tribulation and anguish comes upon every soul of man that does evil,
that thinks and imagines evil,
and that yields his members as servants to unrighteousness, let his opinion, profession,
and talk of religion be what it will.
Indeed, "`He that commits sin is of the devil.`"^
footnote:[1 John 3:8]
And unless they turn from it, and know a finishing or ending of it,
and righteousness set up in the room thereof,
they will have the wages and reward of the same,
and possess the fruit of their own thoughts and doings.

Now it is a heavenly state to live under the government of Christ,
to know and experience him, swaying the scepter in the heart,
and established in the throne thereof.
But none come to enjoy this,
till they have first known him to sit as a refiner with fire, and as a fuller with soap,
and as a spirit of judgment and burning,
and as the stronger man to dispossess the strong man, spoil all his goods,
sweep and cleanse the house, and to furnish it again with heavenly goods, thoughts,
desires and meditations, and all other things that become the house of the Lord.
Holiness to the Lord was written or engraved upon the crown and plate of gold,
and all the furniture of the outward temple was sanctified,
of which this is the antitype, or substance, as he that enjoys it well knows.

And now,
it is the duty of a Christian to watch in the light against evil thoughts,
and to use the ax of God, which is laid to the root of them,
so that their springing up again may be hindered, and the end of them prevented.
So also, it is the duty of everyone,
when good thoughts and desires spring in the room thereof, to cherish them,
to join with them, and to keep the eye unto the Lord that begat them,
or raised them up in the heart.
For such thoughts are from the Lord, being thoughts of purity,
thoughts of peace and righteousness, thoughts of holiness and joy in the inward man,
which thoughts you, of yourself, cannot think.
These are comfortable thoughts, justifying and excusing thoughts,
thoughts that will stand approved in the light, and the end and tendency of them is good,
even as pleasant fruit to the soul.
Such can say, as David once did, "`How precious are your thoughts unto me, O God!
How great is the sum of them!
If I should count them, they are more in number than the sand.
When I awake I am still with you.`"^
footnote:[Psalm 139:17-18]
As you love the light, and delight in the law of God, and meditate therein,^
footnote:[W. S.--"`Good thoughts are of God`'s own
begetting and are very comfortable to a Christian.
These are the fruit and effect of keeping and obeying the law of God within the heart.
Rom. 2:14-15`"]
these good thoughts will multiply and increase in you,
to your great contentment and satisfaction.
But the thoughts of the wicked are sin, and sin brings trouble, anguish, and torment.
Men are accused or excused in their thoughts (Rom 2:15). It is
said that Belshazzar was so much troubled with his thoughts,
that his "`countenance was changed, and the joints of his thighs were loosed,
and his knees knocked together.`"^
footnote:[Daniel 5:6]
Indeed, many are the amazing, tormenting thoughts that attend the wicked,
"`whose feet run to do evil, and make haste to shed innocent blood.
Their thoughts are thoughts of iniquity; wasting and destruction are in their paths;
the way of peace they know not, and there is no judgment in their ways.`"^
footnote:[Isaiah 59:6-7]

Now the thoughts of the righteous are right,
and those who commit their way to the Lord, their thoughts shall be established.
And this is a blessed state indeed--to have good
thoughts established in the heart and in the mind.
Such as these can go forth and come in in peace, lie down and rise up in peace,
live and walk in peace, and praise the God of peace, who is blessed forever more.
And this is the peace, the inward peace,
which the world with all its treasures and pleasures cannot give,
nor by its frowns take away.
This peace is the portion of all that get victory over their own thoughts, imaginations,
lusts, desires, and affections, and who also keep in the wisdom and power of God.
And when good thoughts are established in them,
and they are so made partakers of the divine nature,
then they naturally think good thoughts, thoughts of love, peace, and obedience,
even as they did think the contrary while in the state of degeneration.

Nevertheless, in this state of innocency and harmlessness,
you must still be diligent in the wisdom of God to dress and keep the garden.
Take heed lest, having found honey,
you eat more than may suffice to nourish the right birth,
and you feed yourself without fear, and eat and drink and rise up to play,
and grow idle and wanton through having plenty, and so forget the Lord.
Yes take heed lest his benefits slip out of your mind, and you slight his commandments,
and allow pride and exaltation in your selfish spirit to grow up again--even
as the first Adam and others have done (mentioned in the holy Scriptures,
which are written for our learning and admonition,
upon whom the ends of the world are come.) Therefore let him that thinks he stands,
take heed lest he fall.
