[#chap4, short="Concerning Christian Worship"]
== Concerning Christian Worship In What it Stands and How it is Performed

There is a great contest in Christendom among the diverse
sects and bare professions of Christianity about worship,
and many are the modes and ceremonies that are commended among them.
Every sect conceives their way to be right, and all are full of dispute, contention,
and quarreling one with and against another, envying and hating one another, fighting,
killing and destroying one another.
Such as these, however, are all creations of man`'s own devising.
They are forms and images of man`'s own making, mostly from the example of Jews, Gentiles,
and apostate Christians,
into which they have not been led or guided by the unerring
Spirit of God (as their fruits makes fully manifest,
to the great scandal of the Christian religion.)

Now the true Christian`'s worship is in the Spirit and in the truth,
not in the letter, nor in the bare form.
This worship was before all letters and outward laws and prescriptions, inventions,
errors, and before the spirit of such things.
Indeed, this was the worship in Paradise.
When mankind neglected this worship, he fell into evil, into invention, into error,
which was the cause of the outward law,
and all other dispensations of God for the recovery of lost man.
And before man can witness a return out of his lost state,
he must come again to the same worship in the Spirit and in the truth,
even the truth in the inward parts, for that is it which God loves.
Yes, man must come to the word in the mouth, to the law in the heart,
and the fear in the inward parts.
And he must come out from all fear towards God which is taught by the precepts of men,
from all traditions of men of corrupt minds, from all devices and inventions of men.

This worship in the Spirit and in the truth is the
blessed state into which the true Christian comes,
and it is the end, sum, and substance of all holy writings, forms, and holy traditions,
ministrations, and dispensations before the law, under the law, and in the prophets.
The worship in the wilderness, in Jerusalem, and all temple-worship,
stood in diverse bodily exercises, outward works and services, a variety of offerings,
observing of times, days, months, and years, meats, drinks,
outward washings and purifications, new-moons, fasts, feasts, solemn meetings,
and general assemblies once a year at Jerusalem--all
these things were but shadows and typical,
and this worship in Spirit and truth is the antitype
and substance shadowed forth by them all.
Indeed, the substance of all is to worship in the Spirit, in the truth,
to come to Mount Zion, the city of the living God, the heavenly Jerusalem,
to come to the general assembly and church of the firstborn, written in heaven,
and to God the Judge of all, and the spirits of just men made perfect.
It is to know the heavenly city that comes down from God out of heaven,
even Jerusalem the mother of all the living citizens thereof,
whose law and covenant is spiritual and written in their hearts, and whose love, fear,
and obedience to God is engraved in their inward parts.
From here arises the true worship in the Spirit, and in the truth.

This is the worship to which the primitive Christians came,
and they were exercised therein.
Indeed, they prayed in the Spirit, not at any set time or appointed place only,
according to the exhortations: "`pray always,`"^
footnote:[Luke 21:36]
"`pray continually,`"^
footnote:[Luke 18:1]
"`pray without ceasing,`"^
footnote:[1 Thessalonians 5:17]
"`I desire that men pray everywhere, lifting up holy hands without wrath or doubting,`"^
footnote:[1 Timothy 2:8]
etc.
They breathed to the Lord in Spirit, though never a word was uttered,
in the closet when the door is shut, and the Lord heard and answered this prayer.
And many times they were also led forth to pray publicly in words,
but mostly for the sake of others, and on the behalf of others, as Christ Jesus did.

The true Christian is also a preacher of righteousness, not only in words,
at set times, and appointed places, but in life and conduct.
Yes, in this he is a preacher and a teacher of that which is good,
as a candle that burns and is set in the right place;
his lamp is trimmed and his light shines.
He is as a city upon a hill, as the salt of the earth, and as the light of the world,
to season and give light to others by holy example, which preaches louder than words.

The true Christian`'s singing or rejoicing is also in the Spirit and in the truth,
with a good understanding, and not in iniquity.
He needs no art or invention to bring words into meter or
rhyme in order to make a pleasant sound and a joyful noise.
His music does not stand in outward sounds made by art and air,
but his melody is in the heart, in the spirit, in the inward man,
in the hidden man of the heart.
This is the antitype and substance of all outward music used in the time of the law,
under the first covenant, in the worship and service of God,
and as far exceeds it as the substance of a thing does exceed the shadow.
And he that has this heavenly, inward rejoicing, and this pleasant melody in the heart,
will never invent to himself instruments of music like David,
nor delight in the sounds thereof.
Where this heart-melody is lost, the outward invented music is set up, among Jews,
Gentiles, and apostate Christians.
For the true Christian has come to know Christ Jesus as a Prince of peace,
as a peaceable Savior, as the consolation of Israel, and joy of generations.
Truly he is known to be the giver of peace which the world cannot give or take away,
which far surpasses all the delights of the sons
of men which they can attain unto by nature,
art, and invention.

Now the Spirit of God is universal, and the truth is universal,
and so the true Christian worship that stands in these is also to be universal.
It is not only when people meet together in a solemn manner to wait upon God,
but in every hour and every day, bowing in spirit, worshiping in the truth.
This makes free from all error, from all evil, from all vain observations,
literal traditions, and human inventions about the worship of God.
Yes it makes free from all carnal ordinances, such as music, food, drinking, washings,
feasts, fasts, days and times, which perish with the using.
Though such things were significant in their first institution,
they are not to be touched, nor tasted, no nor so much as handled by the true Christian.
For these things are but beggarly elements and worldly rudiments, which had a beginning,
and must have an end.

And the root or origin of a Christian, which is Christ, is the end of the law,
and of all the types and shadows in it.
Indeed Christ fulfills all the righteousness of it, and of the Prophets and John also.
And it is he who brings in a better hope, a better law, a better covenant,
a better worship--which hope, law, covenant, and worship, are inward and spiritual,
and not outward and carnal, formal or traditional.
And all that are come to this worship in the Spirit and in the truth (which is one pure,
eternal, principle of light, life, and power) and have their hearts tenderized by it,
and their minds exercised in it,
and their thoughts and meditations guided by it--these have
come to the mystery of the fellowship of the gospel.
Yes, these have come to the blessed unity wherein is no strife, no wrangling, disputing,
contention, treachery, wars, cruelty or violence, because they are all minding one thing,
learning of one teacher, following one guide, namely, the grace and Spirit of God.
And though they have diversity of gifts, and have attained to different degrees of faith,
grace, knowledge, growth, and salvation in the same, and though some are as a foot,
some as a hand, eye, ear and mouth, yet all are as members of one body.
The more common has unity with the more noble, the greatest with the least,
the lowest with the highest, the strongest with the weakest.
Nor is there any discord or schism in this well framed body,
of which Christ is the unction, the anointing, the head and teacher.

This heavenly unity is the antitype or fulfillment of the seamless coat of Christ,
woven from top to bottom, which the soldiers did not rend, tear, or divide,
but cast lots for.
And it is the fulfillment of that law that forbade weaving linen and wool together,
and sowing mixed seed.

Now there is no concord between light and darkness, sin and righteousness,
Christ and Belial.
These things are of a different and contrary nature and so cannot unite, cannot agree,
though they are near to each other, sown in one field.
God has sown a good Seed in the field of mankind; the enemy has sown an evil seed.
In many this evil seed has taken root and sprung up above the good Seed,
even among those professing Christianity.
From here arises and grows all the evil will, envy, hatred, strife, cruelty, violence,
bloodshed, wars, and murders in the world,
and until the head of this evil seed be not only bruised but rooted
out of the heart of man (by the promised Seed which God has sown),
all these things will grow up.
Indeed, these evil effects can never cease until the cause be removed and taken away,
as the true Christian knows right well by experience.

Now the Christians indeed,
as they live and abide in this pure internal Seed of light, life, spirit, and truth,
they have unity one with another, and fellowship with God.
They are the brethren whose living together in unity is beautiful to behold,
who have one mind and one heart, and have their minds and hearts always governed, ruled,
and ordered by the good Spirit of God.
As everyone lives and keeps this order, and keeps under this heavenly government,
they cannot choose but to live together in unity, in love, in goodwill, in peace,
heavenly concord and agreement, everyone within himself, with God, and with each other,
and in love to all mankind.
Here is the end of strife, wars, and fightings, both within and without.
And this is the time and state wherein instruments of war and cruelty
are turned into instruments of necessary use (Isa.
2:4).

Any that will abide in this, can no more learn war,
according to the blessed sight and prophesy of Isaiah, that evangelical prophet.
Here Jerusalem is known to be a quiet habitation,
the inhabitants thereof being established in peace and righteousness,
far from oppressing.
From these the cause of war and oppression has been taken away, which is evil thinking,
evil speaking, and evil doing.
Truly, everyone must know and experience this before they can be established in peace,
before they can know the peace of God (which passes
all understanding) to keep their hearts and minds,
and to rule in their hearts, and before they know the abounding of this peace,
and what it means to delight therein--as it is written,
"`The meek shall inherit the earth, and delight themselves in the abundance of peace.`"^
footnote:[Psalm 37:11]

Oh, this is a blessed state indeed!
All wait to possess and enjoy it more and more.
Indeed, this is the blessed end of the gospel of peace, and of the Christian religion.
My breathing unto the Lord is that all who profess this may come to inherit peace,
righteousness, and joy in the inward man,
even to lie down in that peace where none can make afraid,
and to dwell on that holy mountain where there is no destroyer,
and to inhabit that city whose builder and maker is God.
To him be praise and glory forever more!

[.centered]
=== A Few Words Added to the Sensible Reader

You who are awakened out of the sleep of death,
and risen out of the grave of sin, and out of the sea of corruption,
and are come to the exercise of your spiritual senses, so that you can hear, see, taste,
and handle the things of God--you well know what is the
blessed end of all holy men`'s words and writings,
testimonies and declarations, which have proceeded out from the love of God.
Indeed, you know that such were given forth so that those who are yet unholy,
still wandering about in and after the vanity of their own minds, thoughts,
and imaginations, upon the barren mountains, even as sheep without a shepherd,
may come to be gathered and brought home to the true fold of rest.
Only here is safety, peace, and satisfaction to be found for their weary souls,
who have long wandered in desolate places, seeking rest, but finding none,
spending their time, labor, and money for that which does not profit, feed,
and nourish up to eternal life.
To direct these strangers, wanderers, laborers,
and unsatisfied travelers into the way of rest and peace,
this is the blessed end of all words and holy writings, so that men may come to possess,
enjoy, and inherit the things of which others have spoken and written.
Without this, all hearing, reading, seeking, enquiring, toiling, laboring,
spending time and money, is to no purpose.

Now it is the soul of man that lacks rest, and that has gone from its center,
and lost its stay, habitation, and dwelling-place in God.
And innumerable are the thoughts, imaginations, devices and inventions,
willings and runnings, that poor mankind in this state is exercised in,
and carried away with, both Jew and Gentile, professor and profane,
upon the face of the whole earth.
For in all sects and sorts of religions,
those who are sincere and devout propose this end
to themselves in their exercise of religion,
namely, to attain a state of happiness and felicity at last.
Many are the ways, means, precepts, prescriptions, directions,
and observations that men give and receive from one another,
enjoin and persuade one another, and sometimes compel one another by violence,
to walk in and make use of, in order to arrive thereto, as they think and imagine.
But in this age (as of old), the guides and teachers of the people cause them to err,
cause them to go astray and wander from the right way of the Lord.
They err in vision, judgment, and understanding themselves,
and cause all that follow and obey them to do the same, being unskillful guides,
and blind watchmen, and are as the blind leading the blind,
so that both fall into the ditch together.

Now the way to everlasting happiness is but one, both for Jew and Gentile,
which way is Christ, who is the wisdom and power of God, the truth and the life;
and the appearance of this Christ of God is within men, in their hearts.
His first appearance is as a light shining in darkness,
and as a pure spotless Spirit that consents to no evil,
but reproves and convinces all that are found in it.
Now all who write or speak for God, and for the good of mankind,
do turn and direct the minds of men to this light or Spirit,
and endeavor to persuade them to regard its reproofs
of instruction as being the way to life,
and to obey its counsel and teaching as the only means of salvation.
Indeed, this is the way of returning to the rock from which they were hewn,
and to the hole of the pit from which they were dug,
to their habitation and dwelling place in God.

Many thousands in this island, and in other places,
can give testimony that this is the only way and
means that God has ordained for the recovery,
return, and restoration of lost man,
and that all other ways and means (in which they
had been wearying themselves) availed nothing.
But walking in this heavenly way, the light, the Spirit and grace of God within,
and learning of the anointing within, they witness salvation come to their house,
and to surround them as walls and bulwarks.
These witness the fulfilling of that divine prophecy,
"`My people shall dwell in a peaceable habitation, and in sure dwellings,
and in quiet resting places,`"^
footnote:[Isaiah 32:18]
and "`The eyes of them that see shall not be dim,
and the ears of them that hear shall hearken,
the heart also of the rash shall understand knowledge,
and the tongue of the stammerers shall be ready to speak plainly.`"^
footnote:[Isaiah 32:3-4]
These are the blessed effects of walking in the way and path of righteousness,
of which a remnant are now living witnesses,
who can praise and magnify the name of the Lord in the sense thereof.

But none enjoy this blessed state, nor inhabit this heavenly dwelling place,
except as their minds come to be truly exercised by and in the light of the Lord.
By walking and abiding therein, these come to have their minds established, settled,
and stayed upon him who is indeed the only stay of his people,
and the rock of his inheritance.

Truly nothing can be found in the heavens above, nor in the earth beneath,
that is able to satisfy or stay the mind of man, except the Lord.
The mind or soul of man is more noble and excellent than all visible things,
so that all these are not capable to fill or satisfy his soul, or to stay his mind.
Though he might possess the whole world to himself,
yet in the end he will be made to cry out and confess with the preacher of old,
"`Vanity of vanities, all is vanity and vexation of spirit.`"^
footnote:[Ecclesiastes 1:2, 12:8]
But to have the mind stayed upon the Lord, there is pleasure, peace,
and contentment truly found and enjoyed,
according to the testimony of that prophet Isaiah, who spoke in the name of the Lord,
"`You will keep him in perfect peace, whose mind is stayed upon you.`"^
footnote:[Isaiah 26:3]
This is a truth that none knows but he that has it.
It may be easily written, read, or spoken,
but to enjoy being kept in perfect peace is more than words.
It is the end, sum, and substance of all that can be said or done,
and is the reward of the righteous from the immediate hand of God.
It is the end of all holy desires and breathings unto the Lord.
It is the end of the preaching of the gospel of peace and salvation--even to know, feel,
and experience the peace of God to keep the heart and mind, and to rule there.

This is a blessed state indeed, worthy to be waited for and pressed after,
by all that have a sight and sense thereof, and are in the way that leads thereto,
though not yet having arrived.
Go forward in the name of the Lord, even in that name Light,
by which he has made himself known unto us in this age.
By this light you saw the wandering and the unstableness of your mind,
and the multitude of your thoughts, imaginations, and inventions.
Now persevere in the same, and you will become not only a child of it,
but also grow from a child`'s state to the state of a young man, elder, and father.
Keep the faith, and firmly believe,
that that which shows you the wandering and unstableness of your mind,
will be as a shepherd`'s crook unto you,
and in due time will bring you back into the fold of rest.
The same holy light that discovers and shows unto you your thoughts and inward enemies,
will also by the brightness of its arising, disperse and destroy them for you,
and bring you into that state your soul desires, pants and looks after,
even into the presence of the Lord, where there is fullness of joy,
and where the rivers of pleasures run.
Here there is reaping and returning with joy, and singing for joy of heart,
and here is felt the joy of God`'s salvation.
The blessed light of God, or Son of righteousness, in whom you have believed,
is the only way to possess and inherit these things.
And your walking, abiding, and persevering in this is the means.
There is not any other way or means appointed of God to bring man back into,
or establish him in, that paradisiacal state of simplicity that he lost by transgression.

But all that do not walk, abide, and persevere in this way,
after they have come into it,
never attain to that blessed end of its appearing and shining in them.
For a bare knowledge of the truth,
and a profession of the light and Spirit of God within, avails nothing,
if they walk not in it, and are not guided and led by it.
Rather,
this draws down fierce wrath and vengeance upon the head
of such who "`know their master`'s will and do it not,`"^
footnote:[Luke 12:47]
who talk and profess well, but are found doing evil,
and thereby lay a stumbling block in the way of the blind,
and cause the way of truth to be evilly spoken of.
These cause the name of the Lord (by which he has made himself known in this age),
to be blasphemed, by reason of their ungodly deeds under a profession of godliness,
and under a cloak of righteousness.
With such their damnation slumbers not.

And this I testify and declare to all people to whom this may come,
which may also serve as a caution and warning to them:
that if they meet with any under the name, form, and profession of a Quaker,
who in his converse, trade, dealing, commerce, and affairs, does not let his yes be yes,
and his no be no, but breaks his word and promises,
there is need to have a special care of that man,
and to look upon him as one who is false and deceitful with the holy principles of truth,
and as a hypocrite under the profession of it.
He that is false to God, cannot be true to men.
You had better trust and give credit to a heathen or infidel than to such a one.
Indeed, there is no wickedness beyond that which is acted under a cloak of religion.
Such who gain credit and repute by wearing this cloak,
and get widows and orphans money into their hands,
and create great trades by sea and by land,
are some of the worse sort of robbers and cheats, and the cry of the poor, fatherless,
and widows cries loud against them.
This is a short testimony arising in my heart against this sort of wickedness,
wherein I have a little eased my mind, and in the truth remain a friend to all men.
