== Concerning the Life, State, and Enjoyment of a True Christian

The life of a Christian, of an Israelite indeed in whom is no guile,
is a life of innocency, peace, and contentment,
where quietness and true satisfaction abound in the inward man,
so that none can harm him.
He lives in the fear of God, which taught him to depart from iniquity,
and which now preserves him out of the same.
He loves God and his neighbor and hates no man,
and so he fears not what man can do to him.
His bread is sure, and his water fails not.
If he has wife or children, house or land, or the increase of corn, wine, and oil,
he looks upon them as things below,
and so does not set his heart and affection upon them.
He looks upon them as they are, and loves them in their place, but not more than Christ.
Indeed, he loves the Lord above all,
and loves to keep his conscience void of offense towards God and towards man.
If he cannot enjoy his estate and relations according to the will of God,
he is ready and willing to part with them, and can say as Job did, "`The Lord gives,
and the Lord takes away; blessed be the name of the Lord.`"^
footnote:[Job 1:21]

The true Christian is not afraid of evil tidings, and the ruffling of the winds,
and the roaring of the sea do not amaze or frighten him.
He lives the life of faith,
which gives him victory and enables him to overcome all things.
He keeps on the shield of faith, and the breastplate of righteousness,
and the sword of the Spirit, and so is always armed against all assaults of the world,
the flesh, and the devil.
He knows the name of the Lord as a strong tower, as a shield, as a buckler,
as a wall of defense,
and is prepared to suffer and endure all things like a good
soldier with a settled countenance and a holy resolution.
And though by men he may be accounted smitten and forsaken of God,
and not fit to live upon the earth, yet he enjoys heavenly consolation,
pure tranquility of mind, refreshment, comfort, and joy in the inward man.
It is written, "`The King`'s daughter is all glorious within,`"^
footnote:[Psalm 45:13]
and all things that do or can befall a Christian on this side of the grave are
not worthy to be compared to the glory that is and shall be revealed in him.
And even if there were no reward on the other side the grave,
he would not exchange his life and condition for all the glory, riches,
and excellency that the world can afford,
seeing and accounting it all vanity and vexation of spirit, yes,
less than nothing and lighter than vanity.
Having found the precious pearl, which the swine do not regard,
he is willing to part with all for it, knowing its wonderful virtue, riches, and power.
He bids farewell to all the fading treasures and pleasures of Egypt,
choosing rather to suffer affliction and persecution for the sake of righteousness,
than to enjoy the court pleasures of princes.
Hereby he has great gain even in this life; on this side the grave he has a hundred-fold.
He finds by experience that saying to be true:
"`Godliness with contentment is great gain and is profitable unto all things,
having the promise of the life that now is, and of that which is to come.`"^
footnote:[1 Timothy 6:6, 4:8]

So though the true Christian seems (in the judgment of
the wise in their own conceit) to lose the enjoyment of his life,
honor, riches, profit, pleasure, preferment, relations, etc.,
instead thereof he rather finds them all.
Indeed, in the true self-denial he enjoys them all,
and is able to say as Paul did to the Corinthians (speaking of himself and other Christians),
"`As sorrowful, yet always rejoicing; as poor, yet making many rich; as having nothing,
yet possessing all things; having learned to be content in all states and conditions,
knowing how to suffer want, and how to abound, everywhere, and in all things.`"^
footnote:[2 Corinthians 6:10, Philippians 4:11-12]
And where there is true contentment, there is no lack, no poverty, no sorrow,
except that which is turned into plenty, riches, and rejoicing.
This makes the true Christian rejoice in sorrow and sing in the stocks.
This turns a dungeon into a palace, and bonds and chains into liberty.
This turns poverty into riches, loss into gain, and darkness into light before him.
These and many more are the virtues and powerful operations of the precious pearl,
the white stone, the elect and precious stone, the chief cornerstone,
which the wise master builders disregard and stumble over,
and will not use in their building.
But to the Christian indeed this rock is precious.
He is his foundation, his corner and top-stone also.
He is as a treasure better than mountains of gold.
He is like a rock out from which issues the water of life which makes the river
of pleasure--the river which never ceases to run at the right-hand of God.
These things are known and enjoyed by the true Christian as he
arrives at the mark of the high calling of God in Christ Jesus,
and also by those who are true travelers in the way.
But the bare professor, or nominal Christian, knows nothing of these things.

The life, riches, and enjoyment of a Christian are inward and hidden.
Indeed, his life is hidden with Christ in God, and none knows it but he that has it.
His citizenship is with God in heaven,
and his treasure is laid up where he walks and dwells,
and where he sits in heavenly places with his Savior Christ Jesus,
who is made unto him wisdom, righteousness, sanctification, and redemption.
Not only so,
but he is come to see what is the fellowship of the mystery which
from the beginning of the world has been hidden in God.
He is come to know the Lord to be one, and his name one.
He has come to the one body, one Spirit, one hope, one faith, one baptism, one way,
one truth, one life, one God and Father of all, who is above all, through all,
and in all.
This is the blessed end of all the appearances, manifestations, and dispensations,
under all the variety of names and various workings of the
one eternal God towards mankind ever since the fall,
mentioned throughout the holy Scriptures.
Indeed, this is witnessed by the true Christian,
who really enjoys the end of Paul`'s bowing his knees
and praying unto the Father of our Lord Jesus Christ,
of whom the whole family in Heaven and earth is named.

Now the true Christian will come to know a being dead and buried with Christ,
and a rising with him, and not only a seeking of those things that are above,
but also a finding of them.
He will know and experience Christ in all his offices: as a mediator, reconciler,
intercessor, maker of peace, healer of the wound,
and maker-up of the breach that the first Adam made.
He will be known as a quickening Spirit, as the Lord from heaven, as a king,
priest and prophet, as a savior, sanctifier and redeemer,
as a purifier and the one who makes an end of sin,
and brings in everlasting righteousness.
He will be known as a High Priest to present the bride to God without spot, wrinkle,
or any such thing.
And when he is thus known to perform all these offices in and for his people,
he is then by such known to sit down at the right hand of God,
having accomplished the work the Father gave him to do,
having put all things under his feet, and restored all things into their primitive order.
Yes, he is then also known to surrender up the kingdom to the Father,
so that God becomes all in all.
Here the first is known to be last, and the last first; the beginning is the end,
and the end the beginning.
And here is the heavenly rest with him who is without beginning or end; yes,
a rest in pure celestial stillness from all self-working, willing, running, and thinking.
And though an innocency, or innocent self be attained unto,
and a harmless will comes to be known, yet this still must not act, work, will, run,
and think of itself (as the true Christian, who has traveled and experienced,
knows right well), but must say to his Father, "`Not my will but yours be done.`"^
footnote:[Luke 22:42]
Herein man receives wisdom to dress and keep the garden,
and power and strength to resist and overcome the serpent in paradise,
and the dragon in heaven, and to keep his habitation in the heavenly city Jerusalem,
which comes down from God out of Heaven, whose walls are salvation,
and whose gates are praise forever.
