== Counsel to the Christian Traveler

Have you put your hand to the plow?
Look not back!
Keep it there until the fallow ground is plowed up,
and the briars and thorns are rooted out and destroyed,
so that the seed may grow up in you to perfection.
Have you known the kingdom and the power in which it stands
to be like a little leaven hidden in three measures of meal?
Do not hinder its working, but let it leaven the whole lump!
Do you know the field where the pearl of great price is hidden?
Then dig deep and find it!
And when you have found it, sell all and purchase it,
and then you will be the wise merchant indeed.

Have you traveled out of Egypt, through the Red Sea and wilderness?
Have you known the right arm of the Lord accompanying
you and supporting you in your trials,
temptations, and besetments you have there met with?
Keep to the same arm and power that has called, led, and sustained you thus far,
and it will bring you into the promised land.
Not only so, but he will give you a possession therein,
and destroy your enemies that formerly did possess it.
You will have a house given you that you did not build,
a vineyard that you did not plant, and a well that you did not dig,
which shall spring up in you to everlasting life.
You will sit under your own vine, and under your own fig tree,
and lie down where none can make you afraid.
You will be blessed in your basket and in your store, in your going out and coming in,
in lying down and rising up.
These blessings shall assuredly attend you, as you love the day of small things,
and are faithful in following the Lord,
who has appeared by his light and grace to you for your perfect redemption, restoration,
and everlasting salvation.
I say, you will certainly enjoy and inherit these things,
and receive not only the addition of virtue, knowledge, temperance, patience,
etc. to your faith, but also the very end of your faith.
For faith and hope have an end,
and it is a blessed thing to receive their end--even salvation.
And truly, there are none but such as endure to the end who can be saved,
even to the end of the work of God, the new creation of God in Christ Jesus.

=== The Days of Creation Inwardly Known

Many may begin well, and make good progress also, and yet fall short.
They may know the first day`'s work.
Read Genesis 1--the Spirit of God moving upon the face of the waters,
the appearance of light, and the division of light from darkness,
and to call the light day, and the darkness night.
Indeed this is more than all the wise, prudent,
religious men of this world can know or do, who are all as waters,
and the harlot sits upon them,
and the moving of the Spirit of God they despise and disregard.
The appearance of light they also hate, so it shines in darkness and is not divided,
and the darkness cannot comprehend it, cannot give true names to things,
cannot call the light day, nor the darkness night.
Yes, these err and mistake so far as to call the light darkness,
and to call the darkness light.
This all men in the fall are prone to do, and are found doing,
under the old heavens and upon the old earth.
This is something of a side note, to those it does concern.

But to proceed,
they may also know the second and third day`'s work--the
firmament in the midst of the waters,
the waters divided,
the dry land appearing and bringing forth seed and fruit after its kind, which is good.
This is more than words, names, and professions.
Such as these have some standing, some foundation in the midst of the waters.
They are as trees that bear fruit,
and the earth that yields its increase to him that dresses it.

On the fourth day it is written, "`God made two great lights,
the one to rule the day, and the other to rule the night.`"^
footnote:[Genesis 1:16]
The light, and its rule and government, may be known also.
And as in the fifth day`'s work, there may be a bringing forth and multiplying abundantly,
and a flying above the earth in the open firmament of heaven.
And the sixth day`'s work may also be known--"`Made in the likeness and image of God,`"^
footnote:[Genesis 1.26]
blessed and endued with heavenly power and dominion over all,
placed in a garden planted by the Lord.
Yes, a restoration into innocence and uprightness by Christ the power, light, love,
and wisdom of God may be attained to.
Yet in this very state there is danger.
There is a proneness to look out at the beauty of the works of God, to feed upon them,
to delight yourself with them, or to eat that which is forbidden,
unless the law and command of God be kept close and obeyed.

The sun that is placed in the midst of the
works of God must rule the day and its children,
and the moon must rule the night.
He that has wisdom let him understand.
The voice of the serpent must not be listened unto.
If you desire to keep your habitation, and preserve your dwelling place in paradise,
in the garden of God, you must dress it and keep it.
"`Keep your heart with all diligence.`"^
footnote:[Proverbs 4:23]
If anything appears therein that would entice and allure you to break the law of God,
see that you do not consent.
See that you do not do it,
but rather abide in the rule and dominion that God has given you,
not only over the serpent, but over all the works of his hands.
In so doing,
you will understand the reason for the godly jealousy and fear of the apostle,
who said to such as were brought to a good state, even espoused to one husband,
in order to be presented as a chaste virgin in Christ
(which is a state very near the marriage union):
2 Cor.
11:2-3 "`I fear,`" said he, "`lest by any means,
as the serpent beguiled Eve through his subtlety,
so your minds should be corrupted from the simplicity that is in Christ.`"

Now consider:
it is those who are espoused and adorned as a bride for her husband,
who are come to the simplicity that is in Christ,
and have escaped the corruption that is in the world through lust, and who are restored,
redeemed, and brought back again into innocency,
and have a place in the garden of God--it is these that the serpent would again betray,
beguile, and overthrow.
Therefore, keep in the dominion, power, and wisdom which God has endued, armed,
and surrounded you with, and the serpent shall never prevail against you.
Look not at the first Adam, except to take warning by him,
lest you receive the same reward.
Look, rather, at the Second Adam, in whom the serpent, the deceiver, the devil,
has no part.
Though he has power to tempt in paradise, and to make war in heaven,
and to appear before the Lord and accuse, still he could never deceive, overcome,
or prevail against the Second Adam.
No more can he prevail against you as you keep close unto him, armed with his power,
and your mind stayed upon God your Savior.

This will bring you into a surer state than the first Adam had,
and for a time enjoyed in paradise.
Indeed,
you may come not only to be taken and placed into
the garden of God to dress it and keep it,
but you may also come to have a place in his house, in the temple of God,
and be as a pillar therein, and go forth no more.
You may become as Mount Zion that cannot be moved.
Your heart may be established with grace,
and fixed upon the rock that is higher than you,
against whom neither the devices and allurements on the one hand,
nor the storms or tempests of the enemy on the other, can prevail.
You may come to see eye to eye, and know even as you are known.
You may come to know the Lord to be one, and his name one, the first to be the last,
and the last to be first, and to know your heavenly rest with him,
who is without beginning or end, to whom be praise forever more!

This is the blessed end of the work of God that all are
to know wrought and accomplished in themselves by Christ the light,
power, and wisdom of God.
But in the way to this end there is great danger,
as you who have been a traveler therein know right well.
There are many things written for your comfort and for your learning in the holy Scriptures,
which I would have you esteem a great mercy that you have the use and benefit of them.
Concerning these it is said, "`They are able to make wise unto salvation,
through faith in Christ Jesus.`"^
footnote:[2 Timothy 3:15-17]
Christ indeed is the wisdom of God, the opener of the scriptures,
the only leader into the true understanding of them.
And it is through faith in him that the man of God comes to be
made perfect and thoroughly furnished for all good works.
It is the man of God alone who has the comfort of the Scriptures,
and who has unity and fellowship with the holy men`'s spirits that gave them forth.
It is he alone that understands them.
They are as a sealed book to the learned and unlearned, to the professor,
the nominal Christian, and the profane.
Great is the mystery of godliness which is revealed to babes,
and hidden from the wise and prudent scholars of this world.
These make a trade of the written history of godliness for the sake of filthy profit,
to the danger of their own and other`'s souls.

Now, tender friend, in order that you may persevere safely in your way,
always remember the counsel of Christ Jesus:
"`Take heed or pray that your flight be not in the winter, nor upon the Sabbath day.`"^
footnote:[Matthew 24:20]
These two seasons are the most dangerous.
There is much in these words; the wisdom of God spoke them,
and only those who are endued with his wisdom can understand them.
And by the same wisdom, you may be preserved in and through the winter,
and be able to say, "`The winter is past, and the summer is come,
and the singing of birds is heard in your land.`"^
footnote:[Song of Solomon 2:11-12]
And you will also know the Lord of the Sabbath, and rest in him,
who is the dwelling place of his people in all ages and generations.
To him be glory forever and ever more.

=== The Inward Exodus from Egypt

Thus I have briefly shown how the inward work, or new creation of God,
holds parallel with the history of the outward or old creation,
and what danger attends you when you are a plant of God, even in paradise itself,
which man lost through disobedience and transgression.

I have it also in my mind to set before you the
method and order of the wisdom of God in your restoration,
and the danger that attends in the way thereto.
This was shadowed forth in the history of his people under
oppression in the land of Egypt--their cries unto him,
his coming down to deliver them,
his raising up for them a captain or leader to bring them out with a strong hand,
leading them through the Red Sea, destroying their enemies,
and bringing them to the banks on the other side.
It was set forth in his giving them a song of deliverance and salvation,
and leading them through the wilderness, feeding them with manna and quail from heaven,
and water out of the rock,
going before them in a pillar of fire by night and a pillar of cloud by day,
bringing them to Mount Sinai and giving them his law, statutes, and judgments.
By his direction they prepared his ark, reared up his tabernacle, fastened the sockets,
set up the boards and put in the bars, reared up his pillars,
brought the ark of the testimony into the tabernacle, set bread in order upon the table,
lit the lamps, offered sweet incense upon the golden altar,
so that the glory of the Lord appeared in the tabernacle,
and was their guide in all their journeys.
This was glorious in its time.
And the antitype, or the thing signified by all of this,
only the traveling Christian understands.
These were great helps, great benefits and blessings,
accompanying them in the way to the promised land.

Yet consider, notwithstanding all these things,
and all their experiences of the out-stretched hand, power, and presence of the Lord,
his promises to the obedient, and his threatenings to the rebellious and disobedient,
yet they forgot the Lord, and turned back in their hearts.
Yes, through unbelief, murmuring, and disobedience,
they fell by the way and never entered into rest,
into the promised land that flowed with milk and honey.
All who came out of Egypt through the Red Sea (above twenty years old,
except Joshua and Caleb) miscarried and fell short.
And when their offspring came to possess Canaan, the promised land,
consider how in the process of time they corrupted themselves,
and grieved the Spirit of the Lord through their backslidings and abominations,
not only before,
but also after God had caused his temple to be erected
and furnished in a most magnificent manner,
with vessels of gold, silver, brass, and other costly ornaments,
with '`Holiness to the Lord`' written thereon,
and his own presence and glorious appearance therein.
After all this, through sin and disobedience, they became a prey to the spoiler,
and were made captives, and were carried away into a strange land.

These things are written for the learning and warning of the wise in heart,
whose eye God has opened, and to whom he has revealed his arm of power,
and in and for whom he has done many wondrous works.
Yes, these are written so that man turn not again to folly, carelessness, wantonness,
pride, and rebellion against the Spirit of God,
and that they do not deck themselves with God`'s jewels,
and play the harlot with them (as Israel did),
and so receive the like reward in the mystery^
footnote:[Editor`'s Note--i.e. in a spiritual sense]
as they did in the history.
Truly there is as great a danger of this now in the inward,
as there was then in the outward.

Likewise now, in the dispensation of the Spirit, at the end of the prophets,
I will also hint at the work of God therein,
and show that the same danger attends those who now walk in his way.
The mystery of godliness is great, and the mystery of iniquity is great also,
and happy are you if you abide in the light of God which makes them both manifest.
It is not enough to know the light to shine, but you must walk and abide in it,
and be a true child of it.
It is not enough to know the Spirit of truth, and the power of it,
but you must be led by it, joined to it, become one with it, and bring forth its fruit.
It is not enough to know the seed of the kingdom, and the sowing of it,
but you must know it breaking through the clods and growing up,
not only into the stalk and blade, but into the full ear of corn.
And not only this,
but you must know it to be reaped and gathered into
the storehouse for the use of the Lord of the harvest.
It is not enough to know one of the days of the Son of Man, the child born,
and the Son given, but you must know the government upon his shoulders,
with him reigning in your heart, and his and your enemies destroyed.

To attain to this (according to the phrases used in the holy Scriptures),
there is an "`overshadowing of the Holy Spirit`"^
footnote:[Luke 1:35]
to be known, a "`begetting and forming of Christ within`"^
footnote:[Galatians 4:19]
to be known, and a travailing to bring forth, be born,
and grow up from one stature to another, from a child to a young man,
from a young man to an elder.
And there is a suffering with Christ, a taking up his cross daily and following him,
a dying with him and a rising with him, and a seeking those things which are above,
where Christ sits at the right hand of God.
You must be risen with Christ before you are in a capacity
to seek those things that are at the right hand of God.
But it is a farther state to find these things,
and to be seated in a heavenly place in Christ Jesus,
and to sit down in the kingdom with Abraham, Isaac, and Jacob.
And the farthest and greatest state of all,
is to know the kingdom delivered up unto the Father, where God becomes all in all,
and where alone there is safety.

Until this, though you are a disciple of Christ, and become as a chaste,
wise virgin espoused unto him, you must watch and pray,
keeping your lamp trimmed and your light burning, lest you enter into temptation,
lest you slumber and sleep and the door be shut against you.
For there is a possibility, yes, a real danger of loss in all states and growths,
until you get into Abraham`'s bosom.
There the gulf is known to be fixed.
There is no changing states then,
as is signified in the parable of Lazarus and the rich man, Luke 16,
"`Between us and you there is a great gulf fixed,
so that they that would pass from us to you cannot,
neither can they pass to us that would come from there.`"
And to speak a little according to this parabolic discourse between
Abraham and the rich man--they that would descend cannot;
and they that would ascend cannot.
The one can do nothing against the truth, he is so governed by it,
so in love and unity with it.
The other can no nothing for the truth,
he is so in enmity and hardness of heart against it, having lost his day of visitation,
and become sealed up in darkness, in a sense of his loss.
For this greatly adds to the torments of the wicked,
to behold the blessed state of the righteous afar off,
and themselves in a state of torment and misery, crying and praying for mercy and relief.
But they cannot be heard nor eased of their pain, the sun having already set upon them,
and their day having being turned into utter darkness,
which has become their dwelling or habitation, where there is weeping, wailing,
and gnashing of teeth.

So, dear friend, you may perceive by what I have briefly hinted,
by the current of the holy Scriptures, and by your own experience,
that it is no easy thing to be a true Christian,
to go through the work of regeneration unto a new creation of God in Christ Jesus.
It is no easy thing to go through the warfare, and be able to say with the Apostle,
"`I have fought a good fight, I have finished my course,
henceforth there is a crown of glory laid up for me.`"^
footnote:[2 Timothy 4:7]
Yes, it is not easy to come to the wearing of this crown,
and to be more than a conqueror in him that has loved you.

To witness and enjoy these things is the blessed
end of all the dispensations of God since the fall.
He that is the overcomer is more than a conqueror.
He has received the white stone, wherein the new name is written,
which none knows but he that has it.
He is the wise merchant who has sold all and purchased the pearl of great price,
which excels all other things.
He has a right to eat of the Tree of Life, which grows in the midst of the garden.
He is blessed with all spiritual blessings in heavenly places in Christ Jesus.
He is a co-heir, a joint-heir with him, and not only so,
but has come into the possession of his inheritance.
This is his state,
though he may meet with no better reception in the world than did Christ,
the captain of his salvation, and his disciples.

So it is your enjoying of the light of God`'s countenance,
your being joined to the Lord and being made one spirit with him,
your knowing the marriage union (your maker to be your husband), that is your comfort,
your rejoicing, your crown and diadem in prosperity and in adversity,
in heights and in depths, in the palace and in the dungeon, in all states, times,
and places.
You who partake of these things are the only happy men, though your goods may be spoiled,
and your body be in the hands of your enemies,
yet you can really seal to the truth of that testimony of Paul, Rom.
8:18,
"`I reckon that the sufferings of this present time are not worthy
to be compared to the glory that shall be revealed in us.`"
To you this time of revelation is come.
You know the Lord to be come, and his reward is with him a hundred fold,
even in this life, and in the world to come, life everlasting.

Godliness with contentment is great gain,
for it possesses the promises of all good things, present and to come.
They that have resigned up themselves (and all things) into the hand of God,
have nothing to lose, have nothing to take care for, except to please the Lord.
And it is the food and drink of such to do his will,
for his paths are all paths of pleasantness,
and there is no bitterness at the latter end for such as walk therein.

=== Consider and Be Warned

Therefore, consider and be warned by the examples recorded in the holy Scriptures.
Always remember, that they tell you of a people that came to the knowledge of God,
his laws and ordinances, and the manner of worship which he himself commanded,
which while performed in sincerity of heart, he was well pleased,
and his blessings and presence accompanied them.
But when they lost sincerity, uprightness, and integrity of heart,
though they kept in the exact practice and performance of the outward part of worship,
yet all their performances were an abomination to him, and rejected by him.
This is testified by his prophet Isaiah, saying, "`He that kills an ox,
is as if he slew a man; he that sacrifices a lamb, is as if he cut off a dog`'s neck;
he that offers an oblation, as if he offered swine`'s blood; he that burns incense,
as if he blessed an idol.`"^
footnote:[Isaiah 66:3]
This is mighty strange to those that do not know the real cause why these services (commanded
by God) should become so abominable in the sight of him who commanded them.
God looks at the heart, at the inside.
If that be gone astray, if that be corrupted, degenerated,
and fallen in love with the creation,
he accepts nothing as well done from man in this state.
In this state, man`'s righteousness and his wickedness are both an abomination to him.
This was a sore evil which the people fell into under the
dispensation of the law--they kept sinning and sacrificing,
but neglected to hear and obey the voice of the Lord.
Likewise in the dispensation of the gospel, even in the first ages of it,
the like evil was creeping in.
By the preaching of the apostles, many were brought to believe in Christ,
and to make profession of him.
But it soon came to pass with some,
that they were ready to sit down or rest in a profession
and knowledge of Christ after the flesh,
and to observe a form of godliness, but deny and neglect the power.

The ministers of Christ in the primitive times had a great work before them:
First, to persuade and convince the Jews that Jesus was the Christ of God,
the Messiah promised and prophesied of by the holy prophets,
whom they persecuted and slew in one age,
but honored (at least with their lips) and garnished their sepulchers in another.
Secondly, to oppose the continuance of their temple worship,
the shadowy and typical ordinances and observances which God once commanded,
and to bring them out from under them to the thing signified by them.
Indeed they were to believe in him who was the end and substance thereof,
who did fulfill all righteousness contained in the law, in the prophets, and John.

Now,
when they had brought people to believe that Christ was the great
prophet like unto Moses which God had promised to raise up,
how ready were many of these believers to sit down in this belief,
and to content themselves with a knowledge of Christ after the flesh,
just as the Jews pleased themselves with the temple of the Lord,
and with their outward observances, while they lacked the root of the matter, namely,
an upright, broken, contrite heart,
which is and was the only sacrifice in which God delighted.
So the apostles were constrained to testify against
the bare knowledge of Christ after the flesh,
saying, "`From now on, we know no man after the flesh; yes,
though we have known Christ after the flesh, we know him thus no more.`"^
footnote:[2 Corinthians 5:16]
They preached the knowledge of him after the Spirit, revealed, manifested,
and known by the operation of his power and Spirit within.
They affirmed that the ones in whom this knowledge was lacking were reprobates.
It was not enough to know him born of the virgin,
who increased in wisdom and stature and in favor with God and men,
who did many outward miracles, preached many excellent sermons,
gave forth many divine and heavenly precepts, went up and down doing good, suffered by,
for, and because of sin and sinners, died, rose,
and ascended into the glory of his Father.
No, in the primitive times it was not sufficient to know
and believe the history and truth of these things,
and neither is it now.
Indeed, you must also know and experience him in his spiritual appearance, power,
and inward operation, and persevere therein to the end of the work.
Without this, you will be as formal a Christian under the profession of Christ,
and as much rejected in the account of God,
as the outward Jew was when he kept to the outward practice and form of religion,
and boasted in the temple of the Lord and its outward holiness,
while he himself was a temple of unholiness, uncleanness, and corruption.

So, dear friend and fellow traveler, that we may run to the end of our race,
and be certain of the crown, that we may fight, not as those that beat the air,
but as those that go on conquering and to conquer,
keeping under all that would hinder us from running well to the end,
and deprive us of the crown, and betray us into the hand of our enemies; I say,
that we may do this, let us always remember the sayings of the apostle Paul,
who was a wise experienced traveler, and an able minister of the new covenant--1 Cor.
9:26 "`I so run, not with uncertainty.
I so fight, not as one that beats the air.
But I keep under my body, and bring it into subjection, lest by any means,
when I have preached to others, I myself become a cast-away.`"

In the tenth chapter he gives an instance
of the Jews who were baptized unto Moses in the cloud,
and in the sea, and ate of the spiritual meat, and drank of the spiritual drink,
even of the spiritual rock that followed them, which rock was Christ.
Yet these were overthrown in the wilderness, and destroyed of the destroyer,
because when they did eat and drink, they rose up to play, and lusted after evil things.
"`Now,`" says he, "`these things happened unto them for examples,
and they are written for our admonition or learning,
upon whom the end of the ages are come.
Therefore let him that thinks he stands, take heed lest he fall.`"^
footnote:[1 Corinthians 10:11-12]
From which sayings, with our own experience, we may observe and conclude,
that it is the duty of teachers and preachers, hearers and learners, eaters and drinkers,
even in this spiritual dispensation, to take heed that they run well to the end,
that they fight well to the end, that they eat and drink worthily,
lest judgment overtake them while the meat is in their mouths.
For some, even in this generation, after they knew God, did not glorify him as God,
but became vain in their imaginations,
and their foolish hearts deceived them to such a degree,
that under the very form and profession of Christ in his
spiritual appearance and work in the inward parts,
they do oppose and resist the thing itself, both in themselves and others.
And the mist and mystery of iniquity has so wrought in them,
that they cannot see or understand these things.
But all shall certainly escape this sore evil,
who make it their daily practice to walk in the fear of the Lord,
and to keep their minds exercised in his law, meditating upon his mercies and judgments,
new and old, past and present.
In so doing, no evil can prevail or overtake you unaware.

So dear friend and reader, whose good I chiefly aim at through this writing,
I desire you to be weighty and serious in reading, as I have been in writing,
and you will find benefit and comfort ministered into your own bosom.
And you will not only clearly perceive and understand the difference between the light,
careless, reading, hearing, professing and talking of good things, and the serious,
weighty, possession and enjoyment of them, but also between the beginning, progress,
and end of the work of God in the new creation, restoration, regeneration, and salvation.

So, to the grace of God I do heartily commend you, which leads unto glory,
and from one degree of glory unto another.
Truly, this grace is sufficient to teach you all good, and preserve you from all evil,
and in the same I remain your friend and brother,

[.signed-section-signature]
William Shewen
